### ISSUE TITLE
absurdly long hostnames break fpm

### ISSUE THREAD

**Issue by andersje** [jordansissel/fpm#1013]
When my host is named bl-02-rg-2nuyntivo4uh-1-tx4hkhm66czh-srv-x5gnhr6zuc7.abcdef.com i can build an rpm.  (that is 63 characters long)

When my host is named bl-02-rg-2nuyntivo4uh-1-tx4hkhm66czh-srv-x5gnhr6zuc7l.abcdef.com (which is 64 characters), fpm blows up with the following message:

/home/jenkins/.rvm/gems/ruby-2.1.4/gems/fpm-1.4.0/lib/fpm/command.rb:132:in `gethostname': File name too long - gethostname(3) (Errno::ENAMETOOLONG)
	from /home/jenkins/.rvm/gems/ruby-2.1.4/gems/fpm-1.4.0/lib/fpm/command.rb:132:in `<class:Command>'
	from /home/jenkins/.rvm/gems/ruby-2.1.4/gems/fpm-1.4.0/lib/fpm/command.rb:23:in `<top (required)>'
	from /home/jenkins/.rvm/rubies/ruby-2.1.4/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/jenkins/.rvm/rubies/ruby-2.1.4/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/jenkins/.rvm/gems/ruby-2.1.4/gems/backports-3.6.6/lib/backports/std_lib.rb:9:in `require_with_backports'
	from /home/jenkins/.rvm/gems/ruby-2.1.4/gems/fpm-1.4.0/bin/fpm:6:in `<top (required)>'
	from /home/jenkins/.rvm/gems/ruby-2.1.4/bin/fpm:23:in `load'
	from /home/jenkins/.rvm/gems/ruby-2.1.4/bin/fpm:23:in `<main>'
	from /home/jenkins/.rvm/gems/ruby-2.1.4/bin/ruby_executable_hooks:15:in `eval'
	from /home/jenkins/.rvm/gems/ruby-2.1.4/bin/ruby_executable_hooks:15:in `<main>'
[jenkins@bl-02-rg-2nuyntivo4uh-1-tx4hkhm66czh-srv-x5gnhr6zuc7l frontend]$ hostname
bl-02-rg-2nuyntivo4uh-1-tx4hkhm66czh-srv-x5gnhr6zuc7l.abcdef.com

This is an openstack instance, so the hostnames are programmatically assigned.

If I remove the domain name from the hostname, it works fine.  Perhaps altering fpm to get just the short hostname would be sufficient -- particularly as the full domain never shows up in RPM's Packager field?

I also tried setting the maintainer flag, but fpm still blows up.  It would appear that full hostname is read in by fpm even when maintainer is being overridden.
Perhaps detect if the --maintainer field is set, and if it is, skip auto-detection of the FQDN?

My OS swears it supports 64-character hostnames:  [root@bl-02-rg-2nuyntivo4uh-1-tx4hkhm66czh-srv-x5gnhr6zuc7l frontend]# getconf HOST_NAME_MAX
64

CentOS release 6.6 (Final)

**Comment by andersje** [comment]
This is, in actuality, a bug in ruby 2.1.4.

Ruby 2.2.3 fixes this, and allows fpm to build RPMs with any length of hostname.
