### ISSUE TITLE
fpm issues error when using --exclude-file

### ISSUE THREAD

**Issue by jtrammel** [jordansissel/fpm#1021]
Hi,

First, thanks for creating fpm and making it compatible with Macs at all.

When I create an RPM from a directory tree, and I want to exclude some dirs, fpm spits out an error when using the --exclude-file parameter.

Steps to reproduce:

Create the source tree:

/bin/rm -rf /tmp/foo
mkdir -p /tmp/foo/bar
mkdir -p /tmp/foo/boo
touch /tmp/foo/bar/baz
touch /tmp/foo/boo/fubu

Create the exclude-file:

echo "/tmp/foo/boo" > /tmp/exclude.txt

Create the RPM using fpm:

fpm \
-t rpm \
--vendor Foo \
--category "System Environment/Shells" \
--license LGPL \
--name foo \
--version 1.0.0 \
--iteration 0 \
--epoch 0 \
--architecture noarch \
--rpm-os linux \
-s dir \
--directories /tmp/foo \
--package /tmp \
--exclude-file /tmp/exclude.txt \
/tmp/foo

You should get the following error:

.../lib/ruby2.0/gems/2.0.0/gems/fpm-1.4.0/lib/fpm/command.rb:367:in `execute': undefined local variable or method `exclude' for #<FPM::Command:0x007ff76ccb2030> (NameError)
	from /opt/macportsdev/lib/ruby2.0/gems/2.0.0/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'
	from /opt/macportsdev/lib/ruby2.0/gems/2.0.0/gems/fpm-1.4.0/lib/fpm/command.rb:535:in `run'
	from /opt/macportsdev/lib/ruby2.0/gems/2.0.0/gems/clamp-0.6.5/lib/clamp/command.rb:132:in `run'
	from /opt/macportsdev/lib/ruby2.0/gems/2.0.0/gems/fpm-1.4.0/bin/fpm:8:in `<top (required)>'
	from /opt/macportsdev/bin/fpm:23:in `load'
	from /opt/macportsdev/bin/fpm:23:in `<main>'

Thanks.

**Comment by iurii-polishchuk** [comment]
I've got the same error when using --exclude-file option.

**Comment by jbalonso** [comment]
For the record: this appears to have been resolved in PR #982, but it looks like we're still waiting for a release containing it (see PR #1057).

**Comment by pschichtel** [comment]
I just found this issue randomly. It's long fixed, isn't it?
