### ISSUE TITLE
BUG: logger.rb:12:in `included': undefined method `options'

### ISSUE THREAD

**Issue by aholbreich** [jordansissel/fpm#1058]
I've installed fpm by
```
 yum install ruby-devel gcc
 gem install fpm
```
No prolems where poerted...
But calling fresh installed fpm i get 
```
/usr/lib/ruby/gems/1.8/gems/cabin-0.8.0/lib/cabin/mixins/logger.rb:12:in `included': undefined method `options' for #<Cabin::Subscriber:0x7f58ef8fb318> (NoMethodError)
	from /usr/lib/ruby/gems/1.8/gems/cabin-0.8.0/lib/cabin/channel.rb:105:in `call'
	from /usr/lib/ruby/gems/1.8/gems/cabin-0.8.0/lib/cabin/channel.rb:105:in `allow_event?'
	from /usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `all?'
	from /usr/lib/ruby/gems/1.8/gems/cabin-0.8.0/lib/cabin/channel.rb:105:in `each'
	from /usr/lib/ruby/gems/1.8/gems/cabin-0.8.0/lib/cabin/channel.rb:105:in `all?'
	from /usr/lib/ruby/gems/1.8/gems/cabin-0.8.0/lib/cabin/channel.rb:105:in `allow_event?'
	from /usr/lib/ruby/gems/1.8/gems/cabin-0.8.0/lib/cabin/channel.rb:195:in `publish'
	from /usr/lib/ruby/gems/1.8/gems/cabin-0.8.0/lib/cabin/channel.rb:193:in `each'
	from /usr/lib/ruby/gems/1.8/gems/cabin-0.8.0/lib/cabin/channel.rb:193:in `publish'
	from /usr/lib/ruby/gems/1.8/gems/cabin-0.8.0/lib/cabin/channel.rb:192:in `synchronize'
	from /usr/lib/ruby/gems/1.8/gems/cabin-0.8.0/lib/cabin/channel.rb:192:in `publish'
	from /usr/lib/ruby/gems/1.8/gems/cabin-0.8.0/lib/cabin/mixins/logger.rb:113:in `_log'
	from /usr/lib/ruby/gems/1.8/gems/cabin-0.8.0/lib/cabin/mixins/logger.rb:90:in `log_with_level'
	from /usr/lib/ruby/gems/1.8/gems/cabin-0.8.0/lib/cabin/mixins/logger.rb:75:in `warn'
	from /usr/lib/ruby/gems/1.8/gems/fpm-1.4.0/lib/fpm/package/rpm.rb:530:in `epoch'
	from /usr/lib/ruby/gems/1.8/gems/fpm-1.4.0/lib/fpm/package.rb:343:in `to_s'
	from /usr/lib/ruby/gems/1.8/gems/fpm-1.4.0/lib/fpm/package/rpm.rb:540:in `to_s'
	from /usr/lib/ruby/gems/1.8/gems/fpm-1.4.0/lib/fpm/command.rb:469:in `execute'
	from /usr/lib/ruby/gems/1.8/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'
	from /usr/lib/ruby/gems/1.8/gems/fpm-1.4.0/lib/fpm/command.rb:535:in `run'
	from /usr/lib/ruby/gems/1.8/gems/clamp-0.6.5/lib/clamp/command.rb:132:in `run'
	from /usr/lib/ruby/gems/1.8/gems/fpm-1.4.0/bin/fpm:8
	from /usr/bin/fpm:19:in `load'
	from /usr/bin/fpm:19
```

The error appers indepently of params i've provide...

**Comment by aholbreich** [comment]
```
ruby --version
ruby 1.8.7 (2013-06-27 patchlevel 374) [x86_64-linux]
```

**Comment by aholbreich** [comment]
I found that workout presented here: https://github.com/jordansissel/fpm/issues/1051 works for me. So maybe this is dupplication of known prolem.
