### ISSUE TITLE
No such file or directory @ rb_sysopen - /var/lib/jenkins/jobs/deploy_api_v2/workspace/temporary

### ISSUE THREAD

**Issue by johnhamelink** [jordansissel/fpm#1064]
Hey there,

I'm struggling with FPM crashing when running the build on my Jenkins server:

```bash
  echo " -> Running FPM"                                                     
  fpm -s dir -t deb \                                                        
    --depends=libphonenumber \                                               
    --depends=libre2-1 \                                                     
    --depends=nginx \                                                        
    --deb-upstart=${UPSTART_SCRIPT} \                                        
    --deb-user=deploy \                                                      
    --deb-group=deploy \                                                     
    --deb-use-file-permissions \                                             
    --before-install release/deb/before-install.sh \                         
    --after-install release/deb/after-install.sh \                           
    --maintainer='John Hamelink <john@johnhamelink.com>' \                    
    --description='Lorem Ipsum' \                
    --url="https://example.com" \                                        
    --name=api \                                            
    --version="${VERSION}" \                                                 
    rel/api=/opt/api
```

```
 -> Running FPM
{:timestamp=>"2016-01-30T10:42:57.695024+0000", :message=>"Debian packaging tools generally labels all files in /etc as config files, as mandated by policy, so fpm defaults to this behavior for deb packages. You can disable this default behavior with --deb-no-default-config-files flag", :level=>:warn}
/usr/lib/ruby/2.3.0/fileutils.rb:1392:in `initialize': No such file or directory @ rb_sysopen - /var/lib/jenkins/jobs/deploy_api_v2/workspace/temporary (Errno::ENOENT)
	from /usr/lib/ruby/2.3.0/fileutils.rb:1392:in `open'
	from /usr/lib/ruby/2.3.0/fileutils.rb:1392:in `copy_file'
	from /usr/lib/ruby/2.3.0/fileutils.rb:486:in `copy_file'
	from /usr/lib/ruby/2.3.0/fileutils.rb:403:in `block in cp'
	from /usr/lib/ruby/2.3.0/fileutils.rb:1571:in `block in fu_each_src_dest'
	from /usr/lib/ruby/2.3.0/fileutils.rb:1587:in `fu_each_src_dest0'
	from /usr/lib/ruby/2.3.0/fileutils.rb:1569:in `fu_each_src_dest'
	from /usr/lib/ruby/2.3.0/fileutils.rb:402:in `cp'
	from /var/lib/gems/2.3.0/gems/fpm-1.4.0/lib/fpm/package/deb.rb:446:in `block in output'
	from /var/lib/gems/2.3.0/gems/fpm-1.4.0/lib/fpm/package/deb.rb:442:in `each'
	from /var/lib/gems/2.3.0/gems/fpm-1.4.0/lib/fpm/package/deb.rb:442:in `output'
	from /var/lib/gems/2.3.0/gems/fpm-1.4.0/lib/fpm/command.rb:475:in `execute'
	from /var/lib/gems/2.3.0/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'
	from /var/lib/gems/2.3.0/gems/fpm-1.4.0/lib/fpm/command.rb:535:in `run'
	from /var/lib/gems/2.3.0/gems/clamp-0.6.5/lib/clamp/command.rb:132:in `run'
	from /var/lib/gems/2.3.0/gems/fpm-1.4.0/bin/fpm:8:in `<top (required)>'
	from /usr/local/bin/fpm:23:in `load'
	from /usr/local/bin/fpm:23:in `<main>'
```

**Comment by hatt** [comment]
The best I can see from this and the code is that for whatever reason, FPM can't open the staging path (probably). Do you have a weird `/tmp` setup or something? Maybe run the above command with `--verbose --debug` or something and see if we can get some more info.

**Comment by johnhamelink** [comment]
@hatt it turned out the server had ran out of disk space
