### ISSUE TITLE
Can not get fpm to run.

### ISSUE THREAD

**Issue by DougRoyer** [jordansissel/fpm#1118]
I tried the example from the Wiki:

> fpm  fpm -s dir -t rpm -n "slashbin" -v 1.0 /bin            9:36:01
Loading flags from rc file /home/doug/.fpm {:level=>:warn}
/var/lib/gems/2.1.0/gems/fpm-1.5.0/lib/fpm/command.rb:530:in `read': Is a directory @ io_fread - /home/doug/.fpm (Errno::EISDIR)
        from /var/lib/gems/2.1.0/gems/fpm-1.5.0/lib/fpm/command.rb:530:in `block in run'
        from /var/lib/gems/2.1.0/gems/fpm-1.5.0/lib/fpm/command.rb:527:in `each'
        from /var/lib/gems/2.1.0/gems/fpm-1.5.0/lib/fpm/command.rb:527:in `run'
        from /var/lib/gems/2.1.0/gems/clamp-0.6.5/lib/clamp/command.rb:132:in `run'
        from /var/lib/gems/2.1.0/gems/fpm-1.5.0/bin/fpm:8:in `<top (required)>'
        from /usr/local/bin/fpm:23:in `load'
        from /usr/local/bin/fpm:23:in `<main>'

**Comment by DougRoyer** [comment]
> uname -a                                                    9:40:17
Linux kernel 4.2.0-35-generic #40-Ubuntu SMP Tue Mar 15 19:53:28 UTC 2016 i686 i686 i686 GNU/Linux

**Comment by jordansissel** [comment]
Hmm. Looks like fpm is looking for a local configuration file /home/doug/.fpm but that path is a directory. 

Did you intend to have ~/.fpm be a directory?

**Comment by DougRoyer** [comment]
I installed it, then ran it. I assumed fpm created ~/.fpm, I did not.

The contents of ~/.fpm is a file called fpm, that contains:

<?xml version="1.0" ?><FPM display_version="0.53" full_version="00.53.00" generator="kedpm" 
min_version="00.50.00"><KeyInfo salt="grnxxzlw" vstring="gogiffdbdgecjigc"/><PasswordList/><
/FPM>

**Comment by DougRoyer** [comment]
The file was created Oct 13 2012, seems some other tool uses ~/.fpm !
