### ISSUE TITLE
fpm doesn't work after install ruby C headers

### ISSUE THREAD

**Issue by picrin** [jordansissel/fpm#1128]
Ruby C headers are installed as shown below:

```
[picrin@jordan deployment]$ sudo dnf install ruby-devel gcc make
Last metadata expiration check: 0:33:27 ago on Wed Jun  1 22:12:03 2016.
Package ruby-devel-2.2.5-48.fc23.x86_64 is already installed, skipping.
Package gcc-5.3.1-6.fc23.x86_64 is already installed, skipping.
Package make-1:4.0-5.1.fc23.x86_64 is already installed, skipping.
Dependencies resolved.
Nothing to do.
Complete!
```

Nonetheless fpm will not be installed properly.

```
[picrin@jordan deployment]$ sudo gem install fpm
Building native extensions.  This could take a while...
ERROR:  Error installing fpm:
	ERROR: Failed to build gem native extension.

    /usr/bin/ruby -r ./siteconf20160601-9553-1q22zxq.rb extconf.rb
checking for ffi.h... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib64
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/usr/bin/$(RUBY_BASE_NAME)
	--with-ffi_c-dir
	--without-ffi_c-dir
	--with-ffi_c-include
	--without-ffi_c-include=${ffi_c-dir}/include
	--with-ffi_c-lib
	--without-ffi_c-lib=${ffi_c-dir}/lib64
	--with-libffi-config
	--without-libffi-config
	--with-pkg-config
	--without-pkg-config
/usr/share/ruby/mkmf.rb:456:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
	from /usr/share/ruby/mkmf.rb:587:in `try_cpp'
	from /usr/share/ruby/mkmf.rb:1060:in `block in have_header'
	from /usr/share/ruby/mkmf.rb:911:in `block in checking_for'
	from /usr/share/ruby/mkmf.rb:351:in `block (2 levels) in postpone'
	from /usr/share/ruby/mkmf.rb:321:in `open'
	from /usr/share/ruby/mkmf.rb:351:in `block in postpone'
	from /usr/share/ruby/mkmf.rb:321:in `open'
	from /usr/share/ruby/mkmf.rb:347:in `postpone'
	from /usr/share/ruby/mkmf.rb:910:in `checking_for'
	from /usr/share/ruby/mkmf.rb:1059:in `have_header'
	from extconf.rb:16:in `<main>'

extconf failed, exit code 1

Gem files will remain installed in /usr/local/share/gems/gems/ffi-1.9.10 for inspection.
Results logged to /usr/local/lib64/gems/ruby/ffi-1.9.10/gem_make.out
```

I'm on fedora 23 as shown below:

```
[picrin@jordan deployment]$ uname -a
Linux jordan 4.4.9-300.fc23.x86_64 #1 SMP Wed May 4 23:56:27 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
[picrin@jordan deployment]$ ^C
[picrin@jordan deployment]$ dnf --version
1.1.9
  Installed: dnf-0:1.1.9-2.fc23.noarch at 2016-05-31 11:49
  Built    : Fedora Project at 2016-05-24 15:43

  Installed: rpm-0:4.13.0-0.rc1.13.fc23.x86_64 at 2016-05-11 20:56
  Built    : Fedora Project at 2016-04-25 13:50
```

**Comment by picrin** [comment]
As suggested in #1127 packaging all dependencies of fpm into an rpm and putting it on rpmfusion would be a very good idea.
