### ISSUE TITLE
"uninitialized constant" error with fpm 1.6

### ISSUE THREAD

**Issue by 7AC** [jordansissel/fpm#1148]
I get this error with `fpm 1.6.2`, works fine with `1.5.0`.

```
# fpm -s python -t rpm protobuf
/home/gvalente/.gem/ruby/1.9.1/gems/fpm-1.6.2/lib/fpm/util/tar_writer.rb:9:in `has_issue_1608?': uninitialized constant FPM::Issues::TarWriter::StringIO (NameError)
        from /home/gvalente/.gem/ruby/1.9.1/gems/fpm-1.6.2/lib/fpm/util/tar_writer.rb:18:in `has_issues_with_split_name?'
        from /home/gvalente/.gem/ruby/1.9.1/gems/fpm-1.6.2/lib/fpm/util/tar_writer.rb:32:in `<class:TarWriter>'
        from /home/gvalente/.gem/ruby/1.9.1/gems/fpm-1.6.2/lib/fpm/util/tar_writer.rb:31:in `<top (required)>'
        from /usr/share/rubygems/rubygems/custom_require.rb:36:in `require'
        from /usr/share/rubygems/rubygems/custom_require.rb:36:in `require'
        from /home/gvalente/.gem/ruby/1.9.1/gems/fpm-1.6.2/lib/fpm/util.rb:358:in `<top (required)>'
        from /usr/share/rubygems/rubygems/custom_require.rb:36:in `require'
        from /usr/share/rubygems/rubygems/custom_require.rb:36:in `require'
        from /home/gvalente/.gem/ruby/1.9.1/gems/fpm-1.6.2/lib/fpm/package.rb:2:in `<top (required)>'
        from /usr/share/rubygems/rubygems/custom_require.rb:36:in `require'
        from /usr/share/rubygems/rubygems/custom_require.rb:36:in `require'
        from /home/gvalente/.gem/ruby/1.9.1/gems/fpm-1.6.2/lib/fpm.rb:3:in `<top (required)>'
        from /usr/share/rubygems/rubygems/custom_require.rb:36:in `require'
        from /usr/share/rubygems/rubygems/custom_require.rb:36:in `require'
        from /home/gvalente/.gem/ruby/1.9.1/gems/fpm-1.6.2/bin/fpm:5:in `<top (required)>'
        from /home/gvalente/bin/fpm:23:in `load'
        from /home/gvalente/bin/fpm:23:in `<main>'
# ruby --version
ruby 1.9.3p484 (2013-11-22 revision 43786) [i386-linux]
```

**Comment by jcm2007** [comment]
Yes,i get this error also.

**Comment by 7AC** [comment]
This workaround gets you going:

```
gem install fpm -v 1.5.0
```

**Comment by jairov4** [comment]
<1.5.x in CentOS6 creates unusable RPMs that fails with cpio: Digest mismatch  
>1.6.x in CentOS6 fails because of this.
Im blocked :(

**Comment by josegonzalez** [comment]
Seeing the same issue from our build process under a Docker container running Ubuntu 14.04. Here is the build output:

```
['fpm', '-t', 'deb', '-s', 'dir', '-C', '/tmp', '--name', 'wiki-3e6f01d287dd55087d861e1e09dc4eb8d9a55092', '--architecture', 'amd64', '--package', '/tmp/wiki-3e6f01d287dd55087d861e1e09dc4eb8d9a55092.deb', '--category', 'web', '--description', 'Package for installing wiki at commit 3e6f01d287dd55087d861e1e09dc4eb8d9a55092', '--maintainer', 'SeatGeek Operations <operations@seatgeek.com>', '--version', '1.0', '--deb-pre-depends', 'debconf', '--deb-pre-depends', 'debconf-utils', '--deb-pre-depends', 'gliderlabs-sigil', '--deb-pre-depends', 'colordiff', '--deb-pre-depends', 'python-s3cmd', '--after-install', '/app/post-install', '--deb-pre-depends', u'libicu-dev', '--deb-pre-depends', u'ruby1.9.3', '--deb-pre-depends', u'ruby-switch', '/apps', 'etc']
/var/lib/gems/1.9.1/gems/fpm-1.6.2/lib/fpm/util/tar_writer.rb:9:in `has_issue_1608?': uninitialized constant FPM::Issues::TarWriter::StringIO (NameError)
	from /var/lib/gems/1.9.1/gems/fpm-1.6.2/lib/fpm/util/tar_writer.rb:18:in `has_issues_with_split_name?'
	from /var/lib/gems/1.9.1/gems/fpm-1.6.2/lib/fpm/util/tar_writer.rb:32:in `<class:TarWriter>'
	from /var/lib/gems/1.9.1/gems/fpm-1.6.2/lib/fpm/util/tar_writer.rb:31:in `<top (required)>'
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from /var/lib/gems/1.9.1/gems/fpm-1.6.2/lib/fpm/util.rb:358:in `<top (required)>'
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from /var/lib/gems/1.9.1/gems/fpm-1.6.2/lib/fpm/package.rb:2:in `<top (required)>'
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from /var/lib/gems/1.9.1/gems/fpm-1.6.2/lib/fpm.rb:3:in `<top (required)>'
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from /var/lib/gems/1.9.1/gems/fpm-1.6.2/bin/fpm:5:in `<top (required)>'
	from /usr/local/bin/fpm:23:in `load'
	from /usr/local/bin/fpm:23:in `<main>'
/var/lib/gems/1.9.1/gems/fpm-1.6.2/lib/fpm/util/tar_writer.rb:9:in `has_issue_1608?': uninitialized constant FPM::Issues::TarWriter::StringIO (NameError)
	from /var/lib/gems/1.9.1/gems/fpm-1.6.2/lib/fpm/util/tar_writer.rb:18:in `has_issues_with_split_name?'
	from /var/lib/gems/1.9.1/gems/fpm-1.6.2/lib/fpm/util/tar_writer.rb:32:in `<class:TarWriter>'
	from /var/lib/gems/1.9.1/gems/fpm-1.6.2/lib/fpm/util/tar_writer.rb:31:in `<top (required)>'
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from /var/lib/gems/1.9.1/gems/fpm-1.6.2/lib/fpm/util.rb:358:in `<top (required)>'
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from /var/lib/gems/1.9.1/gems/fpm-1.6.2/lib/fpm/package.rb:2:in `<top (required)>'
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from /var/lib/gems/1.9.1/gems/fpm-1.6.2/lib/fpm.rb:3:in `<top (required)>'
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from /var/lib/gems/1.9.1/gems/fpm-1.6.2/bin/fpm:5:in `<top (required)>'
	from /usr/local/bin/fpm:23:in `load'
	from /usr/local/bin/fpm:23:in `<main>'
```

Going to investigate and see if I can't drum up the real issue...

**Comment by josegonzalez** [comment]
Patch made, wasn't too hard.

For those of you following along, it seems as though Ruby got confused and looked in the current namespace for `StringIO` under at least ruby 1.9.3 (what I was running under). Prefixing with a `::` made it look at the top-level namespace, which should fix the issue.

**Comment by josegonzalez** [comment]
Oi I'm a noob, you need to `require 'stringio'` to fix it :P
