### ISSUE TITLE
Creating rpm from virtualenv failing with ChildProcess::LaunchError

### ISSUE THREAD

**Issue by Amar-Chaudhari** [jordansissel/fpm#1193]
I am trying to create a rpm from virtualenv which has all the required python packages.
Eventually I am getting `ChildProcess::LaunchError`  

Any help will be much appreciated ! :)

**Command**: `fpm --verbose --debug -s virtualenv -t rpm /opt/jupyterhub`

**Output**:
```
Setting workdir {:workdir=>"/tmp", :level=>:info, :file=>"fpm/command.rb", :line=>"280", :method=>"execute"}
Setting attribute {:output_type=>"rpm", :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:input_type=>"virtualenv", :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:chdir=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:prefix=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:package=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:force?=>false, :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:name=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:log_level=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:verbose?=>true, :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:debug?=>true, :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:debug_workspace?=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:version=>1.0, :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:iteration=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:epoch=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:license=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:vendor=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:category=>"none", :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:dependencies=>[], :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:no_depends?=>false, :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:no_auto_depends?=>false, :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:provides=>[], :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:conflicts=>[], :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:replaces=>[], :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:config_files=>[], :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:directories=>[], :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:architecture=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:maintainer=>"<root@amar-test-centos7.colorado.edu>", :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:package_name_suffix=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:edit?=>false, :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:excludes=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:exclude_file=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:description=>"no description", :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:url=>"http://example.com/no-uri-given", :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:inputs=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:post_install=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:pre_install=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:post_uninstall=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:pre_uninstall=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:after_install=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:before_install=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:after_remove=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:before_remove=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:after_upgrade=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:before_upgrade=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:template_scripts?=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:template_value_list=>[], :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:workdir=>"/tmp", :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:gem_bin_path=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:gem_package_prefix=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:gem_package_name_prefix=>"rubygem", :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:gem_gem=>"gem", :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:gem_shebang=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:gem_fix_name?=>true, :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:gem_fix_dependencies?=>true, :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:gem_env_shebang?=>true, :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:gem_prerelease?=>false, :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:gem_disable_dependencies=>[], :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:gem_version_bins?=>false, :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:deb_ignore_iteration_in_dependencies?=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:deb_build_depends=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:deb_pre_depends=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:deb_compression=>"gz", :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:deb_custom_control=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:deb_config=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:deb_templates=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:deb_installed_size=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:deb_priority=>"extra", :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:deb_use_file_permissions?=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:deb_user=>"root", :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:deb_group=>"root", :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:deb_changelog=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:deb_upstream_changelog=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:deb_recommends=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:deb_suggests=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:deb_meta_file=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:deb_interest=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:deb_activate=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:deb_field=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:deb_no_default_config_files?=>false, :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:deb_auto_config_files?=>true, :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:deb_shlibs=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:deb_init_list=>[], :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:deb_default_list=>[], :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:deb_upstart_list=>[], :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:deb_systemd_list=>[], :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:deb_systemd_restart_after_upgrade?=>true, :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:npm_bin=>"npm", :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:npm_package_name_prefix=>"node", :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:npm_registry=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:rpm_use_file_permissions?=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:rpm_user=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:rpm_group=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:rpm_defattrfile=>"-", :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:rpm_defattrdir=>"-", :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:rpm_rpmbuild_define=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:rpm_dist=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:rpm_digest=>"md5", :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:rpm_compression=>"gzip", :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:rpm_os=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:rpm_changelog=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:rpm_summary=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:rpm_sign?=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:rpm_auto_add_directories?=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:auto_add_exclude_directories=>[], :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:rpm_autoreqprov?=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:rpm_autoreq?=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:rpm_autoprov?=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:attrs=>[], :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:rpm_init_list=>[], :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:rpm_filter_from_provides=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:rpm_filter_from_requires=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:rpm_tag=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:rpm_ignore_iteration_in_dependencies?=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:rpm_verbatim_gem_dependencies?=>false, :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:rpm_verifyscript=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:rpm_pretrans=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:rpm_posttrans=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:rpm_trigger_before_install=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:rpm_trigger_after_install=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:rpm_trigger_before_uninstall=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:rpm_trigger_after_target_uninstall=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:cpan_perl_bin=>"perl", :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:cpan_cpanm_bin=>"cpanm", :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:cpan_mirror=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:cpan_mirror_only?=>false, :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:cpan_package_name_prefix=>"perl", :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:cpan_test?=>true, :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:cpan_perl_lib_path=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:cpan_sandbox_non_core?=>true, :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:cpan_cpanm_force?=>false, :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:pear_package_name_prefix=>"php-pear", :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:pear_channel=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:pear_channel_update?=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:pear_bin_dir=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:pear_php_bin=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:pear_php_dir=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:pear_data_dir=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:python_bin=>"python", :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:python_easyinstall=>"easy_install", :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:python_pip=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:python_pypi=>"https://pypi.python.org/simple", :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:python_package_prefix=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:python_package_name_prefix=>"python", :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:python_fix_name?=>true, :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:python_fix_dependencies?=>true, :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:python_downcase_name?=>true, :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:python_downcase_dependencies?=>true, :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:python_install_bin=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:python_install_lib=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:python_install_data=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:python_dependencies?=>true, :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:python_obey_requirements_txt?=>false, :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:python_scripts_executable=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:python_disable_dependency=>[], :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:osxpkg_identifier_prefix=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:osxpkg_payload_free?=>false, :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:osxpkg_ownership=>"recommended", :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:osxpkg_postinstall_action=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:osxpkg_dont_obsolete=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:solaris_user=>"root", :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:solaris_group=>"root", :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:p5p_user=>"root", :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:p5p_group=>"root", :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:p5p_zonetype=>"value=global value=nonglobal", :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:p5p_publisher=>"FPM", :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:p5p_lint?=>true, :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:p5p_validate?=>true, :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:freebsd_abi=>"Linux:3:x86_64", :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:freebsd_origin=>"fpm/<name>", :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:virtualenv_pypi=>"https://pypi.python.org/simple", :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:virtualenv_package_name_prefix=>"virtualenv", :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:virtualenv_install_location=>"/usr/share/python", :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:virtualenv_fix_name?=>true, :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:virtualenv_other_files_dir=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:virtualenv_pypi_extra_index_urls=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:pleaserun_name=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:pacman_optional_depends_list=>[], :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:pacman_use_file_permissions?=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:pacman_user=>"root", :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:pacman_group=>"root", :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Setting attribute {:pacman_compression=>"xz", :level=>:debug, :file=>"fpm/command.rb", :line=>"324", :method=>"block (2 levels) in execute"}
Running command {:args=>["virtualenv", "/tmp/package-virtualenv-build-5a93716573c390bf1f952c1a6cbc672380cb66a8b9adaa1191aa948d0e12/usr/share/python/opt/jupyterhub"], :level=>:debug, :file=>"fpm/util.rb", :line=>"144", :method=>"execmd"}
Process is running {:pid=>10398, :level=>:debug, :file=>"fpm/util.rb", :line=>"162", :method=>"execmd"}
New python executable in /tmp/package-virtualenv-build-5a93716573c390bf1f952c1a6cbc672380cb66a8b9adaa1191aa948d0e12/usr/share/python/opt/jupyterhub/bin/python {:level=>:info, :file=>"cabin/mixins/pipe.rb", :line=>"47", :method=>"block in pipe"}
Installing Setuptools..............................................................................................................................................................................................................................done. {:level=>:info, :file=>"cabin/mixins/pipe.rb", :line=>"47", :method=>"block in pipe"}
Installing Pip.....................................................................................................................................................................................................................................................................................................................................done. {:level=>:info, :file=>"cabin/mixins/pipe.rb", :line=>"47", :method=>"block in pipe"}
Running command {:args=>["/tmp/package-virtualenv-build-5a93716573c390bf1f952c1a6cbc672380cb66a8b9adaa1191aa948d0e12/usr/share/python/opt/jupyterhub/bin/pip", "install", "-U", "-i", "https://pypi.python.org/simple", "pip", "distribute"], :level=>:debug, :file=>"fpm/util.rb", :line=>"144", :method=>"execmd"}
Cleaning up staging path {:path=>"/tmp/package-virtualenv-staging-56ece0e3bbae7d7ced86dec5f264299167825e67757a1ee38ad64b436b51", :level=>:debug, :file=>"fpm/package.rb", :line=>"280", :method=>"cleanup_staging"}
Cleaning up build path {:path=>"/tmp/package-virtualenv-build-5a93716573c390bf1f952c1a6cbc672380cb66a8b9adaa1191aa948d0e12", :level=>:debug, :file=>"fpm/package.rb", :line=>"287", :method=>"cleanup_build"}
/usr/local/share/gems/gems/childprocess-0.5.9/lib/childprocess/unix/fork_exec_process.rb:58:in `launch_process': No such file or directory - /tmp/package-virtualenv-build-5a93716573c390bf1f952c1a6cbc672380cb66a8b9adaa1191aa948d0e12/usr/share/python/opt/jupyterhub/bin/pip (ChildProcess::LaunchError)
	from /usr/local/share/gems/gems/childprocess-0.5.9/lib/childprocess/abstract_process.rb:82:in `start'
	from /usr/local/share/gems/gems/fpm-1.6.3/lib/fpm/util.rb:159:in `execmd'
	from /usr/local/share/gems/gems/fpm-1.6.3/lib/fpm/util.rb:195:in `safesystem'
	from /usr/local/share/gems/gems/fpm-1.6.3/lib/fpm/package/virtualenv.rb:85:in `input'
	from /usr/local/share/gems/gems/fpm-1.6.3/lib/fpm/command.rb:338:in `block in execute'
	from /usr/local/share/gems/gems/fpm-1.6.3/lib/fpm/command.rb:337:in `each'
	from /usr/local/share/gems/gems/fpm-1.6.3/lib/fpm/command.rb:337:in `execute'
	from /usr/local/share/gems/gems/clamp-1.0.0/lib/clamp/command.rb:68:in `run'
	from /usr/local/share/gems/gems/fpm-1.6.3/lib/fpm/command.rb:560:in `run'
	from /usr/local/share/gems/gems/clamp-1.0.0/lib/clamp/command.rb:133:in `run'
	from /usr/local/share/gems/gems/fpm-1.6.3/bin/fpm:8:in `<top (required)>'
	from /usr/local/bin/fpm:23:in `load'
	from /usr/local/bin/fpm:23:in `<main>'
```

**Comment by selyx** [comment]
Had exatctly the same problem. According to #1217 this might be caused by the shebang size limitation.

There is already a fix in the latest master

**Comment by jordansissel** [comment]
Hmm, @selyx good eye. This sounds about right.

I'll see if I can make the part of fpm chill out a bit with the long temporary path names.
