### ISSUE TITLE
Cannot convert local CPAN module

### ISSUE THREAD

**Issue by liger1978** [jordansissel/fpm#1202]
You get the following error when you try to convert a local CPAN module (e.g. to an RPM):

```
/usr/local/share/gems/gems/fpm-1.6.3/lib/fpm/package/cpan.rb:75:in `input': undefined method `merge' for nil:NilClass (N
oMethodError)
        from /usr/local/share/gems/gems/fpm-1.6.3/lib/fpm/command.rb:338:in `block in execute'
        from /usr/local/share/gems/gems/fpm-1.6.3/lib/fpm/command.rb:337:in `each'
        from /usr/local/share/gems/gems/fpm-1.6.3/lib/fpm/command.rb:337:in `execute'
        from /usr/local/share/gems/gems/clamp-1.0.0/lib/clamp/command.rb:68:in `run'
        from /usr/local/share/gems/gems/fpm-1.6.3/lib/fpm/command.rb:560:in `run'
        from /usr/local/share/gems/gems/clamp-1.0.0/lib/clamp/command.rb:133:in `run'
        from /usr/local/share/gems/gems/fpm-1.6.3/bin/fpm:8:in `<top (required)>'
        from /usr/local/bin/fpm:23:in `load'
        from /usr/local/bin/fpm:23:in `<main>'
```

Should be easy to fix.  I'll do it and put in a pull request.

**Comment by liger1978** [comment]
I've put in a pull request.  Please review and pull.
