### ISSUE TITLE
python virtualenv packages fail when '-' in package name

### ISSUE THREAD

**Issue by nzjrs** [jordansissel/fpm#1217]
fpm 1.6.3
ubuntu 12.04

trying to create a package from a python virtualenv source fails with the following error

```
$ fpm --verbose --debug --debug-workspace -s virtualenv -t deb requirements.txt
```

```
No name given. Using the directory's name {:name=>"test-package", :level=>:info, :file=>"fpm/package/virtualenv.rb", :line=>"52", :method=>"input"}
Running command {:args=>["virtualenv", "/tmp/package-virtualenv-build-85bda807e0c1119ba23c2f129d001d839b9d2d3e6d18e3be1b2996ec0a00/usr/share/python/test-package"], :level=>:debug, :file=>"fpm/util.rb", :line=>"144", :method=>"execmd"}
Process is running {:pid=>22472, :level=>:debug, :file=>"fpm/util.rb", :line=>"162", :method=>"execmd"}
New python executable in /tmp/package-virtualenv-build-85bda807e0c1119ba23c2f129d001d839b9d2d3e6d18e3be1b2996ec0a00/usr/share/python/test-package/bin/python {:level=>:info, :file=>"cabin/mixins/pipe.rb", :line=>"47", :method=>"block in pipe"}
Installing distribute.............................................................................................................................................................................................done. {:level=>:info, :file=>"cabin/mixins/pipe.rb", :line=>"47", :method=>"block in pipe"}
Installing pip... {:level=>:info, :file=>"cabin/mixins/pipe.rb", :line=>"47", :method=>"block in pipe"}
  Error [Errno 13] Permission denied while executing command /tmp/package-virtual...age/bin/easy_install /usr/share/python-virtualenv/pip-1.1.tar.gz {:level=>:info, :file=>"cabin/mixins/pipe.rb", :line=>"47", :method=>"block in pipe"}
...Installing pip...done. {:level=>:info, :file=>"cabin/mixins/pipe.rb", :line=>"47", :method=>"block in pipe"}
Traceback (most recent call last): {:level=>:info, :file=>"cabin/mixins/pipe.rb", :line=>"47", :method=>"block in pipe"}
  File "/usr/bin/virtualenv", line 3, in <module> {:level=>:info, :file=>"cabin/mixins/pipe.rb", :line=>"47", :method=>"block in pipe"}
    virtualenv.main() {:level=>:info, :file=>"cabin/mixins/pipe.rb", :line=>"47", :method=>"block in pipe"}
  File "/usr/lib/python2.7/dist-packages/virtualenv.py", line 938, in main {:level=>:info, :file=>"cabin/mixins/pipe.rb", :line=>"47", :method=>"block in pipe"}
    never_download=options.never_download) {:level=>:info, :file=>"cabin/mixins/pipe.rb", :line=>"47", :method=>"block in pipe"}
  File "/usr/lib/python2.7/dist-packages/virtualenv.py", line 1054, in create_environment {:level=>:info, :file=>"cabin/mixins/pipe.rb", :line=>"47", :method=>"block in pipe"}
    install_pip(py_executable, search_dirs=search_dirs, never_download=never_download) {:level=>:info, :file=>"cabin/mixins/pipe.rb", :line=>"47", :method=>"block in pipe"}
  File "/usr/lib/python2.7/dist-packages/virtualenv.py", line 643, in install_pip {:level=>:info, :file=>"cabin/mixins/pipe.rb", :line=>"47", :method=>"block in pipe"}
    filter_stdout=_filter_setup) {:level=>:info, :file=>"cabin/mixins/pipe.rb", :line=>"47", :method=>"block in pipe"}
  File "/usr/lib/python2.7/dist-packages/virtualenv.py", line 976, in call_subprocess {:level=>:info, :file=>"cabin/mixins/pipe.rb", :line=>"47", :method=>"block in pipe"}
    cwd=cwd, env=env) {:level=>:info, :file=>"cabin/mixins/pipe.rb", :line=>"47", :method=>"block in pipe"}
  File "/usr/lib/python2.7/subprocess.py", line 679, in __init__ {:level=>:info, :file=>"cabin/mixins/pipe.rb", :line=>"47", :method=>"block in pipe"}
    errread, errwrite) {:level=>:info, :file=>"cabin/mixins/pipe.rb", :line=>"47", :method=>"block in pipe"}
  File "/usr/lib/python2.7/subprocess.py", line 1249, in _execute_child {:level=>:info, :file=>"cabin/mixins/pipe.rb", :line=>"47", :method=>"block in pipe"}
    raise child_exception {:level=>:info, :file=>"cabin/mixins/pipe.rb", :line=>"47", :method=>"block in pipe"}
OSError: [Errno 13] Permission denied {:level=>:info, :file=>"cabin/mixins/pipe.rb", :line=>"47", :method=>"block in pipe"}
Process failed: virtualenv failed (exit code 1). Full command was:["virtualenv", "/tmp/package-virtualenv-build-85bda807e0c1119ba23c2f129d001d839b9d2d3e6d18e3be1b2996ec0a00/usr/share/python/test-package"] {:level=>:error, :file=>"fpm/command.rb", :line=>"491", :method=>"rescue in execute"}
plugin directory {:plugin=>"virtualenv", :pathtype=>:build_path, :path=>"/tmp/package-virtualenv-build-85bda807e0c1119ba23c2f129d001d839b9d2d3e6d18e3be1b2996ec0a00", :file=>"fpm/command.rb", :line=>"498", :method=>"each"}
```

after upgrading virtualenv, I get the following error

```
No name given. Using the directory's name {:name=>"test-package", :level=>:info, :file=>"fpm/package/virtualenv.rb", :line=>"52", :method=>"input"}
Running command {:args=>["virtualenv", "/tmp/package-virtualenv-build-71a4a6fe38d6808f739b0f69508614c7046d303512fc73a44f983443fbfe/usr/share/python/test-package"], :level=>:debug, :file=>"fpm/util.rb", :line=>"144", :method=>"execmd"}
Process is running {:pid=>24490, :level=>:debug, :file=>"fpm/util.rb", :line=>"162", :method=>"execmd"}
New python executable in /tmp/package-virtualenv-build-71a4a6fe38d6808f739b0f69508614c7046d303512fc73a44f983443fbfe/usr/share/python/test-package/bin/python {:level=>:info, :file=>"cabin/mixins/pipe.rb", :line=>"47", :method=>"block in pipe"}
Installing setuptools, pip...done. {:level=>:info, :file=>"cabin/mixins/pipe.rb", :line=>"47", :method=>"block in pipe"}
Running command {:args=>["/tmp/package-virtualenv-build-71a4a6fe38d6808f739b0f69508614c7046d303512fc73a44f983443fbfe/usr/share/python/test-package/bin/pip", "install", "-U", "-i", "https://pypi.python.org/simple", "pip", "distribute"], :level=>:debug, :file=>"fpm/util.rb", :line=>"144", :method=>"execmd"}
plugin directory {:plugin=>"virtualenv", :pathtype=>:build_path, :path=>"/tmp/package-virtualenv-build-71a4a6fe38d6808f739b0f69508614c7046d303512fc73a44f983443fbfe", :file=>"fpm/command.rb", :line=>"498", :method=>"each"}
/var/lib/gems/1.9.1/gems/childprocess-0.5.8/lib/childprocess/unix/fork_exec_process.rb:58:in `launch_process': Permission denied - /tmp/package-virtualenv-build-71a4a6fe38d6808f739b0f69508614c7046d303512fc73a44f983443fbfe/usr/share/python/test-package/bin/pip (ChildProcess::LaunchError)
    from /var/lib/gems/1.9.1/gems/childprocess-0.5.8/lib/childprocess/abstract_process.rb:82:in `start'
    from /var/lib/gems/1.9.1/gems/fpm-1.6.3/lib/fpm/util.rb:159:in `execmd'
    from /var/lib/gems/1.9.1/gems/fpm-1.6.3/lib/fpm/util.rb:195:in `safesystem'
    from /var/lib/gems/1.9.1/gems/fpm-1.6.3/lib/fpm/package/virtualenv.rb:85:in `input'
    from /var/lib/gems/1.9.1/gems/fpm-1.6.3/lib/fpm/command.rb:338:in `block in execute'
    from /var/lib/gems/1.9.1/gems/fpm-1.6.3/lib/fpm/command.rb:337:in `each'
    from /var/lib/gems/1.9.1/gems/fpm-1.6.3/lib/fpm/command.rb:337:in `execute'
    from /var/lib/gems/1.9.1/gems/clamp-1.0.1/lib/clamp/command.rb:68:in `run'
    from /var/lib/gems/1.9.1/gems/fpm-1.6.3/lib/fpm/command.rb:560:in `run'
    from /var/lib/gems/1.9.1/gems/clamp-1.0.1/lib/clamp/command.rb:133:in `run'
    from /var/lib/gems/1.9.1/gems/fpm-1.6.3/bin/fpm:8:in `<top (required)>'
    from /usr/local/bin/fpm:19:in `load'
    from /usr/local/bin/fpm:19:in `<main>'
```

**Comment by nzjrs** [comment]
the cause of this was a '-' in the package name. the generated debug workspace path that is written is not a valid interpreter path (why??)

running the failing step above manually

```
/tmp/package-virtualenv-build-71a4a6fe38d6808f739b0f69508614c7046d303512fc73a44f983443fbfe/usr/share/python/test-package/bin/pip install -U -i https://pypi.python.org/simple pip distribute
-bash: /tmp/package-virtualenv-build-71a4a6fe38d6808f739b0f69508614c7046d303512fc73a44f983443fbfe/usr/share/python/test-package/bin/pip: /tmp/package-virtualenv-build-71a4a6fe38d6808f739b0f69508614c7046d303512fc73a4: bad interpreter: Permission denied
```

the shbang in the virtualenv pip is

```/tmp/package-virtualenv-build-71a4a6fe38d6808f739b0f69508614c7046d303512fc73a44f983443fbfe/usr/share/python/test-package/bin/python```

the python path it points to can be executed manually !?, but is an invalid shbang

**Comment by hatt** [comment]
Is it possible to gist the head or first few lines of the file with any trailing non-printable characters?

**Comment by nicobrevin** [comment]
can you try with latest master and see if it still fails?

**Comment by nicobrevin** [comment]
It might be the hyphen put you over the shebang size limit. There is a fix
on master for this.

On Sun, 23 Oct 2016 23:16 John Stowers, <notifications@github.com> wrote:

the cause of this was a '-' in the package name. the generated debug
workspace path that is written is not a valid interpreter path (why??)

running the failing step above manually

/tmp/package-virtualenv-build-71a4a6fe38d6808f739b0f69508614c7046d303512fc73a44f983443fbfe/usr/share/python/test-package/bin/pip
install -U -i https://pypi.python.org/simple pip distribute
-bash: /tmp/package-virtualenv-build-71a4a6fe38d6808f739b0f69508614c7046d303512fc73a44f983443fbfe/usr/share/python/test-package/bin/pip:
/tmp/package-virtualenv-build-71a4a6fe38d6808f739b0f69508614c7046d303512fc73a4:
bad interpreter: Permission denied

the shbang in the virtualenv pip is


the python path it points to can be executed manually !?, but is an
invalid shbang

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/jordansissel/fpm/issues/1217#issuecomment-255580273>,
or mute the thread

**Comment by nzjrs** [comment]
I couldn't reproduce this on master. I think it was the shbang size limit

**Comment by jhermann** [comment]
It is the size limit, the work-around is to call these scripts with an *explicit* interpreter binary when used from the working dir with its long path.

    $ wc -c <<<'/tmp/package-virtualenv-build-71a4a6fe38d6808f739b0f69508614c7046d303512fc73a44f983443fbfe/usr/share/python/test-package/bin/python'
    132

**Comment by nzjrs** [comment]
yeah, I should have closed this as fixed ages ago. Thanks for the reminder
