### ISSUE TITLE
Install fpm in Alpine

### ISSUE THREAD

**Issue by sfwn** [jordansissel/fpm#1243]
I have a docker container based on image **ruby:2.3.2-alpine**.
When I use `gem install fpm` it always failed.
Error message when I ran `gem install fpm` below:
```
Building native extensions.  This could take a while...
ERROR:  Error installing fpm:
	ERROR: Failed to build gem native extension.

    current directory: /usr/local/bundle/gems/ffi-1.9.14/ext/ffi_c
/usr/local/bin/ruby -r ./siteconf20161129-203-1hrhf0s.rb extconf.rb
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/usr/local/bin/$(RUBY_BASE_NAME)
	--with-ffi_c-dir
	--without-ffi_c-dir
	--with-ffi_c-include
	--without-ffi_c-include=${ffi_c-dir}/include
	--with-ffi_c-lib
	--without-ffi_c-lib=${ffi_c-dir}/lib
	--with-libffi-config
	--without-libffi-config
	--with-pkg-config
	--without-pkg-config
/usr/local/lib/ruby/2.3.0/mkmf.rb:456:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
	from /usr/local/lib/ruby/2.3.0/mkmf.rb:541:in `try_link0'
	from /usr/local/lib/ruby/2.3.0/mkmf.rb:556:in `try_link'
	from /usr/local/lib/ruby/2.3.0/mkmf.rb:657:in `try_ldflags'
	from /usr/local/lib/ruby/2.3.0/mkmf.rb:1813:in `pkg_config'
	from extconf.rb:15:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /usr/local/bundle/extensions/x86_64-linux/2.3.0-static/ffi-1.9.14/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /usr/local/bundle/gems/ffi-1.9.14 for inspection.
Results logged to /usr/local/bundle/extensions/x86_64-linux/2.3.0-static/ffi-1.9.14/gem_make.out
```
And context in */usr/local/bundle/extensions/x86_64-linux/2.3.0-static/ffi-1.9.14/mkmf.log*:
```
"pkg-config --exists libffi"
| pkg-config --libs libffi
=> "-L/usr/lib/../lib -lffi  \n"
"gcc -o conftest -I/usr/local/include/ruby-2.3.0/x86_64-linux -I/usr/local/include/ruby-2.3.0/ruby/backward -I/usr/local/include/ruby-2.3.0 -I.     -O3 -fno-fast-math -ggdb3 -Wall -Wextra -Wno-unused-parameter -Wno-parentheses -Wno-long-long -Wno-missing-field-initializers -Wunused-variable -Wpointer-arith -Wwrite-strings -Wdeclaration-after-statement -Wimplicit-function-declaration -Wdeprecated-declarations -Wno-packed-bitfield-compat -Wno-maybe-uninitialized conftest.c  -L. -L/usr/local/lib -Wl,-R/usr/local/lib -L. -fstack-protector -rdynamic -Wl,-export-dynamic     -Wl,-R/usr/local/lib -L/usr/local/lib -lruby-static  -lpthread -ldl -lcrypt -lm   -lc"
In file included from /usr/local/include/ruby-2.3.0/ruby/ruby.h:36:0,
                 from /usr/local/include/ruby-2.3.0/ruby.h:33,
                 from conftest.c:1:
/usr/local/include/ruby-2.3.0/ruby/defines.h:26:19: fatal error: stdio.h: No such file or directory
 #include <stdio.h>
                   ^
compilation terminated.
checked program was:
/* begin */
1: #include "ruby.h"
2:
3: int main(int argc, char **argv)
4: {
5:   return 0;
6: }
/* end */
```

I know the main caveat to note is that it does use **musl libc** instead of **glibc** and friends, so certain software might run into issues depending on the depth of their libc requirements. 

So, what should I do? Please help.

**Comment by chemist** [comment]
https://github.com/chemist/dockers/tree/master/alpine-fpm

**Comment by sfwn** [comment]
OK, after I install a lot of packages with apk, now I can install fpm.
The last command I typed is `# apk add --no-cache build-base libffi-dev`, and I don't test yet if it is enough. I will update my answer as soon as I tested.

**Comment by sfwn** [comment]
@chemist 
thank you very much :) 
I will test it later~

**Comment by sfwn** [comment]
Tested.
Based image: **ruby:2.3.2-alpine**
Just add **build-base**  by `# apk add --no-cache build-base` and I can install fpm successfully.

@chemist 
I ran your Dockerfile and it works, nice ~

**Comment by josegonzalez** [comment]
Closing as the OP has found a way around their own issue.
