### ISSUE TITLE
can't package / dir

### ISSUE THREAD

**Issue by sfwn** [jordansissel/fpm#1244]
I happend to run fpm in my `/` dir.
The fpm command is:
```fpm
/ # fpm -s dir -t rpm -n rootdir -v 0.1-SNAPSHOT -p /20161130/02_25_54/rootdir-0.1-SNAPSHOT.rpm -C / --rpm-os linux -x "201*" --verbose
```
And the result:
```
No args, but -s dir and -C are given, assuming '.' as input {:level=>:info}
Setting workdir {:workdir=>"/tmp", :level=>:info}
/usr/local/bundle/gems/fpm-1.7.0/lib/fpm/util.rb:255:in `mknod_w': undefined method `xmknod' for #<FPM::Package::Dir:0x00564b43becbe0> (NoMethodError)
Did you mean?  mknod
	from /usr/local/bundle/gems/fpm-1.7.0/lib/fpm/util.rb:289:in `copy_entry'
	from /usr/local/bundle/gems/fpm-1.7.0/lib/fpm/package/dir.rb:210:in `rescue in copy'
	from /usr/local/bundle/gems/fpm-1.7.0/lib/fpm/package/dir.rb:204:in `copy'
	from /usr/local/bundle/gems/fpm-1.7.0/lib/fpm/package/dir.rb:162:in `block in clone'
	from /usr/local/lib/ruby/2.3.0/find.rb:49:in `block (2 levels) in find'
	from /usr/local/lib/ruby/2.3.0/find.rb:48:in `catch'
	from /usr/local/lib/ruby/2.3.0/find.rb:48:in `block in find'
	from /usr/local/lib/ruby/2.3.0/find.rb:43:in `each'
	from /usr/local/lib/ruby/2.3.0/find.rb:43:in `find'
	from /usr/local/bundle/gems/fpm-1.7.0/lib/fpm/package/dir.rb:160:in `clone'
	from /usr/local/bundle/gems/fpm-1.7.0/lib/fpm/package/dir.rb:71:in `block in input'
	from /usr/local/bundle/gems/fpm-1.7.0/lib/fpm/package/dir.rb:69:in `chdir'
	from /usr/local/bundle/gems/fpm-1.7.0/lib/fpm/package/dir.rb:69:in `input'
	from /usr/local/bundle/gems/fpm-1.7.0/lib/fpm/command.rb:338:in `block in execute'
	from /usr/local/bundle/gems/fpm-1.7.0/lib/fpm/command.rb:337:in `each'
	from /usr/local/bundle/gems/fpm-1.7.0/lib/fpm/command.rb:337:in `execute'
	from /usr/local/bundle/gems/clamp-1.0.1/lib/clamp/command.rb:68:in `run'
	from /usr/local/bundle/gems/fpm-1.7.0/lib/fpm/command.rb:560:in `run'
	from /usr/local/bundle/gems/clamp-1.0.1/lib/clamp/command.rb:133:in `run'
	from /usr/local/bundle/gems/fpm-1.7.0/bin/fpm:8:in `<top (required)>'
	from /usr/local/bundle/bin/fpm:22:in `load'
	from /usr/local/bundle/bin/fpm:22:in `<main>'
```

**Comment by josegonzalez** [comment]
What operating system was FPM run on?

**Comment by sfwn** [comment]
@josegonzalez 
both alpine and centos with the same error.
I also tested on osx, but the error is different.

**Comment by jordansissel** [comment]
This error message is really not informative, sorry about that.

Looking at the code, it looks like fpm tries to provide a way to invoke `mknod` and if that fails it tries glibc's `__xmknod` (reference: https://github.com/jordansissel/fpm/blob/master/lib/fpm/util.rb#L10-L17). Later, it will call this if it needs to, and calls xmknod on Linux and mknod elsewhere (https://github.com/jordansissel/fpm/blob/master/lib/fpm/util.rb#L252-L258).

I confess I'm not exactly sure why this code needs to do these checks to call mknod/xmknod. History is commit 7c67bd90 and #539.

I'll try to reproduce this.

**Comment by jordansissel** [comment]
@sfwn what provides your libc?

**Comment by jordansissel** [comment]
I tried to reproduce on the `alpine` docker image, but after spending 10 minutes chasing dependencies, I gave up for lack of finding `rpmbuild` with `apk.

**Comment by jordansissel** [comment]
I tried this on alpine docker:

```
% mkfifo /tmp/a
% fpm -s dir -t dir -n example /tmp/a
```

This worked with no changes on the latest fpm release.

**Comment by jordansissel** [comment]
On alpine, this also works: 

```
fpm -s dir -t deb -n example /tmp/a
```

(with /tmp/a being a pipe)

**Comment by jordansissel** [comment]
Ahh:

```
bash-4.3# fpm -s dir -t deb -n example /dev/tty 
/usr/lib/ruby/gems/2.3.0/gems/fpm-1.7.0/lib/fpm/util.rb:255:in `mknod_w': undefined method `xmknod' for #<FPM::Package::Dir:0x0055cddfeeebe0> (NoMethodError)
Did you mean?  mknod
```

**Comment by jordansissel** [comment]
Testing #1245 on alpine:

* as root:

```
bash-4.3# bin/fpm -s dir -t dir -n example /dev/tty
Created package {:path=>"example.dir"}
```

* As non-root (should fail and does fail)

```
$ bin/fpm -s dir -t dir -n example /dev/tty
/fpm/lib/fpm/util.rb:289:in `copy_entry': Operation not permitted - mknod error while trying to copy /dev/tty to /tmp/package-dir-staging-3851cff49ab376cf26b052d9e8825713ba6a6934ff261caedcc0ce34891e/dev/tty (Errno::EPERM)
```

**Comment by sfwn** [comment]
@josegonzalez 
Thank you for replying me.
The main caveat to note is that alpine does use `musl libc` instead of `glibc` and friends, so certain software might run into issues depending on the depth of their libc requirements.

And, the command below also works for me:
```
# fpm -s dir -t dir -n example /tmp/a
```
But, when I use 
```
# fpm -s dir -t dir -n example /
```
it failed.

**Comment by jordansissel** [comment]
I hope this is solved now, but do let me know if this problem still occurs, and we can reopen! :)

The affected code (calling xmknod, etc) was removed in #1796 and replaced with similar functionality.
