### ISSUE TITLE
"invalid byte sequence" errors when converting gems to debs on ubuntu trusty & xenial

### ISSUE THREAD

**Issue by memory** [jordansissel/fpm#1267]
Stumbled across this while attempting to use fpm to build debs of itself and its gem dependencies as in the following Dockerfile:

```
FROM ubuntu:trusty

RUN apt-get update
RUN apt-get install -yy build-essential ruby-dev
RUN mkdir -p /tmp/gems
RUN gem install --no-ri --no-rdoc --install-dir /tmp/gems fpm -v 1.8.0
RUN gem install --no-ri --no-rdoc --local --force /tmp/gems/cache/*.gem
RUN cd /tmp/gems/cache; find . -name \*.gem | while read i; do echo "*** converting $i"; /usr/local/bin/fpm --deb-no-default-config-files -d ruby --prefix `gem environment gemdir` -s gem -t deb $i; done
```

Conversion of the backports and ruby-xz gems fails with an "invalid byte sequence" error:

```
$ docker build -t failboat -f Dockerfile.fpm  .
  [...much log output elided...]

*** converting ./backports-3.6.8.gem
ERROR:  While executing gem ... (ArgumentError)
    invalid byte sequence in US-ASCII
/var/lib/gems/1.9.1/gems/fpm-1.8.0/lib/fpm/package/gem.rb:108:in `load_package_info': undefined method `name' for false:FalseClass (NoMethodError)
	from /var/lib/gems/1.9.1/gems/fpm-1.8.0/lib/fpm/package/gem.rb:58:in `input'
	from /var/lib/gems/1.9.1/gems/fpm-1.8.0/lib/fpm/command.rb:338:in `block in execute'
	from /var/lib/gems/1.9.1/gems/fpm-1.8.0/lib/fpm/command.rb:337:in `each'
	from /var/lib/gems/1.9.1/gems/fpm-1.8.0/lib/fpm/command.rb:337:in `execute'
	from /var/lib/gems/1.9.1/gems/clamp-1.0.1/lib/clamp/command.rb:68:in `run'
	from /var/lib/gems/1.9.1/gems/fpm-1.8.0/lib/fpm/command.rb:560:in `run'
	from /var/lib/gems/1.9.1/gems/clamp-1.0.1/lib/clamp/command.rb:133:in `run'
	from /var/lib/gems/1.9.1/gems/fpm-1.8.0/bin/fpm:8:in `<top (required)>'
	from /usr/local/bin/fpm:23:in `load'
	from /usr/local/bin/fpm:23:in `<main>'
*** converting ./ruby-xz-0.2.3.gem
ERROR:  While executing gem ... (ArgumentError)
    invalid byte sequence in US-ASCII
/var/lib/gems/1.9.1/gems/fpm-1.8.0/lib/fpm/package/gem.rb:108:in `load_package_info': undefined method `name' for false:FalseClass (NoMethodError)
	from /var/lib/gems/1.9.1/gems/fpm-1.8.0/lib/fpm/package/gem.rb:58:in `input'
	from /var/lib/gems/1.9.1/gems/fpm-1.8.0/lib/fpm/command.rb:338:in `block in execute'
	from /var/lib/gems/1.9.1/gems/fpm-1.8.0/lib/fpm/command.rb:337:in `each'
	from /var/lib/gems/1.9.1/gems/fpm-1.8.0/lib/fpm/command.rb:337:in `execute'
	from /var/lib/gems/1.9.1/gems/clamp-1.0.1/lib/clamp/command.rb:68:in `run'
	from /var/lib/gems/1.9.1/gems/fpm-1.8.0/lib/fpm/command.rb:560:in `run'
	from /var/lib/gems/1.9.1/gems/clamp-1.0.1/lib/clamp/command.rb:133:in `run'
	from /var/lib/gems/1.9.1/gems/fpm-1.8.0/bin/fpm:8:in `<top (required)>'
	from /usr/local/bin/fpm:23:in `load'
	from /usr/local/bin/fpm:23:in `<main>'
```

**Comment by memory** [comment]
...thoughts?

**Comment by memory** [comment]
Possibly a duplicate of https://github.com/jordansissel/fpm/issues/781

**Comment by memory** [comment]
Yup, duplicate of #781.  In an ideal universe fpm might want to warn about missing utf8 locales.

For the elucidation of anyone finding this in the future:

```
sudo apt-get install -y language-pack-en-base
sudo update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8 
export LANG=en_US.UTF-8
```
