### ISSUE TITLE
CPAN: No implicit conversion of Float into String

### ISSUE THREAD

**Issue by liger1978** [jordansissel/fpm#1343]
Converting, e.g. `Beanstalk::Client`:
```
/usr/local/share/gems/bundler/gems/fpm-32d526fb14cf/lib/fpm/package/cpan.rb:102:in `+': no implicit conversion of Float into String (TypeError)
	from /usr/local/share/gems/bundler/gems/fpm-32d526fb14cf/lib/fpm/package/cpan.rb:102:in `block in input'
	from /usr/local/share/gems/bundler/gems/fpm-32d526fb14cf/lib/fpm/package/cpan.rb:101:in `each'
	from /usr/local/share/gems/bundler/gems/fpm-32d526fb14cf/lib/fpm/package/cpan.rb:101:in `input'
```

Will submit fix.

**Comment by rjbell4** [comment]
Confirmed that your fix also allows me to build Beanstalk::Client here.  Thanks.
