### ISSUE TITLE
apk "Invalid tar stream" error

### ISSUE THREAD

**Issue by thefosk** [jordansissel/fpm#1375]
I am seeing the following error when building an Alpine `apk` package from a `dir` source:

```
/usr/lib/ruby/gems/2.4.0/gems/fpm-1.8.1/lib/fpm/package/apk.rb:195:in `block (2 levels) in cut_tar_record': Invalid tar stream, eof before end-of-tar record (StandardError)
from /usr/lib/ruby/gems/2.4.0/gems/fpm-1.8.1/lib/fpm/package/apk.rb:182:in `open'
from /usr/lib/ruby/gems/2.4.0/gems/fpm-1.8.1/lib/fpm/package/apk.rb:182:in `block in cut_tar_record'
from /usr/lib/ruby/gems/2.4.0/gems/fpm-1.8.1/lib/fpm/package/apk.rb:179:in `open'
from /usr/lib/ruby/gems/2.4.0/gems/fpm-1.8.1/lib/fpm/package/apk.rb:179:in `cut_tar_record'
from /usr/lib/ruby/gems/2.4.0/gems/fpm-1.8.1/lib/fpm/package/apk.rb:107:in `output'
from /usr/lib/ruby/gems/2.4.0/gems/fpm-1.8.1/lib/fpm/command.rb:473:in `execute'
from /usr/lib/ruby/gems/2.4.0/gems/clamp-1.0.1/lib/clamp/command.rb:68:in `run'
from /usr/lib/ruby/gems/2.4.0/gems/fpm-1.8.1/lib/fpm/command.rb:560:in `run'
from /usr/lib/ruby/gems/2.4.0/gems/clamp-1.0.1/lib/clamp/command.rb:133:in `run'
from /usr/lib/ruby/gems/2.4.0/gems/fpm-1.8.1/bin/fpm:8:in `<top (required)>'
from /usr/bin/fpm:22:in `load'
from /usr/bin/fpm:22:in `<main>'
```

**Comment by thefosk** [comment]
Also pinging @Knetic who built the apk integration.

**Comment by Knetic** [comment]
That's strange, that error should only happen as a result of the system `tar` executable producing a bad archive. I just did some quick sanity checks locally from `master` branch and didn't see anything amiss right offhand - do you have an example of a repo that runs into this, and what OS (or `tar` package) is being used to package it?

**Comment by thefosk** [comment]
I am running `fpm` on Alpine itself:

```
bash-4.3# uname -a
Linux 59ad20ebb91b 4.4.66-boot2docker #1 SMP Fri May 5 20:44:25 UTC 2017 x86_64 Linux
bash-4.3# tar --version
tar (busybox) 1.26.2
```

**Comment by thefosk** [comment]
It seems like the default `tar` that comes with Alpine doesn't work, and manually installing it with `apk add tar` fixes the problem.
