### ISSUE TITLE
config-files behaving strangely in 1.9.1

### ISSUE THREAD

**Issue by jordansissel** [jordansissel/fpm#1390]
A lesson: Passing tests doesn't mean nothing is broken ;)

Here's a scenario where fpm's --config-files setting fails now in fpm 1.9.1

```
/usr/lib/ruby/2.3.0/fileutils.rb:1387:in `copy': unknown file type: /etc/packetbeat/packetbeat.yml (RuntimeError)
	from /usr/lib/ruby/2.3.0/fileutils.rb:472:in `block in copy_entry'
	from /usr/lib/ruby/2.3.0/fileutils.rb:1498:in `wrap_traverse'
	from /usr/lib/ruby/2.3.0/fileutils.rb:469:in `copy_entry'
	from /usr/lib/ruby/2.3.0/fileutils.rb:444:in `block in cp_r'
	from /usr/lib/ruby/2.3.0/fileutils.rb:1571:in `block in fu_each_src_dest'
	from /usr/lib/ruby/2.3.0/fileutils.rb:1587:in `fu_each_src_dest0'
	from /usr/lib/ruby/2.3.0/fileutils.rb:1569:in `fu_each_src_dest'
	from /usr/lib/ruby/2.3.0/fileutils.rb:443:in `cp_r'
	from /var/lib/gems/2.3.0/gems/fpm-1.9.1/lib/fpm/package/rpm.rb:480:in `block in output'
	from /var/lib/gems/2.3.0/gems/fpm-1.9.1/lib/fpm/package/rpm.rb:476:in `each'
	from /var/lib/gems/2.3.0/gems/fpm-1.9.1/lib/fpm/package/rpm.rb:476:in `output'
	from /var/lib/gems/2.3.0/gems/fpm-1.9.1/lib/fpm/command.rb:487:in `execute'
	from /var/lib/gems/2.3.0/gems/clamp-1.0.1/lib/clamp/command.rb:68:in `run'
	from /var/lib/gems/2.3.0/gems/fpm-1.9.1/lib/fpm/command.rb:574:in `run'
	from /var/lib/gems/2.3.0/gems/clamp-1.0.1/lib/clamp/command.rb:133:in `run'
	from /var/lib/gems/2.3.0/gems/fpm-1.9.1/bin/fpm:8:in `<top (required)>'
	from /usr/local/bin/fpm:23:in `load'
	from /usr/local/bin/fpm:23:in `<main>'
```

**Comment by jordansissel** [comment]
Minimal reproduce case:

```
% bin/fpm -f -s empty -t rpm --config-files /etc/foo/bar -n example
```

**Comment by jordansissel** [comment]
Looks like 783b06fe causes this. It assume config files are always external to the package source.

**Comment by jordansissel** [comment]
fpm 1.9.2 released which hopefully fixes this.
