### ISSUE TITLE
RPM creation returning sys_fail2 and Errno::ENOMEM

### ISSUE THREAD

**Issue by monkage** [jordansissel/fpm#1396]
We use this great app to create hundreds of rpm packages a day. It has never failed!

But now we have one particular package that is failing with the error below. This is our largest package. When it previously worked, it was building from a source of 52M that created an rpm of 17M.

Error:
/usr/local/extras/lib/ruby/gems/2.2.0/gems/fpm-1.3.3/lib/fpm/package/dir.rb:183:in `link': Cannot allocate memory @ sys_fail2 - (a_path/a_file.txt, /tmp/package-dir-staging20170808-238810-zgvtby/a_file.txt) (Errno::ENOMEM)

Command:
fpm --verbose --rpm-use-file-permissions -t rpm -s dir -C /source_path -n my_name -v 1256476 --description 'blah blah blah' my_sub_dir

I haven't been able to find a report of similar messages: sys_fail2 and Errno::ENOMEM.

The fix may be:
1) Change a memory setting for fpm?
2) Upgrade from 1.3.3 to latest version?
3) Invalid characters in files or file names?
4) The package is too large?
5) Code change?

Have you seen this before? What do you suggest?

**Comment by jordansissel** [comment]
If I had to guess, ruby invoked the `link` syscall which returned ENOMEM. I don't have any particular explanation for how or why this happens. The `link(2)` manpage says this:

```
ERRORS
...
       ENOMEM Insufficient kernel memory was available.
```

But I don't know what would cause this. Is this a new error? What environment are you running fpm in (docker? limited container? tiny vm?)

**Comment by RobotGarage** [comment]
This is a new error. And it only occurs for this particular, very large package. Maybe the package finally grew beyond some size threshold.

This is a physical server: Intel Xeon E5-4620, 2.2GHz with 32 cores and 252GB

The OS is RHEL 6.9

> ulimit -Ha
address space limit (Kibytes)  (-M)  unlimited
core file size (blocks)        (-c)  unlimited
cpu time (seconds)             (-t)  unlimited
data size (Kibytes)            (-d)  unlimited
file size (blocks)             (-f)  unlimited
locks                          (-x)  unlimited
locked address space (Kibytes) (-l)  64
message queue size (Kibytes)   (-q)  800
nice                           (-e)  0
nofile                         (-n)  4096
nproc                          (-u)  1032543
pipe buffer size (bytes)       (-p)  4096
max memory size (Kibytes)      (-m)  unlimited
rtprio                         (-r)  0
socket buffer size (bytes)     (-b)  4096
sigpend                        (-i)  1032543
stack size (Kibytes)           (-s)  unlimited
swap size (Kibytes)            (-w)  not supported
threads                        (-T)  not supported
process size (Kibytes)         (-v)  unlimited

**Comment by RobotGarage** [comment]
Also, here is the rest of the error message:

        from /usr/local/extras/lib/ruby/gems/2.2.0/gems/fpm-1.3.3/lib/fpm/package/dir.rb:183:in `copy'
        from /usr/local/extras/lib/ruby/gems/2.2.0/gems/fpm-1.3.3/lib/fpm/package/dir.rb:148:in `block in clone'
        from /usr/local/extras/lib/ruby/2.2.0/find.rb:48:in `block (2 levels) in find'
        from /usr/local/extras/lib/ruby/2.2.0/find.rb:47:in `catch'
        from /usr/local/extras/lib/ruby/2.2.0/find.rb:47:in `block in find'
        from /usr/local/extras/lib/ruby/2.2.0/find.rb:42:in `each'
        from /usr/local/extras/lib/ruby/2.2.0/find.rb:42:in `find'
        from /usr/local/extras/lib/ruby/gems/2.2.0/gems/fpm-1.3.3/lib/fpm/package/dir.rb:146:in `clone'
        from /usr/local/extras/lib/ruby/gems/2.2.0/gems/fpm-1.3.3/lib/fpm/package/dir.rb:71:in `block in input'
        from /usr/local/extras/lib/ruby/gems/2.2.0/gems/fpm-1.3.3/lib/fpm/package/dir.rb:69:in `chdir'
        from /usr/local/extras/lib/ruby/gems/2.2.0/gems/fpm-1.3.3/lib/fpm/package/dir.rb:69:in `input'
        from /usr/local/extras/lib/ruby/gems/2.2.0/gems/fpm-1.3.3/lib/fpm/command.rb:332:in `block in execute'
        from /usr/local/extras/lib/ruby/gems/2.2.0/gems/fpm-1.3.3/lib/fpm/command.rb:331:in `each'
        from /usr/local/extras/lib/ruby/gems/2.2.0/gems/fpm-1.3.3/lib/fpm/command.rb:331:in `execute'
        from /usr/local/extras/lib/ruby/gems/2.2.0/gems/clamp-0.6.3/lib/clamp/command.rb:67:in `run'
        from /usr/local/extras/lib/ruby/gems/2.2.0/gems/fpm-1.3.3/lib/fpm/command.rb:510:in `run'
        from /usr/local/extras/lib/ruby/gems/2.2.0/gems/clamp-0.6.3/lib/clamp/command.rb:125:in `run'
        from /usr/local/extras/lib/ruby/gems/2.2.0/gems/fpm-1.3.3/bin/fpm:8:in `<top (required)>'
        from /usr/local/extras/bin/fpm:23:in `load'
        from /usr/local/extras/bin/fpm:23:in `<main>'

**Comment by RobotGarage** [comment]
One more note...

Sometimes this exact same package creation works. I'm not sure of the exact split of pass/fail, but I'll guess that it is about 75% pass/ 25% fail.
