### ISSUE TITLE
Inconsistent exclude behavior: --exclude doesn't work when --exclude-file does

### ISSUE THREAD

**Issue by idsvandermolen** [jordansissel/fpm#1525]
Tried with fpm 1.10.2
This does not work:
```bash
curl -OL https://github.com/prometheus/node_exporter/releases/download/v0.16.0/node_exporter-0.16.0.linux-amd64.tar.gz
fpm -f -s tar -t deb \
-n node-exporter \
-v 0.16.0 \
--iteration 1 \
--license Apache-2.0 \
--maintainer 'Platform Team <devops@catawiki.nl>' \
--chdir node_exporter-0.16.0.linux-amd64 \
--url https://github.com/prometheus/node_exporter \
--description "Prometheus node-exporter" \
--exclude NOTICE \
--exclude LICENSE \
--prefix /usr/bin \
node_exporter-0.16.0.linux-amd64.tar.gz
```
Returns exception:
```bash
/usr/local/rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/find.rb:43:in `block in find': No such file or directory - /tmp/package-tar-staging-02ee14e294396a5b9aa6854931ed3b52aa4d315f4b53abd9278690c0fce1/usr/bin (Errno::ENOENT)
	from /usr/local/rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/find.rb:43:in `collect!'
	from /usr/local/rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/find.rb:43:in `find'
	from /home/vagrant/.rvm/gems/ruby-2.4.2/gems/fpm-1.10.2/lib/fpm/package.rb:393:in `exclude'
	from /home/vagrant/.rvm/gems/ruby-2.4.2/gems/fpm-1.10.2/lib/fpm/package.rb:197:in `convert'
	from /home/vagrant/.rvm/gems/ruby-2.4.2/gems/fpm-1.10.2/lib/fpm/package/tar.rb:30:in `input'
	from /home/vagrant/.rvm/gems/ruby-2.4.2/gems/fpm-1.10.2/lib/fpm/command.rb:352:in `block in execute'
	from /home/vagrant/.rvm/gems/ruby-2.4.2/gems/fpm-1.10.2/lib/fpm/command.rb:351:in `each'
	from /home/vagrant/.rvm/gems/ruby-2.4.2/gems/fpm-1.10.2/lib/fpm/command.rb:351:in `execute'
	from /home/vagrant/.rvm/gems/ruby-2.4.2/gems/clamp-1.0.1/lib/clamp/command.rb:68:in `run'
	from /home/vagrant/.rvm/gems/ruby-2.4.2/gems/fpm-1.10.2/lib/fpm/command.rb:574:in `run'
	from /home/vagrant/.rvm/gems/ruby-2.4.2/gems/clamp-1.0.1/lib/clamp/command.rb:133:in `run'
	from /home/vagrant/.rvm/gems/ruby-2.4.2/gems/fpm-1.10.2/bin/fpm:7:in `<top (required)>'
	from /home/vagrant/.rvm/gems/ruby-2.4.2/bin/fpm:23:in `load'
	from /home/vagrant/.rvm/gems/ruby-2.4.2/bin/fpm:23:in `<main>'
```
while this does work:
```bash
curl -OL https://github.com/prometheus/node_exporter/releases/download/v0.16.0/node_exporter-0.16.0.linux-amd64.tar.gz
echo "NOTICE" > excl
echo "LICENSE" >> excl
fpm -f -s tar -t deb \
-n node-exporter \
-v 0.16.0 \
--iteration 1 \
--license Apache-2.0 \
--maintainer 'Platform Team <devops@catawiki.nl>' \
--chdir node_exporter-0.16.0.linux-amd64 \
--url https://github.com/prometheus/node_exporter \
--description "Prometheus node-exporter" \
--exclude-file ./excl \
--prefix /usr/bin \
node_exporter-0.16.0.linux-amd64.tar.gz
```

**Comment by joey-grant** [comment]
I am also experiencing this issue. @idsvandermolen, I appreciate you sharing the work-around of using the `exclude-file` option.
