### ISSUE TITLE
cpan.rb:341:in `download': undefined method `[]' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by sun-pgdx** [jordansissel/fpm#1546]
Thank you for fpm.  :)
Getting the following error.  
Please advise.
Thanks in advance!

[/tmp]{361}# fpm --log info -t rpm -s cpan IPC::Open3
Setting workdir {:workdir=>"/tmp", :level=>:info}
Asking metacpan about a module {:module=>"IPC::Open3", :level=>:info}
Downloading perl module {:distribution=>"perl", :version=>nil, :level=>:info}
Traceback (most recent call last):
	12: from /usr/local/rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:24:in `<main>'
	11: from /usr/local/rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:24:in `eval'
	10: from /usr/local/rvm/gems/ruby-2.5.1/bin/fpm:23:in `<main>'
	 9: from /usr/local/rvm/gems/ruby-2.5.1/bin/fpm:23:in `load'
	 8: from /usr/local/rvm/gems/ruby-2.5.1/gems/fpm-1.10.2/bin/fpm:7:in `<top (required)>'
	 7: from /usr/local/rvm/gems/ruby-2.5.1/gems/clamp-1.0.1/lib/clamp/command.rb:133:in `run'
	 6: from /usr/local/rvm/gems/ruby-2.5.1/gems/fpm-1.10.2/lib/fpm/command.rb:574:in `run'
	 5: from /usr/local/rvm/gems/ruby-2.5.1/gems/clamp-1.0.1/lib/clamp/command.rb:68:in `run'
	 4: from /usr/local/rvm/gems/ruby-2.5.1/gems/fpm-1.10.2/lib/fpm/command.rb:351:in `execute'
	 3: from /usr/local/rvm/gems/ruby-2.5.1/gems/fpm-1.10.2/lib/fpm/command.rb:351:in `each'
	 2: from /usr/local/rvm/gems/ruby-2.5.1/gems/fpm-1.10.2/lib/fpm/command.rb:352:in `block in execute'
	 1: from /usr/local/rvm/gems/ruby-2.5.1/gems/fpm-1.10.2/lib/fpm/package/cpan.rb:58:in `input'
/usr/local/rvm/gems/ruby-2.5.1/gems/fpm-1.10.2/lib/fpm/package/cpan.rb:341:in `download': undefined method `[]' for nil:NilClass (NoMethodError)

**Comment by jordansissel** [comment]
I can reproduce and confirm this bug. Thank you for the details!

**Comment by cmacgreg** [comment]
hey, i submitted a patch for this to make the elasticsearch query work (their index doesn't have a "v" before the version number) #1603
