### ISSUE TITLE
linking files fails when directory not writable

### ISSUE THREAD

**Issue by robnagler** [jordansissel/fpm#1549]
You should be allowed to have read-only directories. rsync and cp -a allow it. Set the directory permissions after populating the directories.

```sh
mkdir foo
touch foo/bar
chmod a-w foo
fpm -t rpm -s dir -n foo -v 1.1 foo
```

produces:

```txt
/usr/local/share/gems/gems/fpm-1.10.2/lib/fpm/package/dir.rb:201:in `link': Permission denied @ rb_file_s_link - (foo/bar, /tmp/package-dir-staging-2bb4d8233c792a506b8a0f491c8\
8594061109fd64a298cd2155205862f1b/foo/bar) (Errno::EACCES)
        from /usr/local/share/gems/gems/fpm-1.10.2/lib/fpm/package/dir.rb:201:in `copy'
        from /usr/local/share/gems/gems/fpm-1.10.2/lib/fpm/package/dir.rb:157:in `block in clone'
        from /usr/share/ruby/find.rb:49:in `block (2 levels) in find'
        from /usr/share/ruby/find.rb:48:in `catch'
        from /usr/share/ruby/find.rb:48:in `block in find'
        from /usr/share/ruby/find.rb:43:in `each'
        from /usr/share/ruby/find.rb:43:in `find'
        from /usr/local/share/gems/gems/fpm-1.10.2/lib/fpm/package/dir.rb:155:in `clone'
        from /usr/local/share/gems/gems/fpm-1.10.2/lib/fpm/package/dir.rb:71:in `block in input'
        from /usr/local/share/gems/gems/fpm-1.10.2/lib/fpm/package/dir.rb:69:in `chdir'
        from /usr/local/share/gems/gems/fpm-1.10.2/lib/fpm/package/dir.rb:69:in `input'
        from /usr/local/share/gems/gems/fpm-1.10.2/lib/fpm/command.rb:352:in `block in execute'
        from /usr/local/share/gems/gems/fpm-1.10.2/lib/fpm/command.rb:351:in `each'
        from /usr/local/share/gems/gems/fpm-1.10.2/lib/fpm/command.rb:351:in `execute'
        from /usr/local/share/gems/gems/clamp-1.0.1/lib/clamp/command.rb:68:in `run'
        from /usr/local/share/gems/gems/fpm-1.10.2/lib/fpm/command.rb:574:in `run'
        from /usr/local/share/gems/gems/clamp-1.0.1/lib/clamp/command.rb:133:in `run'
        from /usr/local/share/gems/gems/fpm-1.10.2/bin/fpm:7:in `<top (required)>'
        from /usr/local/bin/fpm:23:in `load'
        from /usr/local/bin/fpm:23:in `<main>'
```

**Comment by jordansissel** [comment]
Thank you for the details! What you describe makes sense, and I agree it is a bug. Hopefully it is easy to fix :)
