### ISSUE TITLE
fails to build apk

### ISSUE THREAD

**Issue by tcurdt** [jordansissel/fpm#1564]
I know `apk` support is quite new and docs are not up-to-date yet. I still tried to get it working:

```
$fpm \
  -p dist \
  -C builder/skel/apk \
  -f -s dir -v $(VERSION) -n $(PKGNAME) \
  --license "$(LICENSE)" \
  --vendor "$(VENDOR)" \
  --maintainer "$(MAINTAINER)" \
  --architecture $(ARCH) \
  --url "$(URL)" \
  --description  "$(DESC)" \
  --config-files etc/ \
  --verbose \
  -t apk

No args, but -s dir and -C are given, assuming '.' as input {:level=>:info}
Setting workdir {:workdir=>"/tmp", :level=>:info}
Setting from flags: architecture=amd64 {:level=>:info}
Setting from flags: description=Example {:level=>:info}
Setting from flags: epoch= {:level=>:info}
Setting from flags: iteration= {:level=>:info}
Setting from flags: license=Apache 2.0 {:level=>:info}
Setting from flags: maintainer=Torsten Curdt <tcurdt@vfer.org> {:level=>:info}
Setting from flags: name=example {:level=>:info}
Setting from flags: url=http://vafer.org {:level=>:info}
Setting from flags: vendor= {:level=>:info}
Setting from flags: version=v0.0.6 {:level=>:info}
Converting dir to apk {:level=>:info}
Traceback (most recent call last):
	12: from /usr/bin/fpm:23:in `<main>'
	11: from /usr/bin/fpm:23:in `load'
	10: from /usr/lib/ruby/gems/2.5.0/gems/fpm-1.10.2/bin/fpm:7:in `<top (required)>'
	 9: from /usr/lib/ruby/gems/2.5.0/gems/clamp-1.0.1/lib/clamp/command.rb:133:in `run'
	 8: from /usr/lib/ruby/gems/2.5.0/gems/fpm-1.10.2/lib/fpm/command.rb:574:in `run'
	 7: from /usr/lib/ruby/gems/2.5.0/gems/clamp-1.0.1/lib/clamp/command.rb:68:in `run'
	 6: from /usr/lib/ruby/gems/2.5.0/gems/fpm-1.10.2/lib/fpm/command.rb:487:in `execute'
	 5: from /usr/lib/ruby/gems/2.5.0/gems/fpm-1.10.2/lib/fpm/package/apk.rb:107:in `output'
	 4: from /usr/lib/ruby/gems/2.5.0/gems/fpm-1.10.2/lib/fpm/package/apk.rb:179:in `cut_tar_record'
	 3: from /usr/lib/ruby/gems/2.5.0/gems/fpm-1.10.2/lib/fpm/package/apk.rb:179:in `open'
	 2: from /usr/lib/ruby/gems/2.5.0/gems/fpm-1.10.2/lib/fpm/package/apk.rb:182:in `block in cut_tar_record'
	 1: from /usr/lib/ruby/gems/2.5.0/gems/fpm-1.10.2/lib/fpm/package/apk.rb:182:in `open'
/usr/lib/ruby/gems/2.5.0/gems/fpm-1.10.2/lib/fpm/package/apk.rb:195:in `block (2 levels) in cut_tar_record': Invalid tar stream, eof before end-of-tar record (StandardError)
```

I did check some of the code but don't see what could be the problem yet:

https://github.com/mdub/clamp/blob/v1.0.1/lib/clamp/command.rb#L133
https://github.com/jordansissel/fpm/blob/v1.10.2/lib/fpm/command.rb#L487

Any pointers? This is on alpine 3.8

**Comment by mzupan** [comment]
@tcurdt its an issue with tar that comes with alpine. Mac has the same issue with the tar that ships with the OS. See the following

https://github.com/jordansissel/fpm/issues/1375

**Comment by tcurdt** [comment]
Hm - that sounded promising but I am installing `tar` as suggested in #1375 

```
FROM ruby:2.5-alpine3.8

RUN apk add --update ruby-dev gcc make musl-dev libffi-dev xz-dev tar rpm && \
    gem install fpm

RUN mkdir /work
VOLUME [ "/work" ]
WORKDIR /work

ENTRYPOINT ["fpm"]
CMD ["--help"]
```

**Comment by tcurdt** [comment]
No further pointers?

**Comment by zwass** [comment]
FWIW I did get it working with https://github.com/fleetdm/docker-fpm/blob/master/Dockerfile.

**Comment by tcurdt** [comment]
In the end I contributed native `apk` support here instead https://github.com/goreleaser/nfpm

**Comment by zwass** [comment]
Wow thank you @tcurdt! npfm looks like a great fit for me since I work with Go!
