### ISSUE TITLE
tar package is needed in Dockerfile for deb generation

### ISSUE THREAD

**Issue by mgeorge** [jordansissel/fpm#1604]
The busybox version of tar (which is what Alpine uses by default) does not seem to be compatible with fpm, and causes the tar operation to error with:

```
tar: unrecognized option: owner=0
```

Simply adding 'tar' to the package list in the Dockerfile fixes this.

**Comment by gecube** [comment]
I've too been hit by this issue.
Also I'd like to ask if it is possible to switch to ubuntu or debian-slim because in alpine there is no possibility to put into the package device files. The fpm utility throws the next error (associated with musl-libc versions incompatibility #1244 ):

```/usr/lib/ruby/gems/2.4.0/gems/fpm-1.11.0/lib/fpm/util.rb:325:in `mknod_w': undefined method `xmknod' for #<FPM::Package::Dir:0x000055ace4175908> (NoMethodError)
	from /usr/lib/ruby/gems/2.4.0/gems/fpm-1.11.0/lib/fpm/util.rb:359:in `copy_entry'
	from /usr/lib/ruby/gems/2.4.0/gems/fpm-1.11.0/lib/fpm/package/dir.rb:205:in `rescue in copy'
	from /usr/lib/ruby/gems/2.4.0/gems/fpm-1.11.0/lib/fpm/package/dir.rb:199:in `copy'
	from /usr/lib/ruby/gems/2.4.0/gems/fpm-1.11.0/lib/fpm/package/dir.rb:157:in `block in clone'
	from /usr/lib/ruby/2.4.0/find.rb:49:in `block (2 levels) in find'
	from /usr/lib/ruby/2.4.0/find.rb:48:in `catch'
	from /usr/lib/ruby/2.4.0/find.rb:48:in `block in find'
	from /usr/lib/ruby/2.4.0/find.rb:43:in `each'
	from /usr/lib/ruby/2.4.0/find.rb:43:in `find'
	from /usr/lib/ruby/gems/2.4.0/gems/fpm-1.11.0/lib/fpm/package/dir.rb:155:in `clone'
	from /usr/lib/ruby/gems/2.4.0/gems/fpm-1.11.0/lib/fpm/package/dir.rb:71:in `block in input'
	from /usr/lib/ruby/gems/2.4.0/gems/fpm-1.11.0/lib/fpm/package/dir.rb:69:in `chdir'
	from /usr/lib/ruby/gems/2.4.0/gems/fpm-1.11.0/lib/fpm/package/dir.rb:69:in `input'
	from /usr/lib/ruby/gems/2.4.0/gems/fpm-1.11.0/lib/fpm/command.rb:352:in `block in execute'
	from /usr/lib/ruby/gems/2.4.0/gems/fpm-1.11.0/lib/fpm/command.rb:351:in `each'
	from /usr/lib/ruby/gems/2.4.0/gems/fpm-1.11.0/lib/fpm/command.rb:351:in `execute'
	from /usr/lib/ruby/gems/2.4.0/gems/clamp-1.0.1/lib/clamp/command.rb:68:in `run'
	from /usr/lib/ruby/gems/2.4.0/gems/fpm-1.11.0/lib/fpm/command.rb:574:in `run'
	from /usr/lib/ruby/gems/2.4.0/gems/clamp-1.0.1/lib/clamp/command.rb:133:in `run'
	from /usr/lib/ruby/gems/2.4.0/gems/fpm-1.11.0/bin/fpm:7:in `<top (required)>'
	from /usr/bin/fpm:23:in `load'
	from /usr/bin/fpm:23:in `<main>'
```
