### ISSUE TITLE
fpm errors on ruby 2.6.0 due to backports/2.0.0/stdlib/ostruct

### ISSUE THREAD

**Issue by jordansissel** [jordansissel/fpm#1663]
```
% fpm -s empty -d rpm -n example
Traceback (most recent call last):
        10: from /home/jls/.rbenv/versions/2.6.3/bin/fpm:23:in `<main>'
         9: from /home/jls/.rbenv/versions/2.6.3/bin/fpm:23:in `load'
         8: from /home/jls/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fpm-1.11.0/bin/fpm:4:in `<top (required)>'
         7: from /home/jls/.rbenv/versions/2.6.3/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
         6: from /home/jls/.rbenv/versions/2.6.3/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
         5: from /home/jls/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fpm-1.11.0/lib/fpm.rb:3:in `<top (required)>'
         4: from /home/jls/.rbenv/versions/2.6.3/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
         3: from /home/jls/.rbenv/versions/2.6.3/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
         2: from /home/jls/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fpm-1.11.0/lib/fpm/package.rb:7:in `<top (required)>'
         1: from /home/jls/.rbenv/versions/2.6.3/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/home/jls/.rbenv/versions/2.6.3/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- backports/2.0.0/stdlib/ostruct (LoadError)
```

I haven't investigated further.

**Comment by jordansissel** [comment]
```
% gem list | grep backports
backports (2.6.2)

# Fails
% fpm ...

% gem install backports
Fetching backports-3.15.0.gem
Successfully installed backports-3.15.0

```

This solves it.

**Comment by TravisEz13** [comment]
just `gem install backports` didn't work for me.  Trying `gem install barkports -v 3.15.0`
