### ISSUE TITLE
installation fails on alpine/3.11 docker image (whereas 3.7 works)

### ISSUE THREAD

**Issue by marcelser** [jordansissel/fpm#1680]
Hi,

I need to install fpm in an alpine 3.11 based docker image but even if fpm install just fine you cannot run it afterwards. Even the simplest options like "version" or no option at all make it fail with this error:

```
/ # fpm --version
Traceback (most recent call last):
        12: from /usr/bin/fpm:23:in `<main>'
        11: from /usr/bin/fpm:23:in `load'
        10: from /usr/lib/ruby/gems/2.6.0/gems/fpm-1.11.0/bin/fpm:4:in `<top (required)>'
         9: from /usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
         8: from /usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
         7: from /usr/lib/ruby/gems/2.6.0/gems/fpm-1.11.0/lib/fpm.rb:13:in `<top (required)>'
         6: from /usr/lib/ruby/gems/2.6.0/gems/backports-3.15.0/lib/backports/std_lib.rb:9:in `require_with_backports'
         5: from /usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
         4: from /usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
         3: from /usr/lib/ruby/gems/2.6.0/gems/fpm-1.11.0/lib/fpm/package/puppet.rb:5:in `<top (required)>'
         2: from /usr/lib/ruby/gems/2.6.0/gems/backports-3.15.0/lib/backports/std_lib.rb:9:in `require_with_backports'
         1: from /usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- etc (LoadError)
```

To test it more easily it just downloaded the Dockerfile provided. If I build & run it with alpine/3.7 everyrhing works fine. If I use alpine/3.11 I also have to remove the installation line because it fails with the given options. Then I installed it without these options using 'gem install fpm' and it report '1 gem installed'. But when you try to run I get the above error and backporst 3.15 was installed. And it's actually the same error as I also get on an 'docker:stable' image (which is in the end the target image) which is also based on alpine:3.11 

Is it possible to update the Dockerfile on github to support alpine/3.11?

**Comment by mattlorimor** [comment]
This obviously isn't an official fix, but making sure the `ruby-etc` package is installed by `apk`should allow you to get past `cannot load such file -- etc (LoadError)`.

**Comment by jordansissel** [comment]
Maybe the best fix here is to add installation instructions for alpine? I
think the “etc” library is part of ruby core and is not a ruby gem, so I’m
not sure if we can solve this with the gem install process for fpm.
