### ISSUE TITLE
Getting rspec working under linux (related to Dockerfiles)

### ISSUE THREAD

**Issue by directionless** [jordansissel/fpm#1682]
Hi! I wanted to make some docker containers to run fpm. But, I can't tell what system tools I need to install to get things working. I'm trying to use rspec to test stuff, but I can't really interpret the errors. 

The docker files are all visible in https://github.com/jordansissel/fpm/pull/1681

They can be run as:
```
cd docker/...
docker build -t fpm-test .
docker run -it fpm-test
```

Some initial errors:
```
  1) FPM::Command -p | --package when given a directory should write the package to the given directory.
     Failure/Error: insist { files.size } == 1
     Insist::Failure:
       Expected 1, but got 0
     # ./spec/fpm/command_spec.rb:76:in `block (5 levels) in <top (required)>'
     # ./spec/fpm/command_spec.rb:71:in `block (4 levels) in <top (required)>'

  2) FPM::Command -p | --package when not set should write the package to the current directory.
     Failure/Error: insist { files.size } == 1
     Insist::Failure:
       Expected 1, but got 0
     # ./spec/fpm/command_spec.rb:90:in `block (5 levels) in <top (required)>'
     # ./spec/fpm/command_spec.rb:84:in `block (4 levels) in <top (required)>'
```

And a slew of errors that maybe all relate to using the wrong tar?
```
  11) FPM::Package::Deb#output package attributes should fix capitalization and underscores-to-dashes (#591)
     Failure/Error: original.output(target)
     FPM::Util::ProcessFailed:
       tar failed (exit code 2). Full command was:["tar", "-C", "/tmp/package-deb-build-d4be5f9be33cc8ab5177db50e10ac92f0854cf618bfd73f2d1862565102c/control", "-z", "-cf", "/tmp/package-deb-build-d4be5f9be33cc8ab5177db50e10ac92f0854cf618bfd73f2d1862565102c/tmp/package-deb-build-d4be5f9be33cc8ab5177db50e10ac92f0854cf618bfd73f2d1862565102c/control.tar.gz", "--owner=0", "--group=0", "--numeric-owner", "."]
     # ./lib/fpm/util.rb:205:in `safesystem'
     # ./lib/fpm/package/deb.rb:816:in `block in write_control_tarball'
     # ./lib/fpm/package/deb.rb:805:in `tap'
     # ./lib/fpm/package/deb.rb:805:in `write_control_tarball'
     # ./lib/fpm/package/deb.rb:579:in `output'
     # ./spec/fpm/package/deb_spec.rb:168:in `block (3 levels) in <top (required)>'

  12) FPM::Package::Deb#output with no depends should have no dependencies
     Failure/Error: original.output(target)
     FPM::Util::ProcessFailed:
       tar failed (exit code 2). Full command was:["tar", "-C", "/tmp/package-deb-build-0267e0af6332af9b873ddb2aff0d33a791394b7327df088951a13f44d18a/control", "-z", "-cf", "/tmp/package-deb-build-0267e0af6332af9b873ddb2aff0d33a791394b7327df088951a13f44d18a/tmp/package-deb-build-0267e0af6332af9b873ddb2aff0d33a791394b7327df088951a13f44d18a/control.tar.gz", "--owner=0", "--group=0", "--numeric-owner", "."]
     # ./lib/fpm/util.rb:205:in `safesystem'
     # ./lib/fpm/package/deb.rb:816:in `block in write_control_tarball'
     # ./lib/fpm/package/deb.rb:805:in `tap'
     # ./lib/fpm/package/deb.rb:805:in `write_control_tarball'
     # ./lib/fpm/package/deb.rb:579:in `output'
     # ./spec/fpm/package/deb_spec.rb:307:in `block (3 levels) in <top (required)>'
```

**Comment by directionless** [comment]
I'd love to get the docker files and dependancies into shape, but I don't have any idea where to start with this.

**Comment by directionless** [comment]
It looks like it's been failing on travis-ci as well
