### ISSUE TITLE
Need executable 'tar' to convert dir to deb

### ISSUE THREAD

**Issue by ctrlventure** [jordansissel/fpm#1725]
I've just upgraded from Ubtunu 14 to 18 and ruby 2.6.6, and fpm 1.4.0 was giving me the following error on a codebase that was working fine until now:

```
/var/lib/gems/2.6.0/gems/fpm-1.4.0/lib/fpm/util.rb:129:in ``': No such file or directory - uname (Errno::ENOENT)
	from /var/lib/gems/2.6.0/gems/fpm-1.4.0/lib/fpm/util.rb:129:in `tar_cmd'
	from /var/lib/gems/2.6.0/gems/fpm-1.4.0/lib/fpm/package/deb.rb:600:in `block in write_control_tarball'
	from /var/lib/gems/2.6.0/gems/fpm-1.4.0/lib/fpm/util.rb:146:in `with'
	from /var/lib/gems/2.6.0/gems/fpm-1.4.0/lib/fpm/package/deb.rb:597:in `write_control_tarball'
	from /var/lib/gems/2.6.0/gems/fpm-1.4.0/lib/fpm/package/deb.rb:389:in `output'
	from /var/lib/gems/2.6.0/gems/fpm-1.4.0/lib/fpm/command.rb:475:in `execute'
	from /var/lib/gems/2.6.0/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'
	from /var/lib/gems/2.6.0/gems/fpm-1.4.0/lib/fpm/command.rb:535:in `run'
	from /var/lib/gems/2.6.0/gems/clamp-0.6.5/lib/clamp/command.rb:132:in `run'
	from /var/lib/gems/2.6.0/gems/fpm-1.4.0/bin/fpm:8:in `<top (required)>'
	from /usr/local/bin/fpm:23:in `load'
	from /usr/local/bin/fpm:23:in `<main>'
```

so i upgraded fpm to 1.11.0 and now i get this error when trying to create a deb package:

`Need executable 'tar' to convert dir to deb`

of course tar is installed on the system:

```
$ which tar
/bin/tar
``` 

i've tried every other release of fpm (1.9.3, 1.10.0, 1.10.1, 1.10.2) and its the same problem.

how can i fix this?

Full output by fpm:

```
Doing `require 'backports'` is deprecated and will not load any backport in the next major release.
Require just the needed backports instead, or 'backports/latest'.
{:timestamp=>"2020-08-27T20:04:51.541900+0200", :message=>"Setting workdir", :workdir=>"/tmp", :level=>:info}
{:timestamp=>"2020-08-27T20:04:51.724954+0200", :message=>"Setting from flags: architecture=all", :level=>:info}
{:timestamp=>"2020-08-27T20:04:51.725094+0200", :message=>"Setting from flags: epoch=", :level=>:info}
{:timestamp=>"2020-08-27T20:04:51.725145+0200", :message=>"Setting from flags: iteration=", :level=>:info}
{:timestamp=>"2020-08-27T20:04:51.725194+0200", :message=>"Setting from flags: maintainer=Julien Fabre", :level=>:info}
{:timestamp=>"2020-08-27T20:04:51.725233+0200", :message=>"Setting from flags: name=cambuilder", :level=>:info}
{:timestamp=>"2020-08-27T20:04:51.725268+0200", :message=>"Setting from flags: url=https://gssfreemium.atlassian.net/wiki/display/DEV/Jizz", :level=>:info}
{:timestamp=>"2020-08-27T20:04:51.725305+0200", :message=>"Setting from flags: vendor=Ctrl Venture s.r.o.", :level=>:info}
{:timestamp=>"2020-08-27T20:04:51.725348+0200", :message=>"Setting from flags: version=1.12.44", :level=>:info}
{:timestamp=>"2020-08-27T20:04:51.725561+0200", :message=>"Converting dir to deb", :level=>:info}
{:timestamp=>"2020-08-27T20:04:51.726893+0200", :message=>"Creating boilerplate changelog file", :level=>:info}
{:timestamp=>"2020-08-27T20:04:51.726999+0200", :message=>"Reading template", :path=>"/var/lib/gems/2.6.0/gems/fpm-1.10.2/templates/deb/changelog.erb", :level=>:info}
{:timestamp=>"2020-08-27T20:04:51.727879+0200", :message=>"No deb_installed_size set, calculating now.", :level=>:info}
{:timestamp=>"2020-08-27T20:04:51.775325+0200", :message=>"Reading template", :path=>"/var/lib/gems/2.6.0/gems/fpm-1.10.2/templates/deb.erb", :level=>:info}
{:timestamp=>"2020-08-27T20:04:51.777617+0200", :message=>"Debian packaging tools generally labels all files in /etc as config files, as mandated by policy, so fpm defaults to this behavior for deb packages. You can disable this default behavior with --deb-no-default-config-files flag", :level=>:warn}
{:timestamp=>"2020-08-27T20:04:52.363189+0200", :message=>"Creating", :path=>"/tmp/package-deb-build-d9a2d4a2bc1cf43d63642bb5910ace58f0af32bd615d4238d43906a6b98e/control.tar.gz", :from=>"/tmp/package-deb-build-d9a2d4a2bc1cf43d63642bb5910ace58f0af32bd615d4238d43906a6b98e/control", :level=>:info}
{:timestamp=>"2020-08-27T20:04:52.369442+0200", :message=>"Need executable 'tar' to convert dir to deb", :level=>:error}
```

**Comment by ctrlventure** [comment]
Turns out there was a new line char in the PATH, that's what was tricking fpm into thinking `tar` was not installed for some reason.
