### ISSUE TITLE
1.12.0 Changelog update

### ISSUE THREAD

**Issue by jacaetevha** [jordansissel/fpm#1751]
Would you mind updating the 1.12.0 changelog so that it mentions a new dependency on the Git gem? Our builds just broke because the Docker image we're running in doesn't have Git, and doesn't need it. I'm not really sure why it's even checking for Git information when I'm not doing anything with Git during the build.

When I run...

```
fpm -s dir --verbose -v 1.0.9 -n my_app --rpm-os linux -t rpm -a all \
	--rpm-user some_user --rpm-group some_group \
	--before-remove /dist/my_app-1.0.9/scripts/on-uninstall \
	--after-install /dist/my_app-1.0.9/scripts/copy-unit-file-to-destination \
	--after-upgrade /dist/my_app-1.0.9/scripts/copy-unit-file-to-destination \
	--rpm-auto-add-directories --rpm-defattrdir 775 --rpm-defattrfile 775 \
	--iteration 4 --provides my_app \
	--prefix /opt/path/to/my_app -C /dist/my_app-1.0.9 .
```

... I get the following error:

```
/usr/local/rvm/gems/ruby-2.6.6/gems/git-1.8.1/lib/git/lib.rb:1097:in `command': git '-c' 'color.ui=false' version   2>&1:sh: git: command not found (Git::GitExecuteError)
	from /usr/local/rvm/gems/ruby-2.6.6/gems/git-1.8.1/lib/git/lib.rb:990:in `current_command_version'
	from /usr/local/rvm/gems/ruby-2.6.6/gems/git-1.8.1/lib/git/lib.rb:1000:in `meets_required_version?'
	from /usr/local/rvm/gems/ruby-2.6.6/gems/git-1.8.1/lib/git.rb:28:in `<top (required)>'
	from /usr/local/rvm/rubies/ruby-2.6.6/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/local/rvm/rubies/ruby-2.6.6/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/local/rvm/gems/ruby-2.6.6/gems/fpm-1.12.0/lib/fpm/package/gem.rb:7:in `<top (required)>'
	from /usr/local/rvm/rubies/ruby-2.6.6/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/local/rvm/rubies/ruby-2.6.6/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/local/rvm/gems/ruby-2.6.6/gems/fpm-1.12.0/lib/fpm.rb:5:in `<top (required)>'
	from /usr/local/rvm/rubies/ruby-2.6.6/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/local/rvm/rubies/ruby-2.6.6/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/local/rvm/gems/ruby-2.6.6/gems/fpm-1.12.0/bin/fpm:4:in `<top (required)>'
	from /usr/local/rvm/gems/ruby-2.6.6/bin/fpm:23:in `load'
	from /usr/local/rvm/gems/ruby-2.6.6/bin/fpm:23:in `<main>'
	from /usr/local/rvm/gems/ruby-2.6.6/bin/ruby_executable_hooks:24:in `eval'
	from /usr/local/rvm/gems/ruby-2.6.6/bin/ruby_executable_hooks:24:in `<main>'
```

**Comment by jordansissel** [comment]
Oops. This dependency was accidental. I don’t think the git binary should
be required when it’s not being used. See
https://github.com/jordansissel/fpm/issues/1748 for some more details.

I’d like to get this fixed and push a bug fix soon.

**Comment by jacaetevha** [comment]
Oh, great. Thanks @jordansissel . Love this gem!!
