### ISSUE TITLE
git is a required dependency

### ISSUE THREAD

**Issue by ekultails** [jordansissel/fpm#1765]
On Debian 11, after installing the dependencies [1] and running `fpm -s rpm -t deb <RPM_NAME>.rpm` an occur is presented about `git` not being found. After installing the package, the error no longer appears and the command works correctly.

```
Traceback (most recent call last):
	14: from /usr/local/bin/fpm:23:in `<main>'
	13: from /usr/local/bin/fpm:23:in `load'
	12: from /var/lib/gems/2.7.0/gems/fpm-1.12.0/bin/fpm:4:in `<top (required)>'
	11: from /usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb:85:in `require'
	10: from /usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb:85:in `require'
	 9: from /var/lib/gems/2.7.0/gems/fpm-1.12.0/lib/fpm.rb:5:in `<top (required)>'
	 8: from /usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb:85:in `require'
	 7: from /usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb:85:in `require'
	 6: from /var/lib/gems/2.7.0/gems/fpm-1.12.0/lib/fpm/package/gem.rb:7:in `<top (required)>'
	 5: from /usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb:85:in `require'
	 4: from /usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb:85:in `require'
	 3: from /var/lib/gems/2.7.0/gems/git-1.8.1/lib/git.rb:28:in `<top (required)>'
	 2: from /var/lib/gems/2.7.0/gems/git-1.8.1/lib/git/lib.rb:1000:in `meets_required_version?'
	 1: from /var/lib/gems/2.7.0/gems/git-1.8.1/lib/git/lib.rb:990:in `current_command_version'
/var/lib/gems/2.7.0/gems/git-1.8.1/lib/git/lib.rb:1097:in `command': git '-c' 'color.ui=false' version   2>&1:sh: 1: git: not found (Git::GitExecuteError)
```

1. https://fpm.readthedocs.io/en/latest/installing.html

**Comment by jordansissel** [comment]
Hi!

Git is an accidental dependency and this is a bug.

I’ve got a patch that should fix it and would benefit from testing, if you
can?
https://github.com/jordansissel/fpm/pull/1753

**Comment by ekultails** [comment]
Thanks for the quick response! I downloaded your branch with the fixes, removed `git` from my system, installed the gem, and verified it works now!
