### ISSUE TITLE
Error on Fedora 34: cannot load such file -- rexml/document

### ISSUE THREAD

**Issue by Ambrevar** [jordansissel/fpm#1784]
I've installed fpm in Fedora 34 Docker with
```
sudo gem install --no-document fpm
```

When I try to package an .rpm, it yields the following stacktrace:

```ruby
<internal:/usr/share/rubygems/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- rexml/document (LoadError)
	from <internal:/usr/share/rubygems/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /usr/local/share/gems/gems/fpm-1.12.0/lib/fpm/package/osxpkg.rb:7:in `<top (required)>'
	from <internal:/usr/share/rubygems/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/usr/share/rubygems/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /usr/local/share/gems/gems/fpm-1.12.0/lib/fpm.rb:15:in `<top (required)>'
	from <internal:/usr/share/rubygems/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/usr/share/rubygems/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /usr/local/share/gems/gems/fpm-1.12.0/bin/fpm:4:in `<top (required)>'
	from /usr/local/bin/fpm:23:in `load'
	from /usr/local/bin/fpm:23:in `<main>'
```

The command I've invoked is

```
"fpm" "-s" "dir" "-t" "rpm" "--maintainer=Atlas Engineer LLC"
               "--license=BSD 3-Clause"
               "--description=Extensible web-browser in Common Lisp"
               "--url=https://nyxt.atlas.engineer" "--depends=glib-networking"
               "--depends=gsettings-desktop-schemas" "--depends=xclip"
               "--depends=enchant" "--depends=notify-osd" "--depends=glibc"
               "--depends=zlib" "--depends=webkit2gtk3" "--depends=gtk3"
               "--depends=gtk3" "--depends=pango" "--depends=pango"
               "--depends=cairo" "--depends=gdk-pixbuf2" "--depends=glib2"
               "--depends=glib2" "--depends=glib2" "--depends=glib2"
               "--depends=libfixposix-devel" "--depends=openssl-libs" "-n"
               "nyxt" "-v" "2" "nyxt=/usr/bin/"
               "assets/nyxt.desktop=usr/share/applications/"
               "assets/nyxt_16x16.png=usr/share/icons/hicolor/16x16/apps/nyxt.png"
               "assets/nyxt_32x32.png=usr/share/icons/hicolor/32x32/apps/nyxt.png"
               "assets/nyxt_128x128.png=usr/share/icons/hicolor/128x128/apps/nyxt.png"
               "assets/nyxt_256x256.png=usr/share/icons/hicolor/256x256/apps/nyxt.png"
               "assets/nyxt_512x512.png=usr/share/icons/hicolor/512x512/apps/nyxt.png"
```

Any idea?

**Comment by aanno** [comment]
Did you tried `dnf install rubygem-rexml`? `fpm` is a bit tricky to install (but it's running on my f34 machine)...

**Comment by Ambrevar** [comment]
It worked, thanks!

**Comment by Kastakin** [comment]
Solved the same issue on an Arch based machine with `pacman -S ruby-rexml`

**Comment by jordansissel** [comment]
Curious -- Are you using ruby 3.0.0 or newer? Ruby made some changes specific to rexml that can cause this error. If you're hitting this error on Ruby 3.0.0 or newer, please let me know here.

**Comment by Ambrevar** [comment]
According to this page,

https://src.fedoraproject.org/rpms/ruby

Fedora 34 uses Ruby 3.0.1.

**Comment by Kastakin** [comment]
It seems arch is using a similar version: 

[https://archlinux.org/packages/extra/x86_64/ruby/]()

**Comment by jordansissel** [comment]
#1950 merged and should resolve this. Let me know if it's not working :)
