### ISSUE TITLE
[Ruby 3.0] 'Header magic did not match' on rpm package

### ISSUE THREAD

**Issue by aanno** [jordansissel/fpm#1786]
```
$ fpm -s rpm -t dir ../nymphcast-all-0.0.1-1.fc34.x86_64.rpm 
/mnt/home/tpasch/.gem/ruby/gems/arr-pm-0.0.10/lib/arr-pm/file/header.rb:85:in `validate': Header magic did not match; got "\\x8E\\xAD\\xE8\\x01\\x00\\x00\\x00\\x00", expected "\\x8E\\xAD\\xE8\\u0001\\u0000\\u0000\\u0000\\u0000" (RuntimeError)
        from /mnt/home/tpasch/.gem/ruby/gems/arr-pm-0.0.10/lib/arr-pm/file/header.rb:57:in `read'
        from /mnt/home/tpasch/.gem/ruby/gems/arr-pm-0.0.10/lib/arr-pm/file.rb:55:in `signature'
        from /mnt/home/tpasch/.gem/ruby/gems/arr-pm-0.0.10/lib/arr-pm/file.rb:68:in `header'
        from /mnt/home/tpasch/.gem/ruby/gems/fpm-1.12.0/lib/fpm/package/rpm.rb:358:in `input'
        from /mnt/home/tpasch/.gem/ruby/gems/fpm-1.12.0/lib/fpm/command.rb:352:in `block in execute'
        from /mnt/home/tpasch/.gem/ruby/gems/fpm-1.12.0/lib/fpm/command.rb:351:in `each'
        from /mnt/home/tpasch/.gem/ruby/gems/fpm-1.12.0/lib/fpm/command.rb:351:in `execute'
        from /mnt/home/tpasch/.gem/ruby/gems/clamp-1.0.1/lib/clamp/command.rb:68:in `run'
        from /mnt/home/tpasch/.gem/ruby/gems/fpm-1.12.0/lib/fpm/command.rb:574:in `run'
        from /mnt/home/tpasch/.gem/ruby/gems/clamp-1.0.1/lib/clamp/command.rb:133:in `run'
        from /mnt/home/tpasch/.gem/ruby/gems/fpm-1.12.0/bin/fpm:7:in `<top (required)>'
        from /mnt/home/tpasch/bin/fpm:23:in `load'
        from /mnt/home/tpasch/bin/fpm:23:in `<main>'
```

`nymphcast-all-0.0.1-1.fc34.x86_64.rpm` is a self built _experimental_ package (build with [pacur](https://github.com/pacur/pacur)).

**Comment by aanno** [comment]
Well just in case:

```bash
$ sudo dnf install ./nymphcast-all-0.0.1-1.fc34.x86_64.rpm 
keybase                                                                                     6.4 kB/s | 3.3 kB     00:00    
Fehler: 
 Problem: conflicting requests
  - nothing provides libnymphcast.so.0.1()(64bit) needed by nymphcast-all-0.0.1-1.fc34.x86_64
(try to add '--skip-broken' to skip uninstallable packages)
```

Hence: yes, the package is broken. But is _not_ broken from the 'Header magic'. `dnf` of Fedora 34 accepts the package without complaining...

**Comment by ixsrscl** [comment]
Did you solve this i got same issue

**Comment by jordansissel** [comment]
This is a bug in fpm.

**Comment by Bug-Reaper** [comment]
Same issue, is there no work-around? (Arch linux w/fpm installed via ruby gem manager thing).

**Comment by Bug-Reaper** [comment]
@jordansissel See above comment. Not sure if something updated with ruby and broke the way arr-pm worked. I think I can tie my first encounter with this problem to when I started using the ruby3.0.0 compiled gem for arr-pm.

**Comment by jordansissel** [comment]
fpm seems to have other issues on ruby 3.0. I'll take a look.

**Comment by jordansissel** [comment]
This specific issue (header magic ...) was due to a library `arr-pm` not working correctly in Ruby 3.0. This was fixed by https://github.com/jordansissel/ruby-arr-pm/pull/12 and is now released as library version arr-pm 0.0.11.

**Comment by jordansissel** [comment]
this should be fixed now, tests I did.

First, testing known failure under Ruby 3.0 with arr-pm 0.0.10:

```
% gem uninstall -a --force --silent arr-pm; gem install arr-pm --no-doc -v 0.0.10; gem install --no-doc fpm; fpm -s rpm -t deb example-1.0-1.x86_64.rpm
Fetching arr-pm-0.0.10.gem
Successfully installed arr-pm-0.0.10
1 gem installed
Successfully installed fpm-1.12.0
1 gem installed
/home/jls/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/arr-pm-0.0.10/lib/arr-pm/file/header.rb:85:in `validate': Header magic did not match; got "\\x8E\\xAD\\xE8\\x01\\x00\\x00\\x00\\x00", expected "\\x8E\\xAD\\xE8\\u0001\\u0000\\u0000\\u0000\\u0000" (RuntimeError)
```


Now, try again letting `gem` choose the latest version of `arr-pm`

```
% gem uninstall -a --force --silent arr-pm; gem install --no-doc fpm; fpm -s rpm -t deb example-1.0-1.x86_64.rpm
Fetching arr-pm-0.0.11.gem
Successfully installed arr-pm-0.0.11
Successfully installed fpm-1.12.0
2 gems installed
...
Created package {:path=>"example_1.0-1_amd64.deb"}
```

**Comment by jordansissel** [comment]
Recommended solution for anyone affected: You'll need `arr-pm` to get upgraded.

Steps for this, if you are impacted today by this issue:

* `gem update arr-pm --no-doc`

New `fpm` installs should not be affected by this issue because `gem install fpm` on a fresh system will grab the latest `arr-pm` dependency.

You can determine if you are impacted by using `gem list arr-pm`. You need version 0.0.11 available:

```
% gem list arr-pm

*** LOCAL GEMS ***

arr-pm (0.0.11, 0.0.10)
```

The above output shows that arr-pm 0.0.11 is available and installed correctly.

**Comment by Bug-Reaper** [comment]
Thanks @jordansissel
