### ISSUE TITLE
Ruby 3.0.1 - fpm setting clamp default flag values fails

### ISSUE THREAD

**Issue by jordansissel** [jordansissel/fpm#1792]
```
% bin/fpm -s empty -t rpm -n example
/home/jls/projects/fpm/lib/fpm/command.rb:397:in `block in execute': undefined method `default_architecture' for #<FPM::Command:0x0000561c10667f88 ... ... ... > (NoMethodError)
Did you mean?  default_attrs
	from /home/jls/projects/fpm/lib/fpm/command.rb:402:in `execute'
	from /home/jls/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/clamp-1.3.2/lib/clamp/command.rb:66:in `run'
```

Code affected:
https://github.com/jordansissel/fpm/blob/d50f756d0e3f9e52bba18bee8e01c740982d18ad/lib/fpm/command.rb#L388-L401

I'm not sure right now what causes this.

In the past, clamp would provide `default_foo` when you specified `option "--foo", "FOO", ...` but maybe that's changed. I'll need to check more.

**Comment by jordansissel** [comment]
This was my error; my dev env was using clamp 1.0.1. Upgrading fixed this (clamp 1.3.x, as permitted by the gemspec)
