### ISSUE TITLE
[ruby 3.0 + bundler] rexml not found

### ISSUE THREAD

**Issue by jordansissel** [jordansissel/fpm#1793]
```
/home/jls/projects/fpm/lib/fpm/package/osxpkg.rb:7:in `require': cannot load such file -- rexml/document (LoadError)
```

This seems to be due to the fact that rexml was moved from a "standard" gem (in ruby 2.x) to a "bundled" gem (in ruby 3.x).

A fix for this is to add `rexml` as a dependency in the gemspec.

**Comment by jordansissel** [comment]
Test cases for this:

Fails on 3.0.1 w/ bundler
```
% (rbenv shell 3.0.1; bundle install; bundle exec bin/fpm -s empty -t empty -n example)
...
/home/jls/projects/fpm/lib/fpm/package/osxpkg.rb:7:in `require': cannot load such file -- rexml/document (LoadError)
```

Working on 2.7.0 w/ bundler
```
% (rbenv shell 2.7.0; bundle install; bundle exec bin/fpm -s empty -t empty -n example)
Your package has gone into the void. {:level=>:warn}
Created package {:path=>""}
```
