### ISSUE TITLE
`default_architecture' for #<FPM::Command:0x00000008067847a0> (NoMethodError)

### ISSUE THREAD

**Issue by theDraco** [jordansissel/fpm#1863]
```
root@FreeBSD:/home/FreeBSD/Github/jumpapp # fpm -s dir -t freebsd -p jumpapp-1.1.pkg --name jumpapp --license MIT --version 1.1 --architecture all --description "A run-or-raise application switcher for any X11 desktop" --url "https://github.com/mkropat/jumpapp" --maintainer "Jumpapp <maintain@jumpapp.com>" jumpapp=/usr/bin/jumpapp
Traceback (most recent call last):
        7: from /usr/local/bin/fpm:23:in `<main>'
        6: from /usr/local/bin/fpm:23:in `load'
        5: from /usr/local/lib/ruby/gems/2.7/gems/fpm-1.11.0/bin/fpm:7:in `<top (required)>'
        4: from /usr/local/lib/ruby/gems/2.7/gems/clamp-1.3.2/lib/clamp/command.rb:140:in `run'
        3: from /usr/local/lib/ruby/gems/2.7/gems/fpm-1.11.0/lib/fpm/command.rb:574:in `run'
        2: from /usr/local/lib/ruby/gems/2.7/gems/clamp-1.3.2/lib/clamp/command.rb:66:in `run'
        1: from /usr/local/lib/ruby/gems/2.7/gems/fpm-1.11.0/lib/fpm/command.rb:402:in `execute'
/usr/local/lib/ruby/gems/2.7/gems/fpm-1.11.0/lib/fpm/command.rb:397:in `block in execute': undefined method `default_architecture' for #<FPM::Command:0x00000008067847a0> (NoMethodError)
Did you mean?  default_attrs
```
Can someone help me resolve this? I'm trying to make a package of jumpapp for FreeBSD.

**Comment by Apteryks** [comment]
Hm, I'm of no help yet but I'm also seeing this with the `fpm` package I mad in GNU Guix.  Did you end up finding a solution?  It may be a packaging problem.

**Comment by Apteryks** [comment]
Ah, it seems this is a duplicated of https://github.com/jordansissel/fpm/issues/1543.
