### ISSUE TITLE
Add suppport for pip's new `pyproject.toml` ?

### ISSUE THREAD

**Issue by lcosmin** [jordansissel/fpm#1873]
For a while now it seems that `pip` has deprecated using `setup.py` in favor of a [different approach](https://pip.pypa.io/en/stable/reference/build-system/pyproject-toml/), using `pyproject.toml`. 

Would it be possible to support this approach for creating packages out of PyPI ? 

For example, the [structlog](https://github.com/hynek/structlog) project has completely discarded `setup.py` and trying to build a package for it fails:

```
$ fpm --verbose -s python -t deb --python-install-bin /usr/bin --python-bin=/usr/bin/python3 --python-package-name-prefix=python3 --python-pip=/usr/bin/pip3 --python-install-lib=/usr/lib/python3/dist-packages/ structlog
Setting workdir {:workdir=>"/tmp", :level=>:info}
Trying to download {:package=>"structlog", :level=>:info}
Looking in indexes: https://pypi.python.org/simple {:level=>:info}
Collecting structlog {:level=>:info}
  Using cached structlog-21.5.0.tar.gz (473 kB) {:level=>:info}
  Installing build dependencies: started {:level=>:info}
  Installing build dependencies: finished with status 'done' {:level=>:info}
  Getting requirements to build wheel: started {:level=>:info}
  Getting requirements to build wheel: finished with status 'done' {:level=>:info}
    Preparing wheel metadata: started {:level=>:info}
    Preparing wheel metadata: finished with status 'done' {:level=>:info}
  Saved /tmp/package-python-build-9d4a0e42c924109148bd3f697cf51ebdd039757d0336f4d6714e497a7639/structlog-21.5.0.tar.gz {:level=>:info}
Successfully downloaded structlog {:level=>:info}
Could not find 'setup.py' {:path=>"/tmp/package-python-build-9d4a0e42c924109148bd3f697cf51ebdd039757d0336f4d6714e497a7639/structlog/structlog/setup.py", :level=>:error}
Traceback (most recent call last):
	9: from /usr/local/bin/fpm:23:in `<main>'
	8: from /usr/local/bin/fpm:23:in `load'
	7: from /var/lib/gems/2.7.0/gems/fpm-1.14.1/bin/fpm:7:in `<top (required)>'
	6: from /var/lib/gems/2.7.0/gems/clamp-1.0.1/lib/clamp/command.rb:133:in `run'
	5: from /var/lib/gems/2.7.0/gems/fpm-1.14.1/lib/fpm/command.rb:574:in `run'
	4: from /var/lib/gems/2.7.0/gems/clamp-1.0.1/lib/clamp/command.rb:68:in `run'
	3: from /var/lib/gems/2.7.0/gems/fpm-1.14.1/lib/fpm/command.rb:351:in `execute'
	2: from /var/lib/gems/2.7.0/gems/fpm-1.14.1/lib/fpm/command.rb:351:in `each'
	1: from /var/lib/gems/2.7.0/gems/fpm-1.14.1/lib/fpm/command.rb:352:in `block in execute'
/var/lib/gems/2.7.0/gems/fpm-1.14.1/lib/fpm/package/python.rb:108:in `input': Unable to find python package; tried /tmp/package-python-build-9d4a0e42c924109148bd3f697cf51ebdd039757d0336f4d6714e497a7639/structlog/structlog/setup.py (RuntimeError)
```

Trying to create the package from an older version, when setup.py was still present, works:

```
$ fpm  -s python -t deb --python-install-bin /usr/bin --python-bin=/usr/bin/python3 --python-package-name-prefix=python3 --python-pip=/usr/bin/pip3 --python-install-lib=/usr/lib/python3/dist-packages/ structlog==20.2.0

Created package {:path=>"python3-structlog_20.2.0_all.deb"}
```

I'm testing on an up to date ubuntu focal, fpm 1.14.1, python3 3.8.2-0ubuntu2 , python3-pip 20.0.2-5ubuntu1.6

**Comment by jdratlif** [comment]
I would also be interested in this.

**Comment by amdei** [comment]
Yet another package without setup.py: https://pypi.org/project/typing-extensions/

**Comment by ObjatieGroba** [comment]
The only one way is to use pip instead of easy_install

**Comment by riton** [comment]
This would of course be awesome if `fpm` has built-in support for `pyproject.toml`.

I know this is no long term solution, but I use a stupid workaround for projects that rely on `flit` or `poetry` to build

### `poetry`

From my _very short experience_ with `poetry`, it seems that unless
```
[tool.poetry.build]
generate-setup-file = false
```
is present in the `pyproject.toml` file, `poetry` will generate a `setup.py` in the `sdist` archive.

I currently just extract this `setup.py` generated file to the _project root directory_ and launch `fpm` like usual.

## `flit`

I literally have **no experience** with `flit`. I've simply found that using `flit build  --setup-py` also generates an _old style_ `setup.py` file that can be used like before.

I've successfully use this _workaround_ to build the package mentioned by @amdei in https://github.com/jordansissel/fpm/issues/1873#issuecomment-1031265116


Those are, of course, just workarounds and absolutely no long term solutions.
They may even not work for all packages, but this still saves me a lot of time.

Hope this may help someone stuck on this during the _transition phase_

**Comment by jvdmr** [comment]
Does anybody have an idea on how to get started here? I've been looking into using `setuptools`, `pypa/build`, `pkginfo` and other ways (like building a wheel first) to get metadata from projects that only include a `pyproject.toml` file, but so far haven't found a straightforward solution to this.
