### ISSUE TITLE
fpm exists with some error related to json.

### ISSUE THREAD

**Issue by SSoft7** [jordansissel/fpm#1889]
Can anyone provide some hint about this error? I've tried ruby version 2 as well but the error is the same. I can't figure out the source of this JSON error.

```
fpm --output-type=deb --input-type=python --name=deluge --version=2.0.5 --vendor=Anonymous --maintainer=Anonymous '--description=Custom Deluge Compiled By Anonymous' --url=https://deluge-torrent.org/ --python-bin=/usr/bin/python3 --python-pip=/usr/local/bin/pip3 --python-package-name-prefix=python3 --python-internal-pip --no-python-dependencies --python-obey-requirements-txt --package=/usr/local/src/packages/deluge-2.0.5.deb --before-install=/tmp/deluge_2.0.5_pre-install.sh --after-remove=/tmp/deluge_2.0.5_post-remove.sh --force setup.py
/snap/ruby/278/lib/ruby/3.1.0/json/common.rb:216:in `parse': 859: unexpected token at '' (JSON::ParserError)
        from /snap/ruby/278/lib/ruby/3.1.0/json/common.rb:216:in `parse'
        from /root/.gem/gems/fpm-1.14.2/lib/fpm/package/python.rb:246:in `load_package_info'
        from /root/.gem/gems/fpm-1.14.2/lib/fpm/package/python.rb:111:in `input'
        from /root/.gem/gems/fpm-1.14.2/lib/fpm/command.rb:352:in `block in execute'
        from /root/.gem/gems/fpm-1.14.2/lib/fpm/command.rb:351:in `each'
        from /root/.gem/gems/fpm-1.14.2/lib/fpm/command.rb:351:in `execute'
        from /root/.gem/gems/clamp-1.0.1/lib/clamp/command.rb:68:in `run'
        from /root/.gem/gems/fpm-1.14.2/lib/fpm/command.rb:574:in `run'
        from /root/.gem/gems/clamp-1.0.1/lib/clamp/command.rb:133:in `run'
        from /root/.gem/gems/fpm-1.14.2/bin/fpm:7:in `<top (required)>'
        from /usr/local/bin/fpm:23:in `load'
```

**Comment by liaralabs** [comment]
Came here to report this bug but see you beat me to it. For what it's worth, I'm also trying to build deluge with fpm and my arguments are similar, however this is all it takes to throw the error. First cloned deluge via git on the master branch, then

```
fpm --python-bin=python3 -n deluge-common -f -p /root/dist/deluge-common_VERSION.deb --description "Deluge compiled by swizzin" -s python -t deb /tmp/deluge/setup.py
```

I wonder if it's related to this: https://github.com/jordansissel/fpm/pull/1806

I'm testing out jammy compilations and bumped into this

**Comment by jordansissel** [comment]
This could be a bug in fpm. It looks like it fails when trying to figure out what version/name/etc the Deluge Python package has. I’ll see if I can figure out a solution — in the meantime, please continue posting any additional data you come across. 

On Tue, Apr 19, 2022, at 7:57 PM, liaralabs wrote:
> 
> 
> Came here to report this bug but see you beat me to it. For what it's worth, I'm also trying to build deluge with fpm and my arguments are similar, however this is all it takes to throw the error. First cloned deluge via git on the master branch, then
> 
> `fpm --python-bin=python3 -n deluge-common -f -p /root/dist/deluge-common_VERSION.deb --description "Deluge compiled by swizzin" -s python -t deb /tmp/deluge/setup.py
`

**Comment by liaralabs** [comment]
Okay, so it seems that in my case, specifically, this error came down to an opinionated vagrant box that I was using as a shortcut to test some development work for the upcoming 22.04 release and not fpm.

There was a custom repo configured which was recompiling a bunch of python3 packages and installing them by default. That's what I get for using someone else's box :smile:  I removed the repo and did a force downgrade of all the affected packages and fpm was able to compile the deluge package successfully.

The wheel package in particular wasn't showing up in a `pip list` but just fixing wheel alone wasn't enough.

Since you can't have `python3-pip` without `python3-wheel` installed I can't put fpm into a situation where this has the potential to break anymore. However, just fixing wheel but not the rest of the python led to a similar output as the author (i.e. no complaints about wheel but also a failure). Given my issues were caused by a poorly configured python env, I wonder if the author could be in a similar state as well.

**Comment by SSoft7** [comment]
I've tested this on a new installation of Ubuntu focal (Official image) and the unexpected error token is pointing at a random line number If I tweak command-line options.

Any update on this?

**Comment by SSoft7** [comment]
This issue only happens with Ubuntu Focal (20.04) + ...Worked fine for ubuntu bionic...So, I'm guessing something changed from Ubuntu focal onwards..Probably a dependency of fpm changed with ubuntu focal?

**Comment by SSoft7** [comment]
@liaralabs can you provide a list of your python3 packages? I would like to compare the versions of python3 packages with mine. Currently, I'm testing this on ubuntu jammy 22.04 and fpm is still failing there.

If you know which exact python package was causing trouble let me know please .

**Comment by liaralabs** [comment]
I only have a vagrant environment for jammy and tested these scripts on the generic/ubuntu2204 image recently. I don't know versions, but this is everything that should be required to build deluge with fpm:

https://github.com/swizzin/swizzin/blob/master/sources/functions/deluge#L175

**Comment by SSoft7** [comment]
> I only have a vagrant environment for jammy and tested these scripts on the generic/ubuntu2204 image recently. I don't know versions, but this is everything that should be required to build deluge with fpm:
> 
> https://github.com/swizzin/swizzin/blob/master/sources/functions/deluge#L175
> 
> My previous issue was related to setup tools and potentially pip itself I think

Thank you for pointing out the `setup-tools` package. That was definitely breaking things for me as well. I had `pip3 install -U setuptools` on my install script which was upgrading setuptools to the latest available version.
After some digging I found out that, this issue appears from setup tools 60.8.0. So the fix for me was `pip3 install setuptools==60.7.1 `

**Comment by cwegener** [comment]
> After some digging I found out that, this issue appears from setup tools 60.7.1.
Is there any way to find out where the issue with setuptools is? Trying to downgrade a core component like setuptools is a bit tricky (e.g. virtualenv is ruled out for switching to a different setuptools version for doing fpm package builds)

**Comment by SSoft7** [comment]
> > After some digging I found out that, this issue appears from setup tools 60.7.1.
> 
> Is there any way to find out where the issue with setuptools is? Trying to downgrade a core component like setuptools is a bit tricky (e.g. virtualenv is ruled out for switching to a different setuptools version for doing fpm package builds)

Honestly, I have no idea. even the downgrades sometimes do not work....it seems there is some conflict between the pre-installed OS setuptools and the pip installed setuptools.

**Comment by cwegener** [comment]
> > > After some digging I found out that, this issue appears from setup tools 60.7.1.
> > 
> > 
> > Is there any way to find out where the issue with setuptools is? Trying to downgrade a core component like setuptools is a bit tricky (e.g. virtualenv is ruled out for switching to a different setuptools version for doing fpm package builds)
> 
> Honestly, I have no idea. even the downgrades sometimes do not work....it seems there is some conflict between the pre-installed OS setuptools and the pip installed setuptools.

FWIW, I'm sticking to Ubuntu 20.04 LTS for `fpm -s python` and it's all working like a treat (using OS provided setuptools which is version 45.2.0 on Ubuntu 20.04)

**Comment by jordansissel** [comment]
I think I figured out the issue.

I ran into this myself and, when troubleshooting it, I found that fpm was getting no information out of the python package. Fpm will write JSON to a file (using python) and the parse it in to find out what the package's name, version, etc are.

In this case, the file is empty.

I tracked the bug back to fpm's pyfpm/get_metadata.py -- I assume this is caused by a new behavior in Python? I used Python 3.11, and the problem seems to be that file writes are not flushed unless you explicitly call file.close()  or file.flush(), and fpm was not invoking this in Python. This *did* work in older versions of pythons where it would flush the write buffer when Python exited.

**Comment by jordansissel** [comment]
I believe #1966 fixes this.
