### ISSUE TITLE
python.rb if the meta['license'] is nil -> `load_package_info':     undefined method `split' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by philschwartzsonos** [jordansissel/fpm#1920]
I've encountered this error when processing the following pip3 packages on ubuntu 22.04 / ruby3.0: isort lockfile pbr pygithub xdg

for instance:
$ fpm -s python -t deb --python-bin=python3 --python-pip=pip3 --python-package-name-prefix=python3 --python-install-lib=/usr/lib/python3/dist-packages --python-install-bin=/usr/bin --deb-no-default-config-files   xdg
    jammy: error occurred building package: xdg
    jammy: re-running with verbose output: fpm -s python -t deb --python-bin=python3 --python-pip=pip3 --python-package-name-prefix=python3 --python-install-lib=/usr/lib/python3/dist-packages --python-install-bin=/usr/bin --maintainer=dl-infra-platforms@sonos.com --deb-no-default-config-files   --verbose xdg
    jammy: {:timestamp=>"2022-08-08T15:01:26.749173+0000", :message=>"Setting workdir", :workdir=>"/tmp", :level=>:info}
    jammy: {:timestamp=>"2022-08-08T15:01:26.754766+0000", :message=>"Trying to download", :package=>"xdg", :level=>:info}
    jammy: {:timestamp=>"2022-08-08T15:01:27.290965+0000", :message=>"Looking in indexes: https://pypi.python.org/simple", :level=>:info}
    jammy: {:timestamp=>"2022-08-08T15:01:27.530018+0000", :message=>"Collecting xdg", :level=>:info}
    jammy: {:timestamp=>"2022-08-08T15:01:27.534536+0000", :message=>"  Using cached xdg-5.1.1.tar.gz (4.7 kB)", :level=>:info}
    jammy: {:timestamp=>"2022-08-08T15:01:27.754842+0000", :message=>"  Installing build dependencies: started", :level=>:info}
    jammy: {:timestamp=>"2022-08-08T15:01:32.742207+0000", :message=>"  Installing build dependencies: finished with status 'done'", :level=>:info}
    jammy: {:timestamp=>"2022-08-08T15:01:32.745669+0000", :message=>"  Getting requirements to build wheel: started", :level=>:info}
    jammy: {:timestamp=>"2022-08-08T15:01:33.436189+0000", :message=>"  Getting requirements to build wheel: finished with status 'done'", :level=>:info}
    jammy: {:timestamp=>"2022-08-08T15:01:33.438013+0000", :message=>"  Preparing metadata (pyproject.toml): started", :level=>:info}
    jammy: {:timestamp=>"2022-08-08T15:01:33.984831+0000", :message=>"  Preparing metadata (pyproject.toml): finished with status 'done'", :level=>:info}
    jammy: {:timestamp=>"2022-08-08T15:01:33.988133+0000", :message=>"Saved /tmp/package-python-build-049913cf5c58fad55d755b740715ada8e34d19097a01096ca266ecc180e4/xdg-5.1.1.tar.gz", :level=>:info}
    jammy: {:timestamp=>"2022-08-08T15:01:33.988752+0000", :message=>"Successfully downloaded xdg", :level=>:info}
    jammy: {:timestamp=>"2022-08-08T15:01:34.253453+0000", :message=>"fetching package metadata", :setup_cmd=>"env PYTHONPATH=/var/lib/gems/3.0.0/gems/fpm-1.13.1/lib/fpm/package:$PYTHONPATH python3 setup.py --command-packages=pyfpm get_metadata --output=/tmp/package-python-build-049913cf5c58fad55d755b740715ada8e34d19097a01096ca266ecc180e4/metadata.json", :level=>:info}
    jammy: {:timestamp=>"2022-08-08T15:01:34.559388+0000", :message=>"running get_metadata", :level=>:info}
    jammy: {:timestamp=>"2022-08-08T15:01:34.592307+0000", :message=>"object output of get_metadata", :json=>{"name"=>"xdg", "version"=>"5.1.1", "author"=>"Scott Stevenson <scott@stevenson.io>", "description"=>"Variables defined by the XDG Base Directory Specification", "license"=>nil, "url"=>"https://github.com/srstevenson/xdg", "architecture"=>"all", "dependencies"=>[]}, :level=>:info}
    jammy: /var/lib/gems/3.0.0/gems/fpm-1.13.1/lib/fpm/package/python.rb:262:in `load_package_info': undefined method `split' for nil:NilClass (NoMethodError)
    jammy: 	from /var/lib/gems/3.0.0/gems/fpm-1.13.1/lib/fpm/package/python.rb:111:in `input'
    jammy: 	from /var/lib/gems/3.0.0/gems/fpm-1.13.1/lib/fpm/command.rb:352:in `block in execute'
    jammy: 	from /var/lib/gems/3.0.0/gems/fpm-1.13.1/lib/fpm/command.rb:351:in `each'
    jammy: 	from /var/lib/gems/3.0.0/gems/fpm-1.13.1/lib/fpm/command.rb:351:in `execute'
    jammy: 	from /var/lib/gems/3.0.0/gems/clamp-1.0.1/lib/clamp/command.rb:68:in `run'
    jammy: 	from /var/lib/gems/3.0.0/gems/fpm-1.13.1/lib/fpm/command.rb:574:in `run'
    jammy: 	from /var/lib/gems/3.0.0/gems/clamp-1.0.1/lib/clamp/command.rb:133:in `run'
    jammy: 	from /var/lib/gems/3.0.0/gems/fpm-1.13.1/bin/fpm:7:in `<top (required)>'
    jammy: 	from /usr/local/bin/fpm:25:in `load'
    jammy: 	from /usr/local/bin/fpm:25:in `<main>'

I was able to "fix" the issue by adding an exception handler in python.rb as such:

    # Sometimes the license field is multiple lines; do best-effort and just
    # use the first line.
    begin
      self.license = metadata["license"].split(/[\r\n]+/).first
    rescue
      self.license = ""
    end
    self.version = metadata["version"]

**Comment by jordansissel** [comment]
Is this still an issue for you? I tried this just now and it works for me on the main branch, and do my knowledge, the `metadata["license"].split(...)` line is still there in the main branch:

```
% bundle exec bin/fpm -s python -t deb --python-bin=python3 --python-pip=pip3 --python-package-name-prefix=python3 --pyt
hon-install-lib=/usr/lib/python3/dist-packages --python-install-bin=/usr/bin --deb-no-default-config-files xdg
...
Created package {:path=>"python3-xdg_5.1.1_all.deb"}
```

I tested with the same command on fpm 1.14.2 and it fails, though with a different error than yours.

**Comment by philschwartzsonos** [comment]
Oh wow, totally forgot about this issue.  Things are working for me since I patched 1.14.2 with that exception handler (above).  Since things are working on the main branch, when you release a new version I'll see if still persists.
