### ISSUE TITLE
fpm rpm test suite fails on fedora 36

### ISSUE THREAD

**Issue by jordansissel** [jordansissel/fpm#1956]
Sample failure 

```
  1) FPM::Package::RPM#output architecture can be basically anything
     Failure/Error: rpm = ::RPM::File.new(target)
     Errno::ENOENT:
       No such file or directory @ rb_sysopen - /run/user/1000/studtmp-ba2e3ed252acb8208461a7b55e4ce412bc3b63058a83f50d1927aa28f3b0
     # ./spec/fpm/package/rpm_spec.rb:165:in `new'
     # ./spec/fpm/package/rpm_spec.rb:165:in `block (4 levels) in <top (required)>'
```

Running the rpmbuild from this test myself has this error

```
+ /usr/lib/rpm/check-buildroot
xargs: invalid number "%{_smp_build_ncpus}" for -P option
Try 'xargs --help' for more information.
+ /usr/lib/rpm/redhat/brp-ldconfig
+ /usr/lib/rpm/brp-compress
+ /usr/lib/rpm/brp-strip /usr/bin/strip
xargs: invalid number "%{_smp_build_ncpus}" for -P option
Try 'xargs --help' for more information.
error: Bad exit status from /run/user/1000/rpm-tmp.uJQ7Dd (%install)
```

**Comment by jordansissel** [comment]
This seems to be related to the test suite using `fancypants` for the architecture value. I can reproduce this on the commandline:

```
% fpm -s empty -t rpm -n example --verbose -a fancypants
+ export CC {:level=>:info}
+ CXX=g++ {:level=>:info}
+ export CXX {:level=>:info}
+ /usr/lib/rpm/check-buildroot {:level=>:info}
xargs: invalid number "%{_smp_build_ncpus}" for -P option {:level=>:info}
Try 'xargs --help' for more information. {:level=>:info}
+ /usr/lib/rpm/redhat/brp-ldconfig {:level=>:info}
+ /usr/lib/rpm/brp-compress {:level=>:info}
+ /usr/lib/rpm/brp-strip /usr/bin/strip {:level=>:info}
xargs: invalid number "%{_smp_build_ncpus}" for -P option {:level=>:info}
Try 'xargs --help' for more information. {:level=>:info}
 {:level=>:info}
error: Bad exit status from /run/user/1000/tmptest/rpm-tmp.xgAQSq (%install) {:level=>:info}
RPM build errors: {:level=>:info}
    Bad exit status from /run/user/1000/tmptest/rpm-tmp.xgAQSq (%install) {:level=>:info}
```

**Comment by jordansissel** [comment]
Related: https://bugzilla.redhat.com/show_bug.cgi?id=1919148

**Comment by jordansissel** [comment]
I think this specifically is a problem for #237 and I can only reproduce the issue on my branch https://github.com/jordansissel/fpm/pull/1952 and not on the main branch.
