### ISSUE TITLE
fpm 1.15.0 fails on CentOS 7: "nil is not a symbol" in backports code

### ISSUE THREAD

**Issue by kpushkaryov** [jordansissel/fpm#1979]
Freshly installed fpm 1.15.0 fails on CentOS 7:
```
# fpm -v
/usr/local/share/gems/gems/backports-3.23.0/lib/backports/ractor/cloner.rb:36:in `private': nil is not a symbol (TypeError)
	from /usr/local/share/gems/gems/backports-3.23.0/lib/backports/ractor/cloner.rb:36:in `<class:Cloner>'
	from /usr/local/share/gems/gems/backports-3.23.0/lib/backports/ractor/cloner.rb:7:in `<class:Ractor>'
	from /usr/local/share/gems/gems/backports-3.23.0/lib/backports/ractor/cloner.rb:6:in `<module:Backports>'
	from /usr/local/share/gems/gems/backports-3.23.0/lib/backports/ractor/cloner.rb:5:in `<top (required)>'
	from /usr/local/share/gems/gems/backports-3.23.0/lib/backports/ractor/ractor.rb:9:in `require_relative'
	from /usr/local/share/gems/gems/backports-3.23.0/lib/backports/ractor/ractor.rb:9:in `<class:Ractor>'
	from /usr/local/share/gems/gems/backports-3.23.0/lib/backports/ractor/ractor.rb:6:in `<module:Backports>'
	from /usr/local/share/gems/gems/backports-3.23.0/lib/backports/ractor/ractor.rb:5:in `<top (required)>'
	from /usr/local/share/gems/gems/backports-3.23.0/lib/backports/3.0.0/ractor.rb:18:in `require_relative'
	from /usr/local/share/gems/gems/backports-3.23.0/lib/backports/3.0.0/ractor.rb:18:in `<top (required)>'
	from /usr/local/share/gems/gems/backports-3.23.0/lib/backports/tools/require_relative_dir.rb:12:in `require_relative'
	from /usr/local/share/gems/gems/backports-3.23.0/lib/backports/tools/require_relative_dir.rb:12:in `block in require_relative_dir'
	from /usr/local/share/gems/gems/backports-3.23.0/lib/backports/tools/require_relative_dir.rb:9:in `each'
	from /usr/local/share/gems/gems/backports-3.23.0/lib/backports/tools/require_relative_dir.rb:9:in `require_relative_dir'
	from /usr/local/share/gems/gems/backports-3.23.0/lib/backports/3.0.0.rb:3:in `<top (required)>'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/share/gems/gems/backports-3.23.0/lib/backports/3.1.0.rb:2:in `<top (required)>'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/share/gems/gems/backports-3.23.0/lib/backports/latest.rb:4:in `<top (required)>'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/share/gems/gems/fpm-1.15.0/lib/fpm/package.rb:7:in `<top (required)>'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/share/gems/gems/fpm-1.15.0/lib/fpm.rb:3:in `<top (required)>'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/share/gems/gems/fpm-1.15.0/bin/fpm:4:in `<top (required)>'
	from /usr/local/bin/fpm:23:in `load'
	from /usr/local/bin/fpm:23:in `<main>'
# gem list fpm

*** LOCAL GEMS ***

fpm (1.15.0)
# ruby -v
ruby 2.0.0p648 (2015-12-16) [x86_64-linux]
```

**Comment by sivabalan** [comment]
Same with fpm (1.15.1).

**Comment by zxzixuanwang** [comment]
Same，i want to package app to rpm.

**Comment by phat-pat** [comment]
When I tried to downgrade to fpm 1.14, I notice it requires ruby >= 2.6. I assume 1.15 also has this requirement, but the gem doesn't seem to think so. CentOS 7 only has ruby 2.0.0.

So I uninstalled ruby 2.0 (not sure if this is necessary), then used [rvm](http://rvm.io/) to install ruby 2.6.6.
After that, I installed fpm with ruby 2.6.6 and `fpm -v` seems to work fine.
