### ISSUE TITLE
fpm-1.15.0/lib/fpm/command.rb:301:in `execute': undefined method `exists?' for File:Class (NoMethodError) ruby 2.4.5

### ISSUE THREAD

**Issue by romulasry** [jordansissel/fpm#1988]
fpm
/home/user/.local/share/gem/ruby/gems/fpm-1.15.0/lib/fpm/command.rb:301:in `execute': undefined method `exists?' for File:Class (NoMethodError)

    if !File.exists?(workdir)
            ^^^^^^^^
Did you mean?  exist?
	from /home/user/.local/share/gem/ruby/gems/clamp-1.0.1/lib/clamp/command.rb:68:in `run'
	from /home/user/.local/share/gem/ruby/gems/fpm-1.15.0/lib/fpm/command.rb:591:in `run'
	from /home/user/.local/share/gem/ruby/gems/clamp-1.0.1/lib/clamp/command.rb:133:in `run'
	from /home/user/.local/share/gem/ruby/gems/fpm-1.15.0/bin/fpm:7:in `<top (required)>'
	from /home/user/bin/fpm:25:in `load'
	from /home/user/bin/fpm:25:in `<main>'

**Comment by romulasry** [comment]
gem --version
3.4.1

**Comment by romulasry** [comment]
fpm
/home/ryan/.local/share/gem/ruby/3.2.0/gems/fpm-1.15.0/lib/fpm/command.rb:301:in `execute': undefined method `exists?' for File:Class (NoMethodError)

    if !File.exists?(workdir)
            ^^^^^^^^
Did you mean?  exist?
	from /home/ryan/.local/share/gem/ruby/3.2.0/gems/clamp-1.0.1/lib/clamp/command.rb:68:in `run'
	from /home/ryan/.local/share/gem/ruby/3.2.0/gems/fpm-1.15.0/lib/fpm/command.rb:591:in `run'
	from /home/ryan/.local/share/gem/ruby/3.2.0/gems/clamp-1.0.1/lib/clamp/command.rb:133:in `run'
	from /home/ryan/.local/share/gem/ruby/3.2.0/gems/fpm-1.15.0/bin/fpm:7:in `<top (required)>'
	from /home/ryan/bin/fpm:25:in `load'
	from /home/ryan/bin/fpm:25:in `<main>'

gem --version 
3.4.5

**Comment by romulasry** [comment]
https://github.com/jordansissel/fpm/pull/1981
