### ISSUE TITLE
Test failures in containerized environment caused by network access

### ISSUE THREAD

**Issue by Apteryks** [jordansissel/fpm#2000]
Hello FPM!

I've attempted packaging FPM for GNU Guix, and it's mostly there, but I thought I'd report some test failures which  I think could be better handled. For example, test reliant on connectivity could be skipped when there's none.

Here are the failures:

```
Failures:

  1) FPM::Command -p | --package when given a directory should write the package to the given directory.
     Failure/Error: if object.send(attribute).nil? || send(attribute) != send("default_#{attribute}")

     NoMethodError:
       undefined method `default_architecture' for #<FPM::Command:0x0000000001cb36c0>
       Did you mean?  default_attrs
     # ./lib/fpm/command.rb:413:in `block in execute'
     # ./lib/fpm/command.rb:418:in `execute'
     # ./lib/fpm/command.rb:591:in `run'
     # ./spec/fpm/command_spec.rb:95:in `block (5 levels) in <top (required)>'
     # ./spec/fpm/command_spec.rb:93:in `block (4 levels) in <top (required)>'

  2) FPM::Command -p | --package when not set should write the package to the current directory.
     Failure/Error: if object.send(attribute).nil? || send(attribute) != send("default_#{attribute}")

     NoMethodError:
       undefined method `default_architecture' for #<FPM::Command:0x000000000150b210>
       Did you mean?  default_attrs
     # ./lib/fpm/command.rb:413:in `block in execute'
     # ./lib/fpm/command.rb:418:in `execute'
     # ./lib/fpm/command.rb:591:in `run'
     # ./spec/fpm/command_spec.rb:109:in `block (6 levels) in <top (required)>'
     # ./spec/fpm/command_spec.rb:107:in `chdir'
     # ./spec/fpm/command_spec.rb:107:in `block (5 levels) in <top (required)>'
     # ./spec/fpm/command_spec.rb:106:in `block (4 levels) in <top (required)>'

  3) FPM::Command --fpm-options-file with multiple single-letter flags on a single line separately should 
     Failure/Error: option = self.class.find_option(single_letter.match(1))

     NoMethodError:
       undefined method `match' for #<MatchData "-f" 1:"-f" 2:"">
     # ./lib/fpm/command.rb:639:in `block in load_options'
     # ./lib/fpm/command.rb:625:in `each'
     # ./lib/fpm/command.rb:625:in `load_options'
     # ./lib/fpm/command.rb:254:in `block in <class:Command>'
     # ./spec/fpm/command_spec.rb:198:in `block (5 levels) in <top (required)>'

  4) FPM::Command --fpm-options-file with multiple single-letter flags on a single line together should wo
     Failure/Error: option = self.class.find_option(single_letter.match(1))

     NoMethodError:
       undefined method `match' for #<MatchData "-ffff" 1:"-f" 2:"fff">
     # ./lib/fpm/command.rb:639:in `block in load_options'
     # ./lib/fpm/command.rb:625:in `each'
     # ./lib/fpm/command.rb:625:in `load_options'
     # ./lib/fpm/command.rb:254:in `block in <class:Command>'
     # ./spec/fpm/command_spec.rb:210:in `block (5 levels) in <top (required)>'

  5) FPM::Package::CPAN should package Digest::MD5
     Failure/Error: response = http.request(Net::HTTP::Get.new(uri.request_uri))

     SocketError:
       Failed to open TCP connection to fastapi.metacpan.org:443 (getaddrinfo: Name or service not known)
     # ./lib/fpm/package/cpan.rb:408:in `httpfetch'
     # ./lib/fpm/package/cpan.rb:372:in `search'
     # ./lib/fpm/package/cpan.rb:57:in `input'
     # ./spec/fpm/package/cpan_spec.rb:34:in `block (2 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # SocketError:
     #   getaddrinfo: Name or service not known
     #   ./lib/fpm/package/cpan.rb:408:in `httpfetch'

  6) FPM::Package::CPAN should package File::Spec
     Failure/Error: response = http.request(Net::HTTP::Get.new(uri.request_uri))

     SocketError:
       Failed to open TCP connection to fastapi.metacpan.org:443 (getaddrinfo: Name or service not known)
     # ./lib/fpm/package/cpan.rb:408:in `httpfetch'
     # ./lib/fpm/package/cpan.rb:372:in `search'
     # ./lib/fpm/package/cpan.rb:57:in `input'
     # ./spec/fpm/package/cpan_spec.rb:59:in `block (2 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # SocketError:
     #   getaddrinfo: Name or service not known
     #   ./lib/fpm/package/cpan.rb:408:in `httpfetch'

  7) FPM::Package::CPAN should package Class::Data::Inheritable
     Failure/Error: response = http.request(Net::HTTP::Get.new(uri.request_uri))

     SocketError:
       Failed to open TCP connection to fastapi.metacpan.org:443 (getaddrinfo: Name or service not known)
     # ./lib/fpm/package/cpan.rb:408:in `httpfetch'
     # ./lib/fpm/package/cpan.rb:372:in `search'
     # ./lib/fpm/package/cpan.rb:57:in `input'
     # ./spec/fpm/package/cpan_spec.rb:71:in `block (2 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # SocketError:
     #   getaddrinfo: Name or service not known
     #   ./lib/fpm/package/cpan.rb:408:in `httpfetch'

  8) FPM::Package::CPAN given a distribution without a META.* file should package IPC::Session
     Failure/Error: response = http.request(Net::HTTP::Get.new(uri.request_uri))

     SocketError:
       Failed to open TCP connection to fastapi.metacpan.org:443 (getaddrinfo: Name or service not known)
     # ./lib/fpm/package/cpan.rb:408:in `httpfetch'
     # ./lib/fpm/package/cpan.rb:372:in `search'
     # ./lib/fpm/package/cpan.rb:57:in `input'
     # ./spec/fpm/package/cpan_spec.rb:81:in `block (3 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # SocketError:
     #   getaddrinfo: Name or service not known
     #   ./lib/fpm/package/cpan.rb:408:in `httpfetch'

  9) FPM::Package::Gem when :gem_shebang is nil/default should not change the shebang
     Failure/Error: insist { File.readlines(file_path).grep(/^#!\/usr\/bin\/env /).any? } == true

     Insist::Failure:
       Expected true, but got false
     # ./spec/fpm/package/gem_spec.rb:90:in `block (3 levels) in <top (required)>'

  10) FPM::Package::Python python_scripts_executable is set should have scripts with a custom hashbang lin
      Failure/Error:
        raise ProcessFailed.new("#{program} failed (exit code #{exit_code})" \
                                ". Full command was:#{args.inspect}")

      FPM::Util::ProcessFailed:
        python3 failed (exit code 1). Full command was:["python3", "-m", "pip", "download", "--no-clean", 05ac930e3f8a792fdf03997f0310a28a5da769f3a6d39671c98a", "-i", "https://pypi.python.org/simple", "django"]
      # ./lib/fpm/util.rb:193:in `safesystem'
      # ./lib/fpm/package/python.rb:167:in `download_if_necessary'
      # ./lib/fpm/package/python.rb:98:in `input'
      # ./spec/fpm/package/python_spec.rb:199:in `block (3 levels) in <top (required)>'

  11) FPM::Package#staging_path and #staging_path should be a subdirectory of workdir (#1124)
      Failure/Error: @build_path ||= Stud::Temporary.directory("package-#{type}-build")

      Errno::ENOENT:
        No such file or directory @ dir_s_mkdir - /var/tmp/package-package-build-3d56a8f7531c3501143e501d7
      # ./lib/fpm/package.rb:267:in `build_path'
      # ./lib/fpm/package.rb:182:in `initialize'
      # ./spec/fpm/package_spec.rb:208:in `block (3 levels) in <top (required)>'

  12) FPM::Package#staging_path and #staging_path should be a subdirectory of workdir (#1124)
      Failure/Error: @build_path ||= Stud::Temporary.directory("package-#{type}-build")

      Errno::ENOENT:
        No such file or directory @ dir_s_mkdir - /var/tmp/package-package-build-32d3a55482d79569555cf3f5c
      # ./lib/fpm/package.rb:267:in `build_path'
      # ./lib/fpm/package.rb:182:in `initialize'
      # ./spec/fpm/package_spec.rb:214:in `block (3 levels) in <top (required)>'

Finished in 18.13 seconds (files took 0.26977 seconds to load)
360 examples, 12 failures, 58 pending

Failed examples:

rspec ./spec/fpm/command_spec.rb:92 # FPM::Command -p | --package when given a directory should write the 
rspec ./spec/fpm/command_spec.rb:105 # FPM::Command -p | --package when not set should write the package t
rspec ./spec/fpm/command_spec.rb:197 # FPM::Command --fpm-options-file with multiple single-letter flags o
rspec ./spec/fpm/command_spec.rb:209 # FPM::Command --fpm-options-file with multiple single-letter flags o
rspec ./spec/fpm/package/cpan_spec.rb:25 # FPM::Package::CPAN should package Digest::MD5
rspec ./spec/fpm/package/cpan_spec.rb:57 # FPM::Package::CPAN should package File::Spec
rspec ./spec/fpm/package/cpan_spec.rb:65 # FPM::Package::CPAN should package Class::Data::Inheritable
rspec ./spec/fpm/package/cpan_spec.rb:76 # FPM::Package::CPAN given a distribution without a META.* file s
rspec ./spec/fpm/package/gem_spec.rb:87 # FPM::Package::Gem when :gem_shebang is nil/default should not ch
rspec ./spec/fpm/package/python_spec.rb:192 # FPM::Package::Python python_scripts_executable is set should
rspec ./spec/fpm/package_spec.rb:207 # FPM::Package#staging_path and #staging_path should be a subdirector
rspec ./spec/fpm/package_spec.rb:213 # FPM::Package#staging_path and #staging_path should be a subdirector

error: in phase 'check': uncaught exception:
%exception #<&invoke-error program: "rspec" arguments: () exit-status: 1 term-signal: #f stop-signal: #f> 
phase `check' failed after 18.7 seconds
command "rspec" failed with status 1
```

The direct inputs used are: 
```
bash-minimal@5.1.8 dpkg@1.21.21 libarchive@3.5.1 node@10.24.1 perl-app-cpanminus@1.7046
+ python@3.9.9 ruby-arr-pm@0.0.12 ruby-backports@3.11.4 ruby-cabin@0.9.0 ruby-clamp@1.3.2
+ ruby-pleaserun@0.0.32 ruby-rexml@3.2.5 ruby-rspec@3.12.0 ruby-stud@0.0.23 squashfs-tools@4.5 zstd@1.5.0
```

Some errors I'm not sure how to interpret, such as the apparent failure of Stud::Temporary.directory to create temporary directories or the `NoMethodError` errors early in the test.

I hope that report is useful!  Thanks for FPM, it looks promising.

**Comment by Apteryks** [comment]
4 failing tests are skipped whne setting TRAVIS_OS_NAME to some value:
```
Failures:

  1) FPM::Command -p | --package when given a directory should write the package to the given directory.
     Failure/Error: if object.send(attribute).nil? || send(attribute) != send("default_#{attribute}")

     NoMethodError:
       undefined method `default_architecture' for #<FPM::Command:0x0000000001cab6c8>
       Did you mean?  default_attrs
     # ./lib/fpm/command.rb:413:in `block in execute'
     # ./lib/fpm/command.rb:418:in `execute'
     # ./lib/fpm/command.rb:591:in `run'
     # ./spec/fpm/command_spec.rb:95:in `block (5 levels) in <top (required)>'
     # ./spec/fpm/command_spec.rb:93:in `block (4 levels) in <top (required)>'

  2) FPM::Command -p | --package when not set should write the package to the current directory.
     Failure/Error: if object.send(attribute).nil? || send(attribute) != send("default_#{attribute}")

     NoMethodError:
       undefined method `default_architecture' for #<FPM::Command:0x000000000150b198>
       Did you mean?  default_attrs
     # ./lib/fpm/command.rb:413:in `block in execute'
     # ./lib/fpm/command.rb:418:in `execute'
     # ./lib/fpm/command.rb:591:in `run'
     # ./spec/fpm/command_spec.rb:109:in `block (6 levels) in <top (required)>'
     # ./spec/fpm/command_spec.rb:107:in `chdir'
     # ./spec/fpm/command_spec.rb:107:in `block (5 levels) in <top (required)>'
     # ./spec/fpm/command_spec.rb:106:in `block (4 levels) in <top (required)>'

  3) FPM::Command --fpm-options-file with multiple single-letter flags on a single line separately should work
     Failure/Error: option = self.class.find_option(single_letter.match(1))

     NoMethodError:
       undefined method `match' for #<MatchData "-f" 1:"-f" 2:"">
     # ./lib/fpm/command.rb:639:in `block in load_options'
     # ./lib/fpm/command.rb:625:in `each'
     # ./lib/fpm/command.rb:625:in `load_options'
     # ./lib/fpm/command.rb:254:in `block in <class:Command>'
     # ./spec/fpm/command_spec.rb:198:in `block (5 levels) in <top (required)>'

  4) FPM::Command --fpm-options-file with multiple single-letter flags on a single line together should work
     Failure/Error: option = self.class.find_option(single_letter.match(1))

     NoMethodError:
       undefined method `match' for #<MatchData "-ffff" 1:"-f" 2:"fff">
     # ./lib/fpm/command.rb:639:in `block in load_options'
     # ./lib/fpm/command.rb:625:in `each'
     # ./lib/fpm/command.rb:625:in `load_options'
     # ./lib/fpm/command.rb:254:in `block in <class:Command>'
     # ./spec/fpm/command_spec.rb:210:in `block (5 levels) in <top (required)>'

  5) FPM::Package::CPAN should unpack tarball containing ./ leading paths FIXED
     Expected pending 'Disabled on travis-ci because it always fails, and there is no way to debug it?' to fail. No error was raised.
     # ./spec/fpm/package/cpan_spec.rb:41

  6) FPM::Package::Gem when :gem_shebang is nil/default should not change the shebang
     Failure/Error: insist { File.readlines(file_path).grep(/^#!\/usr\/bin\/env /).any? } == true

     Insist::Failure:
       Expected true, but got false
     # ./spec/fpm/package/gem_spec.rb:90:in `block (3 levels) in <top (required)>'

  7) FPM::Package#staging_path and #staging_path should be a subdirectory of workdir (#1124)
     Failure/Error: @build_path ||= Stud::Temporary.directory("package-#{type}-build")

     Errno::ENOENT:
       No such file or directory @ dir_s_mkdir - /var/tmp/package-package-build-9362f8404125e58b42179fea9eea9d5e78bdfd8169659b621b41234f86be
     # ./lib/fpm/package.rb:267:in `build_path'
     # ./lib/fpm/package.rb:182:in `initialize'
     # ./spec/fpm/package_spec.rb:208:in `block (3 levels) in <top (required)>'

  8) FPM::Package#staging_path and #staging_path should be a subdirectory of workdir (#1124)
     Failure/Error: @build_path ||= Stud::Temporary.directory("package-#{type}-build")

     Errno::ENOENT:
       No such file or directory @ dir_s_mkdir - /var/tmp/package-package-build-bc05145ee27d416835cbf1fc7de7cbbda453ab39eb3fa86810531ff0f9d2
     # ./lib/fpm/package.rb:267:in `build_path'
     # ./lib/fpm/package.rb:182:in `initialize'
     # ./spec/fpm/package_spec.rb:214:in `block (3 levels) in <top (required)>'

Finished in 18.07 seconds (files took 0.27302 seconds to load)
360 examples, 8 failures, 63 pending

Failed examples:

rspec ./spec/fpm/command_spec.rb:92 # FPM::Command -p | --package when given a directory should write the package to the given directory.
rspec ./spec/fpm/command_spec.rb:105 # FPM::Command -p | --package when not set should write the package to the current directory.
rspec ./spec/fpm/command_spec.rb:197 # FPM::Command --fpm-options-file with multiple single-letter flags on a single line separately should work
rspec ./spec/fpm/command_spec.rb:209 # FPM::Command --fpm-options-file with multiple single-letter flags on a single line together should work
rspec ./spec/fpm/package/cpan_spec.rb:41 # FPM::Package::CPAN should unpack tarball containing ./ leading paths
rspec ./spec/fpm/package/gem_spec.rb:87 # FPM::Package::Gem when :gem_shebang is nil/default should not change the shebang
rspec ./spec/fpm/package_spec.rb:207 # FPM::Package#staging_path and #staging_path should be a subdirectory of workdir (#1124)
rspec ./spec/fpm/package_spec.rb:213 # FPM::Package#staging_path and #staging_path should be a subdirectory of workdir (#1124)

error: in phase 'check': uncaught exception:
%exception #<&invoke-error program: "rspec" arguments: () exit-status: 1 term-signal: #f stop-signal: #f> 
phase `check' failed after 18.7 seconds
command "rspec" failed with status 1
```

**Comment by jordansissel** [comment]
> whne setting TRAVIS_OS_NAME to some value

I wouldn't recommend using that since fpm stopped using travis-ci a few years ago and the code for TRAVIS_OS_NAME and `is_travis` in the specs will be removed eventually

**Comment by jordansissel** [comment]
The Stud::Temporary failures are ... unexpected. Does your container environment not have a usable temporary path? The code for this is [here](https://github.com/jordansissel/ruby-stud/blob/19b1e34f75637c502b150ce203741ce7db1b9d12/lib/stud/temporary.rb#L11-L15) where it checks a bunch of environment variables before falling back to using "/tmp"

Given this, and your output, I assume one env var says to use "/var/tmp" and I can reproduce your exception if I point one of these variables to a place that does not exist:

```
% TMPDIR=/no-such-path ruby -rstud/temporary -e 'begin; Stud::Temporary.directory("example"); rescue => e; puts "Error: #{e}"; end'
Error: No such file or directory @ dir_s_mkdir - /no-such-path/example-85cddfe5cf082966f79d7f725497e6019c803aca8241b7300d28e9d2f025
```

The failure is in attempting to create a directory named "example-85cddfe5cf082966f79d7f725497e6019c803aca8241b7300d28e9d2f025" (generated by Stud::Temporary) within the path given by the `TMPDIR` env var (`/no-such-path`) and this fails as shown above.

**Comment by jordansissel** [comment]
>        undefined method `match' for #<MatchData "-ffff" 1:"-f" 2:"fff">

Odd. What version of ruby? I wonder if there's something that is different between my version tests and yours?

These tests work for me on ruby 3.2.0 - 

```
% bundle exec rspec -f d -e 'with multiple single-letter flags'
Run options: include {:full_description=>/with\ multiple\ single\-letter\ flags/}

FPM::Command
  --fpm-options-file
    with multiple single-letter flags on a single line
      separately
        should work
      together
        should work

Finished in 0.00234 seconds (files took 0.15766 seconds to load)
2 examples, 0 failures
```

**Comment by jordansissel** [comment]
>      SocketError:
>       Failed to open TCP connection to fastapi.metacpan.org:443 (getaddrinfo: Name or service not known)

The test suite currently assumes that internet connectivity is possible (for cpan, python, and probably other parts of the test suite). Disabling them might be ok, but there is not currently a list of "tests that require an internet connection", so a list for this might be the first step to making it possible to skip internet-necessary tests.

**Comment by Apteryks** [comment]
Hi! 

Thanks for looking into this. 

 `TMPDIR` is set to `"/tmp/guix-build-fpm-1.15.1.drv-0"`, which should be writable.   `HOME` though is set to `"/homeless-shelter"`, which isn't writable.  Setting `HOME` to a writable location, e.g. `"/tmp"`, doesn't reduce the failures count (10).

Ruby is at 2.7.4.

For the network-reliant tests, the list appears to be:

1. FPM::Package::CPAN should package Digest::MD5
2. FPM::Package::CPAN should package File::Spec
3. FPM::Package::CPAN should package Class::Data::Inheritable
4. FPM::Package::CPAN given a distribution without a META.* file should package IPC::Session

Which are all part of the CPAN test suite.
