### ISSUE TITLE
Python to deb conversion fails

### ISSUE THREAD

**Issue by me21** [jordansissel/fpm#2026]
I tried to convert Python package to deb but the process crashed. Here's the output:

```
debian@evolve-azarubkin:~/evolve_numpy$ fpm
Loading flags from rc file .fpm {:level=>:warn}
Additional options: -f -a armhf --python-bin python3 --verbose -s python -t deb -n evolve_numpy -v 1.21.4 {:level=>:warn}
Additional arguments: numpy {:level=>:warn}
Setting workdir {:workdir=>"/tmp", :level=>:info}
Trying to download {:package=>"numpy", :level=>:info}
Looking in indexes: https://pypi.python.org/simple, https://www.piwheels.org/simple {:level=>:info}
Collecting numpy==1.21.4 {:level=>:info}
  Using cached https://files.pythonhosted.org/packages/fb/48/b0708ebd7718a8933f0d3937513ef8ef2f4f04529f1f66ca86d873043921/numpy-1.21.4.zip {:level=>:info}
  Saved /tmp/package-python-build-6750e16279e2fd042de8fe1cf7aafaec4cf39922736acf6dfc52e8d2e2a9/numpy-1.21.4.zip {:level=>:info}
  Installing build dependencies: started {:level=>:info}
  Installing build dependencies: still running... {:level=>:info}
  Installing build dependencies: still running... {:level=>:info}
  Installing build dependencies: still running... {:level=>:info}
  Installing build dependencies: still running... {:level=>:info}
  Installing build dependencies: still running... {:level=>:info}
  Installing build dependencies: still running... {:level=>:info}
  Installing build dependencies: still running... {:level=>:info}
  Installing build dependencies: still running... {:level=>:info}
  Installing build dependencies: still running... {:level=>:info}
  Installing build dependencies: still running... {:level=>:info}
  Installing build dependencies: still running... {:level=>:info}
  Installing build dependencies: still running... {:level=>:info}
  Installing build dependencies: still running... {:level=>:info}
  Installing build dependencies: finished with status 'done' {:level=>:info}
Successfully downloaded numpy {:level=>:info}
Traceback (most recent call last):
        10: from /usr/local/bin/fpm:23:in `<main>'
         9: from /usr/local/bin/fpm:23:in `load'
         8: from /var/lib/gems/2.5.0/gems/fpm-1.15.1/bin/fpm:7:in `<top (required)>'
         7: from /var/lib/gems/2.5.0/gems/clamp-1.0.1/lib/clamp/command.rb:133:in `run'
         6: from /var/lib/gems/2.5.0/gems/fpm-1.15.1/lib/fpm/command.rb:591:in `run'
         5: from /var/lib/gems/2.5.0/gems/clamp-1.0.1/lib/clamp/command.rb:68:in `run'
         4: from /var/lib/gems/2.5.0/gems/fpm-1.15.1/lib/fpm/command.rb:367:in `execute'
         3: from /var/lib/gems/2.5.0/gems/fpm-1.15.1/lib/fpm/command.rb:367:in `each'
         2: from /var/lib/gems/2.5.0/gems/fpm-1.15.1/lib/fpm/command.rb:368:in `block in execute'
         1: from /var/lib/gems/2.5.0/gems/fpm-1.15.1/lib/fpm/package/python.rb:98:in `input'
/var/lib/gems/2.5.0/gems/fpm-1.15.1/lib/fpm/package/python.rb:177:in `download_if_necessary': Unexpected directory layout after `pip download ...`. This might be an fpm bug? The directory is /tmp/package-python-build-6750e16279e2fd042de8fe1cf7aafaec4cf39922736acf6dfc52e8d2e2a9 (RuntimeError)
```

Here's my .fpm file:
```
-f
-a armhf
--python-bin python3
--verbose
-s python
-t deb
-n evolve_numpy
-v 1.21.4
```

**Comment by me21** [comment]
The thing is a zip file is downloaded while the code expected .tar.gz.

**Comment by me21** [comment]
After applying a fix in `python.rb`:

```
      files = ::Dir.glob(File.join(build_path, "*.tar.gz"))
      if files.length != 1
        files = ::Dir.glob(File.join(build_path, "*.zip"))
        if files.length != 1
          raise "Unexpected directory layout after `pip download ...`. This might be an fpm bug? The direct$
        else
          safesystem("unzip", files[0], "-d", target)
        end
      else
        safesystem("tar", "-zxf", files[0], "-C", target)
      end
```

the archive extracts and fpm fails further:

```
fetching package metadata {:setup_cmd=>"env PYTHONPATH=/var/lib/gems/2.5.0/gems/fpm-1.15.1/lib/fpm/package:$PYTHONPATH python3 setup.py --command-packages=pyfpm get_metadata --output=/tmp/package-python-build-3ed2fb11ec8950b8ffe2244d76bc3ba2328fa1b6f9d5e68c4c73c2257c06/metadata.json", :level=>:info}
Running from numpy source directory. {:level=>:info}
Traceback (most recent call last): {:level=>:info}
  File "setup.py", line 448, in <module> {:level=>:info}
    setup_package() {:level=>:info}
  File "setup.py", line 421, in setup_package {:level=>:info}
    run_build = parse_setuppy_commands() {:level=>:info}
  File "setup.py", line 357, in parse_setuppy_commands {:level=>:info}
    raise RuntimeError("Unrecognized setuptools command: {}".format(args)) {:level=>:info}
RuntimeError: Unrecognized setuptools command: ['--command-packages=pyfpm', 'get_metadata', '--output=/tmp/package-python-build-3ed2fb11ec8950b8ffe2244d76bc3ba2328fa1b6f9d5e68c4c73c2257c06/metadata.json'] {:level=>:info}
Process failed: /bin/bash failed (exit code 1). Full command was:["/bin/bash", "-c", "env PYTHONPATH=/var/lib/gems/2.5.0/gems/fpm-1.15.1/lib/fpm/package:$PYTHONPATH python3 setup.py --command-packages=pyfpm get_metadata --output=/tmp/package-python-build-3ed2fb11ec8950b8ffe2244d76bc3ba2328fa1b6f9d5e68c4c73c2257c06/metadata.json"] {:level=>:error}
```

**Comment by me21** [comment]
Okay, this is because numpy's setup.py checks for the commands passed to it and doesn't recognize get_metadata and fails. This could be overridden by adding --force argument to that call (https://github.com/jordansissel/fpm/blob/b085edc49c8dd027db6ef3e32d8de531894a26ea/lib/fpm/package/python.rb#L234), but I don't know if it's going to influence other packages conversion.
