### ISSUE TITLE
could not find setup.py in installable package

### ISSUE THREAD

**Issue by gmabey** [jordansissel/fpm#2029]
I'm able to install this package in a regular pip environment https://github.com/markvincze/sabledocs

However, generating a .deb complains that the setup.py file is missing???
```
root@1576e366df8b:/# fpm -s python -t deb --python-bin python3 --python-package-name-prefix python3 --log info sabledocs
Setting workdir {:workdir=>"/tmp", :level=>:info}
Trying to download {:package=>"sabledocs", :level=>:info}
Looking in indexes: https://pypi.python.org/simple {:level=>:info}
Collecting sabledocs {:level=>:info}
  Using cached sabledocs-0.7.226.tar.gz (48 kB) {:level=>:info}
  Installing build dependencies: started {:level=>:info}
  Installing build dependencies: finished with status 'done' {:level=>:info}
  Getting requirements to build wheel: started {:level=>:info}
  Getting requirements to build wheel: finished with status 'done' {:level=>:info}
  Installing backend dependencies: started {:level=>:info}
  Installing backend dependencies: finished with status 'done' {:level=>:info}
  Preparing metadata (pyproject.toml): started {:level=>:info}
  Preparing metadata (pyproject.toml): finished with status 'done' {:level=>:info}
Saved /tmp/package-python-build-e5e505882550644aad47d90059e05db198eabb9b6a3087c36aa44a9355f2/sabledocs-0.7.226.tar.gz {:level=>:info}
Successfully downloaded sabledocs {:level=>:info}
Could not find 'setup.py' {:path=>"/tmp/package-python-build-e5e505882550644aad47d90059e05db198eabb9b6a3087c36aa44a9355f2/sabledocs/sabledocs-0.7.226/setup.py", :level=>:error}
/var/lib/gems/3.1.0/gems/fpm-1.15.1/lib/fpm/package/python.rb:108:in `input': Unable to find python package; tried /tmp/package-python-build-e5e505882550644aad47d90059e05db198eabb9b6a3087c36aa44a9355f2/sabledocs/sabledocs-0.7.226/setup.py (RuntimeError)
        from /var/lib/gems/3.1.0/gems/fpm-1.15.1/lib/fpm/command.rb:368:in `block in execute'
        from /var/lib/gems/3.1.0/gems/fpm-1.15.1/lib/fpm/command.rb:367:in `each'
        from /var/lib/gems/3.1.0/gems/fpm-1.15.1/lib/fpm/command.rb:367:in `execute'
        from /var/lib/gems/3.1.0/gems/clamp-1.0.1/lib/clamp/command.rb:68:in `run'
        from /var/lib/gems/3.1.0/gems/fpm-1.15.1/lib/fpm/command.rb:591:in `run'
        from /var/lib/gems/3.1.0/gems/clamp-1.0.1/lib/clamp/command.rb:133:in `run'
        from /var/lib/gems/3.1.0/gems/fpm-1.15.1/bin/fpm:7:in `<top (required)>'
        from /usr/local/bin/fpm:25:in `load'
        from /usr/local/bin/fpm:25:in `<main>'
```
I don't know enough about python packages to say how that can be ... is this an fpm bug or a sabledocs packaging error??

**Comment by amdei** [comment]
See #1982
Unfortunately the work is stale by lack of feedback/reviewers

**Comment by gmabey** [comment]
Yep understandable.

**Comment by gmabey** [comment]
Is this the same underlying issue as is addressed in #2040 ?

**Comment by amdei** [comment]
Issue seems to be the same.
Although in https://github.com/jordansissel/fpm/pull/1982 I made attempt to solve it via ```pip wheel```, not via ```build``` module from PyPA, as suggested in https://github.com/jordansissel/fpm/issues/2040.

**Comment by jordansissel** [comment]
Release https://github.com/jordansissel/fpm/releases/tag/v1.17.0 should address this issue. Let me know if you find otherwise :)
