### ISSUE TITLE
"--fpm-options-file" fails with "undefined method `extract_value' for nil:NilClass"

### ISSUE THREAD

**Issue by manero6** [jordansissel/fpm#2060]
Hi *

I want to create a `.deb` package out of a bin file.  
To achieve that I created a custom options file called `fpmdeb` (I also tested without newlines):

```bash
--maintainer "Me Myself <me@example.com>"
--architecture all

-s dir

--name blabla-github-yq
--license mit
--description "yq is a portable command-line YAML, JSON, XML, CSV, TOML and properties processor"
--url "https://github.com/mikefarah/yq"

yq_linux_amd64=/usr/bin/yq
```

And run `fpm` as follows:

```bash
fpm -t deb --version 4.43.1 --fpm-options-file fpmdeb
```

Unfortunately I end up getting this error:

```bash
Loading flags from file {:path=>"fpmdeb", :level=>:info}
Processing flags from file {:path=>"fpmdeb", :line=>"--maintainer \"Me Myself <me@example.com>\"", :level=>:info}
Processing flags from file {:path=>"fpmdeb", :line=>"--architecture all", :level=>:info}
Processing flags from file {:path=>"fpmdeb", :line=>"", :level=>:info}
Processing flags from file {:path=>"fpmdeb", :line=>"-s dir", :level=>:info}
Processing flags from file {:path=>"fpmdeb", :line=>"", :level=>:info}
Processing flags from file {:path=>"fpmdeb", :line=>"--name blabla-github-yq", :level=>:info}
Processing flags from file {:path=>"fpmdeb", :line=>"--license mit", :level=>:info}
Processing flags from file {:path=>"fpmdeb", :line=>"--description \"yq is a portable command-line YAML, JSON, XML, CSV, TOML and properties processor\"", :level=>:info}
Processing flags from file {:path=>"fpmdeb", :line=>"--url \"https://github.com/mikefarah/yq\"", :level=>:info}
Processing flags from file {:path=>"fpmdeb", :line=>"", :level=>:info}
Processing flags from file {:path=>"fpmdeb", :line=>"yq_linux_amd64=/usr/bin/yq", :level=>:info}
/var/lib/gems/3.0.0/gems/fpm-1.15.1/lib/fpm/command.rb:662:in `block in load_options': undefined method `extract_value' for nil:NilClass (NoMethodError)
        from /var/lib/gems/3.0.0/gems/fpm-1.15.1/lib/fpm/command.rb:625:in `each'
        from /var/lib/gems/3.0.0/gems/fpm-1.15.1/lib/fpm/command.rb:625:in `load_options'
        from /var/lib/gems/3.0.0/gems/fpm-1.15.1/lib/fpm/command.rb:254:in `block in <class:Command>'
        from /var/lib/gems/3.0.0/gems/clamp-1.0.1/lib/clamp/attribute/declaration.rb:33:in `instance_exec'
        from /var/lib/gems/3.0.0/gems/clamp-1.0.1/lib/clamp/attribute/declaration.rb:33:in `block in define_simple_writer_for'
        from /var/lib/gems/3.0.0/gems/clamp-1.0.1/lib/clamp/attribute/instance.rb:59:in `take'
        from /var/lib/gems/3.0.0/gems/clamp-1.0.1/lib/clamp/option/parsing.rb:32:in `parse_options'
        from /var/lib/gems/3.0.0/gems/clamp-1.0.1/lib/clamp/command.rb:53:in `parse'
        from /var/lib/gems/3.0.0/gems/clamp-1.0.1/lib/clamp/command.rb:67:in `run'
        from /var/lib/gems/3.0.0/gems/fpm-1.15.1/lib/fpm/command.rb:591:in `run'
        from /var/lib/gems/3.0.0/gems/clamp-1.0.1/lib/clamp/command.rb:133:in `run'
        from /var/lib/gems/3.0.0/gems/fpm-1.15.1/bin/fpm:7:in `<top (required)>'
        from /usr/local/bin/fpm:25:in `load'
        from /usr/local/bin/fpm:25:in `<main>'
```

But if I rename `fpmdeb` to `.fpm` and run `fpm` as follows:

```bash
fpm -t deb --version 4.43.1
```

then everything works as expected and I get the desired `.deb` package.

However, with this config file `fpmdeb`:

```bash
--maintainer "Me Myself <me@example.com>"
--architecture all

-s dir

--name blabla-github-yq
--license mit
--description "yq is a portable command-line YAML, JSON, XML, CSV, TOML and properties processor"
--url "https://github.com/mikefarah/yq"
```

And running `fpm` this way:

```bash
fpm -t deb --version 4.43.1 --fpm-options-file fpmdeb yq_linux_amd64=/usr/bin/yq
```

I am able to create a `.deb` package using `--fpm-options-file `!

Am I doing something wrong?

Thanks :)

**Comment by jpiron** [comment]
I have the same error when I try to use a `fpm-options-file` that is located in a subfolder.

Moving the options file to the project root folder solved the issue.

**Comment by sakkyoi** [comment]
fpm-options-file can only handle flag-based options such as:
```
--maintainer "Me Myself <me@example.com>"
--architecture all

-s dir
-t deb

--name blabla-github-yq
--license mit
--description "yq is a portable command-line YAML, JSON, XML, CSV, TOML and properties processor"
--url "https://github.com/mikefarah/yq"
```

you can simply create a file like `fpm-files.txt`
```
yq_linux_amd64=/usr/bin/yq
```

and 

```bash
fpm \
    --version 4.43.1 \
    --fpm-options-file fpmdeb \
    $(cat fpm-files.txt)
```

**Comment by hertznsk** [comment]
According to the example https://fpm.readthedocs.io/en/v1.17.0/getting-started.html#configuration-file additional arguments such as `hello-world=/usr/bin/hello-world hello-world.1=/usr/share/man/man1/hello-world.1` are working successfully in `.fpm`.
But only if you don't use the `--fpm-options-file` option in the shell.

That is, if you make a call in this example: `fpm -t deb -p hello-world-0.1.0-1-any.deb --fpm-options-file .fpm` we will get the same error

This is a defect.

I temporarily bypassed it as follows:

1. `xargs -a .fpm fpm -t deb -p hello-world-0.1.0-1-any.deb`

2.  `eval "fpm -t deb -p hello-world-0.1.0-1-any.deb $(paste -s -d ' ' .fpm)"`which, for security reasons, is not a good solution, but why not if you have full control over the contents of `.fpm`.

**Comment by jordansissel** [comment]
I agree this behavior sounds like a bug
