### ISSUE TITLE
fpm fails under ruby 1.8.5 (missing Object#instance_variable_defined?)

### ISSUE THREAD

**Issue by jordansissel** [jordansissel/fpm#214]
Looks like the backports gem doesn't define Object#instance_variable_defined?

The following is from ruby 1.8.5

```
# fpm
/usr/lib/ruby/gems/1.8/gems/clamp-0.3.1/lib/clamp/attribute_declaration.rb:15:in `input_type': undefined method `instance_variable_defined?' for #<FPM::Command:0xb7e77914> (NoMethodError)
        from /usr/lib/ruby/gems/1.8/gems/fpm-0.4.9/lib/fpm/command.rb:190:in `execute'
        from /usr/lib/ruby/gems/1.8/gems/clamp-0.3.1/lib/clamp/command.rb:64:in `run'
        from /usr/lib/ruby/gems/1.8/gems/cl amp-0.3.1/lib/clamp/command.rb:126:in `run'
        from /usr/lib/ruby/gems/1.8/gems/fpm-0.4.9/bin/fpm:8
        from /usr/bin/fpm:19:in `load'
        from /usr/bin/fpm:19
```

**Comment by jordansissel** [comment]
Last time I tried to fix this on CentOS 5 / Ruby 1.8.5, Ruby kept segfaulting due to bugs. I don't think there's anything to do here given Ruby 1.8.5 crashes so much.
