### ISSUE TITLE
Failed to build gem native extension.

### ISSUE THREAD

**Issue by scribu** [jordansissel/fpm#282]
Hello,

Tried to run `sudo gem install fpm` on Ubuntu 12.10 and this is what I got:

```
Building native extensions.  This could take a while...
ERROR:  Error installing fpm:
    ERROR: Failed to build gem native extension.

        /usr/bin/ruby1.9.1 extconf.rb
/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require': cannot load such file -- mkmf (LoadError)
    from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from extconf.rb:1:in `<main>'
```

Any suggestions?

**Comment by sk33lz** [comment]
Just leaving a note here for those who may stumble upon the same issue I ended up here with. 

I just had to install `libffi-dev` on a docker container running `openjdk:8-jre` as the base image to get fpm to install with gem due to similar issues as stevebanik.

```
ERROR:  Error installing fpm:
	ERROR: Failed to build gem native extension.

    current directory: /var/lib/gems/2.3.0/gems/ffi-1.9.21/ext/ffi_c
/usr/bin/ruby2.3 -r ./siteconf20180206-5-2e8779.rb extconf.rb
checking for ffi.h... no
```
