### ISSUE TITLE
Generating puppet manifest failed

### ISSUE THREAD

**Issue by Finchster** [jordansissel/fpm#346]
Tried to generate a puppet manifest with the below command on a rpm created by FPM -

fpm -s rpm -t puppet --verbose --debug rpm-1.0-1.x86_64.rpm

Error:

Setting attribute {"file":"fpm/command.rb","method":"execute","rpm_sign?":null,"line":"307","level":"debug"}
/usr/lib64/ruby/gems/1.8/gems/fpm-0.4.26/lib/fpm/package/rpm.rb:190:in `input': undefined method`directories' for #RPM::File:0x2b0d4b9d06d8 (NoMethodError)
        from /usr/lib64/ruby/gems/1.8/gems/fpm-0.4.26/lib/fpm/command.rb:316:in `execute'
        from /usr/lib64/ruby/gems/1.8/gems/fpm-0.4.26/lib/fpm/command.rb:315:in`each'
        from /usr/lib64/ruby/gems/1.8/gems/fpm-0.4.26/lib/fpm/command.rb:315:in `execute'
        from /usr/lib64/ruby/gems/1.8/gems/clamp-0.3.1/lib/clamp/command.rb:64:in`run'
        from /usr/lib64/ruby/gems/1.8/gems/clamp-0.3.1/lib/clamp/command.rb:126:in `run'
        from /usr/lib64/ruby/gems/1.8/gems/fpm-0.4.26/bin/fpm:8
        from /usr/bin/fpm:19:in`load'
        from /usr/bin/fpm:19

**Comment by nicobrevin** [comment]
Is there still interest in this feature?  And am I right in saying that it used to build a puppet manifest/module from a package?

**Comment by jordansissel** [comment]
Yeah this feature was an experiment to do what you said - create a puppet
manifest (and files) for from a package.
