### ISSUE TITLE
Building python module as rpm

### ISSUE THREAD

**Issue by project-linux-proj** [jordansissel/fpm#529]
I  have two python 2.6 and 2.7.5 , python 2.6 has binary /usr/bin/python and python 2.7.5 has binary /usr/local/bin/python. when i tried to build the pkg using command ¨fpm -s python -t rpm --python-bin /usr/bin/python2  nose¨  it worked for python 2.6 .

but if i tried the command ¨fpm -s python -t rpm --python-bin /usr/local/bin/python2  nose¨ it didnt. Below is the error.

[root@test1_64 bin]# fpm -s python -t rpm --python-bin /usr/local/bin/python  nose
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: invalid command 'get_metadata'
setup.py get_metadata failed {:command=>"env PYTHONPATH=/usr/local/lib/ruby/gems/1.9.1/gems/fpm-0.4.42/lib/fpm/package /usr/local/bin/python setup.py --command-packages=pyfpm get_metadata", :exitcode=>1, :level=>:error}
/usr/local/lib/ruby/gems/1.9.1/gems/fpm-0.4.42/lib/fpm/package/python.rb:167:in `block in load_package_info': An unexpected error occurred while processing the setup.py file (RuntimeError)
        from /usr/local/lib/ruby/gems/1.9.1/gems/fpm-0.4.42/lib/fpm/package/python.rb:150:in`chdir'
        from /usr/local/lib/ruby/gems/1.9.1/gems/fpm-0.4.42/lib/fpm/package/python.rb:150:in `load_package_info'
        from /usr/local/lib/ruby/gems/1.9.1/gems/fpm-0.4.42/lib/fpm/package/python.rb:90:in`input'
        from /usr/local/lib/ruby/gems/1.9.1/gems/fpm-0.4.42/lib/fpm/command.rb:294:in `block in execute'
        from /usr/local/lib/ruby/gems/1.9.1/gems/fpm-0.4.42/lib/fpm/command.rb:293:in`each'
        from /usr/local/lib/ruby/gems/1.9.1/gems/fpm-0.4.42/lib/fpm/command.rb:293:in `execute'
        from /usr/local/lib/ruby/gems/1.9.1/gems/clamp-0.6.1/lib/clamp/command.rb:67:in`run'
        from /usr/local/lib/ruby/gems/1.9.1/gems/clamp-0.6.1/lib/clamp/command.rb:125:in `run'
        from /usr/local/lib/ruby/gems/1.9.1/gems/fpm-0.4.42/bin/fpm:8:in`<top (required)>'
        from /usr/local/bin/fpm:19:in `load'
        from /usr/local/bin/fpm:19:in`<main>'

**Comment by rapen** [comment]
hi,
same problem here
ubuntu 14.04 with python2.7 & python2.6, trying to convert scipy into rpm(numpy is prereq for scipy and is already installed). Running pip2.6 install  'scipy==0.8.0' gives no errors

fpm -s python -t rpm --python-package-name-prefix python2.6 --verbose --debug --python-easyinstall nil  --python-bin /usr/bin/python2.6 --python-pip pip2.6 'scipy==0.8.0'


Successfully downloaded scipy {:level=>:info, :file=>"cabin/mixins/pipe.rb", :line=>"47", :method=>"block in pipe"}
Running command {:args=>["/bin/bash", "-c", "/usr/bin/python2.6 -c 'try:\n  import json\nexcept ImportError:\n  import simplejson as json'"], :level=>:debug, :file=>"fpm/util.rb", :line=>"59", :method=>"safesystem"}
Process is running {:pid=>1254, :level=>:debug, :file=>"fpm/util.rb", :line=>"72", :method=>"safesystem"}
Running command {:args=>["/bin/bash", "-c", "/usr/bin/python2.6 -c 'import pkg_resources'"], :level=>:debug, :file=>"fpm/util.rb", :line=>"59", :method=>"safesystem"}
Process is running {:pid=>1257, :level=>:debug, :file=>"fpm/util.rb", :line=>"72", :method=>"safesystem"}
fetching package metadata {:setup_cmd=>"env PYTHONPATH=/var/lib/gems/1.9.1/gems/fpm-1.3.3/lib/fpm/package /usr/bin/python2.6 setup.py --command-packages=pyfpm get_metadata --output=/tmp/package-python-build20150127-1238-13go0h2/metadata.json", :level=>:info, :file=>"fpm/package/python.rb", :line=>"187", :method=>"block in load_package_info"}
Running command {:args=>["/bin/bash", "-c", "env PYTHONPATH=/var/lib/gems/1.9.1/gems/fpm-1.3.3/lib/fpm/package /usr/bin/python2.6 setup.py --command-packages=pyfpm get_metadata --output=/tmp/package-python-build20150127-1238-13go0h2/metadata.json"], :level=>:debug, :file=>"fpm/util.rb", :line=>"59", :method=>"safesystem"}
Process is running {:pid=>1260, :level=>:debug, :file=>"fpm/util.rb", :line=>"72", :method=>"safesystem"}
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...] {:level=>:info, :file=>"cabin/mixins/pipe.rb", :line=>"47", :method=>"block in pipe"}
   or: setup.py --help [cmd1 cmd2 ...] {:level=>:info, :file=>"cabin/mixins/pipe.rb", :line=>"47", :method=>"block in pipe"}
   or: setup.py --help-commands {:level=>:info, :file=>"cabin/mixins/pipe.rb", :line=>"47", :method=>"block in pipe"}
   or: setup.py cmd --help {:level=>:info, :file=>"cabin/mixins/pipe.rb", :line=>"47", :method=>"block in pipe"}
 {:level=>:info, :file=>"cabin/mixins/pipe.rb", :line=>"47", :method=>"block in pipe"}
error: invalid command 'get_metadata' {:level=>:info, :file=>"cabin/mixins/pipe.rb", :line=>"47", :method=>"block in pipe"}

trying it manually gives same error
root@tk-dev:/tmp/package-python-build20150127-1238-13go0h2/scipy==0.8.0/scipy# env PYTHONPATH=/var/lib/gems/1.9.1/gems/fpm-1.3.3/lib/fpm/package /usr/bin/python2.6 setup.py --command-packages=pyfpm get_metadata --output=/tmp/package-python-build20150127-1238-13go0h2/metadata.json
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

**Comment by rapen** [comment]
the real problem is with setup.py of scipy(numpy has it's own distutils....)
from setup.py of scipy:
def setup_package():

    from numpy.distutils.core import setup
    from numpy.distutils.misc_util import Configuration

    old_path = os.getcwd()
    local_path = os.path.dirname(os.path.abspath(sys.argv[0]))


the hack that might help to somebody is to enter temp directory(to where fpm downloaded package) and to change setup.py of scipy to have fpm get_metadata inside
cat /var/lib/gems/1.9.1/gems/fpm-1.3.3/lib/fpm/package/pyfpm/get_metadata.py >> setup.py
afterwards you should move main of setup.py and change 
from distutils.core import Command -->
from numpy.distutils.core import Command
