### ISSUE TITLE
Incorrect "File exists" message when building.

### ISSUE THREAD

**Issue by frozenfoxx** [jordansissel/fpm#586]
When attempting to build a package from files I incorrectly get a "file exists" message when the listed-directory doesn't exist:

```
 frozenfoxx@machine:~/transfer/redis-2.6.16$ fpm -s dir -t deb -n redis --config-files /etc/redis/redis.conf -v 2.6.16 ./src/redis-server=/usr/bin redis.conf=/etc/redis/redis.conf ./src/redis-cli=/usr/bin/redis-cli ./src/redis-benchmark=/usr/bin/redis-benchmark ./src/redis-sentinel=/usr/bin/redis-sentinel ./src/redis-check-aof=/usr/bin/redis-check-aof ./src/redis-check-dump=/usr/bin/redis-check-dump
 /usr/lib/ruby/1.9.1/fileutils.rb:247:in `mkdir': File exists - /tmp/package-dir-staging20131114-10360-1oqbkys/usr/bin (Errno::EEXIST)
        from /usr/lib/ruby/1.9.1/fileutils.rb:247:in `fu_mkdir'
        from /usr/lib/ruby/1.9.1/fileutils.rb:221:in `block (2 levels) in mkdir_p'
        from /usr/lib/ruby/1.9.1/fileutils.rb:219:in `reverse_each'
        from /usr/lib/ruby/1.9.1/fileutils.rb:219:in `block in mkdir_p'
        from /usr/lib/ruby/1.9.1/fileutils.rb:205:in `each'
        from /usr/lib/ruby/1.9.1/fileutils.rb:205:in `mkdir_p'
        from /var/lib/gems/1.9.1/gems/fpm-0.4.42/lib/fpm/package/dir.rb:132:in `copy'
        from /var/lib/gems/1.9.1/gems/fpm-0.4.42/lib/fpm/package/dir.rb:113:in `clone'
        from /var/lib/gems/1.9.1/gems/fpm-0.4.42/lib/fpm/package/dir.rb:67:in `block in input'
        from /var/lib/gems/1.9.1/gems/fpm-0.4.42/lib/fpm/package/dir.rb:66:in `chdir'
        from /var/lib/gems/1.9.1/gems/fpm-0.4.42/lib/fpm/package/dir.rb:66:in `input'
        from /var/lib/gems/1.9.1/gems/fpm-0.4.42/lib/fpm/command.rb:294:in `block in execute'
        from /var/lib/gems/1.9.1/gems/fpm-0.4.42/lib/fpm/command.rb:293:in `each'
        from /var/lib/gems/1.9.1/gems/fpm-0.4.42/lib/fpm/command.rb:293:in `execute'
        from /var/lib/gems/1.9.1/gems/clamp-0.6.3/lib/clamp/command.rb:67:in `run'
        from /var/lib/gems/1.9.1/gems/clamp-0.6.3/lib/clamp/command.rb:125:in `run'
        from /var/lib/gems/1.9.1/gems/fpm-0.4.42/bin/fpm:8:in `<top (required)>'
        from /usr/local/bin/fpm:23:in `load'
        from /usr/local/bin/fpm:23:in `<main>'
```

**Comment by jordansissel** [comment]
ahh I found the bug, hilarious.

**Comment by jordansissel** [comment]
```
Copying path {:source=>"redis-cli", :destination=>"/var/folders/4r/4fpyt_2d1qvfrgb2fnngrqm40000gn/T/package-dir-staging20150225-60212-cwhydu/usr/bin/redis-cli", :level=>:debug, :file=>"fpm/package/dir.rb", :line=>"158", :method=>"copy", "method"=>"input"}
Creating directory {:path=>"/var/folders/4r/4fpyt_2d1qvfrgb2fnngrqm40000gn/T/package-dir-staging20150225-60212-cwhydu/usr/bin", :level=>:debug, :file=>"fpm/package/dir.rb", :line=>"161", :method=>"copy", "method"=>"input"}
/Users/jls/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/fileutils.rb:250:in `mkdir': File exists @ dir_s_mkdir - /var/folders/4r/4fpyt_2d1qvfrgb2fnngrqm40000gn/T/package-dir-staging20150225-60212-cwhydu/usr/bin (Errno::EEXIST)
```

It says this .../usr/bin isn't a directory, so it tries to create it, but it's not a directory, it's a file.

```
% ls -ld /var/folders/4r/4fpyt_2d1qvfrgb2fnngrqm40000gn/T/package-dir-staging20150225-60212-cwhydu/usr/bin
-rwxr-xr-x  4 jls  staff  806520 Jan 27 09:52 /var/folders/4r/4fpyt_2d1qvfrgb2fnngrqm40000gn/T/package-dir-staging20150225-60212-cwhydu/usr/bin*
```

computers...

**Comment by jordansissel** [comment]
ok, so the problem is "technically" user error, but the error message you get is terrible.

The problem is that, at least in fpm's view, the dir mapping `./src/redis-server=/usr/bin` says to copy the file "redis-server" and put it in /usr as a file named "bin" so you end up with "/usr/bin" as a file that is the redis-server binary. Oops.

The fix is to add a trailing /:
`./src/redis-server=/usr/bin/`

I've tried to follow rsync's behavior with respect to source/destination copies, and rsync does this also:

```
% mkdir -p /tmp/usr/
% rsync src/redis-server /tmp/usr/bin
% ls -ld /tmp/usr/bin
-rwxr-xr-x  1 jls  wheel  806520 Feb 25 23:03 /tmp/usr/bin*
```

On the other hand, this behavior is ... surprising ... to say the least, even if we can explain the reasons behind it. I'm not sure what exactly to do about it.

**Comment by jordansissel** [comment]
The new error you get is:

```
You wanted to copy a file into a directory, but that's not a directory, it's a file! {:path=>"/usr/bin", :stat=>#<File::Stat dev=0x1000004, ino=16909471, mode=0100755, nlink=10, uid=501, gid=20, rdev=0x0, size=806520, blksize=4096, blocks=1576, atime=2015-02-25 23:03:49 -0800, mtime=2015-01-27 09:52:57 -0800, ctime=2015-02-25 23:05:56 -0800>, :level=>:error, :file=>"fpm/package/dir.rb", :line=>"169", :method=>"copy", "method"=>"input"}
Invalid package configuration: Tried to treat /usr/bin like a directory, but it's a file! {:level=>:error, :file=>"fpm/command.rb", :line=>"465", :method=>"rescue in execute"}
```

**Comment by jordansissel** [comment]
We could also add improvement to scan the things being copied and see if there are any obvious duplicates, and if so, treat it like a directory? I dunno.

`fpm -s dir -t deb ... foo=/usr/bin bar=/usr/bin` - would imply /usr/bin is a directory? Might be surprising in the single-arg case where alone, `foo=/usr/bin` creates a file called /usr/bin

**Comment by jordansissel** [comment]
Thoughts?
