### ISSUE TITLE
Packaging using output as RPM and a input of a directory with -C switch fails but was working in a previous FPM release.

### ISSUE THREAD

**Issue by loque1** [jordansissel/fpm#629]
the following fpm make file was working in a previous version of fpm

appname=tomcat
fpm  \
--config-files /etc/init.d/${appname} \
--config-files /etc/logrotate.d/${appname} \
--config-files /etc/default/locale \
--config-files /etc/default/${appname} \
--config-files /etc/${appname}/catalina.properties \
--config-files /etc/${appname}/policy.d/02debian.policy \
--config-files /etc/${appname}/policy.d/03catalina.policy \
--config-files /etc/${appname}/policy.d/04webapps.policy \
--config-files /etc/${appname}/policy.d/50local.policy \
--config-files /etc/${appname}/policy.d/01system.policy \
--config-files /etc/${appname}/logback.d/01logback_header.xml \
--config-files /etc/${appname}/logback.d/02logback_variables.xml \
--config-files /etc/${appname}/logback.d/03logback_appenders.xml \
--config-files /etc/${appname}/logback.d/97logback_logger.xml \
--config-files /etc/${appname}/logback.d/98logback_root.xml \
--config-files /etc/${appname}/logback.d/99logback_footer.xml \
--config-files /etc/${appname}/app_conf/logback_base.properties \
--config-files /etc/${appname}/server.xml \
--config-files /etc/${appname}/context.xml \
--config-files /etc/${appname}/web.xml \
--config-files /etc/${appname}/tomcat-users.xml \
--config-files /etc/${appname}/jmx.access \
--config-files /etc/${appname}/jmx.passwd \
--config-files /etc/${appname}/app_conf/logging/logback-access.xml \
--category "Appserver/Java" \
--provides "apache-tomcat-7.0.42 Container With Logback" \
--vendor "Orbit Operations" \
-n tomcat-logback-full -v 1.0 -d "java-1.7.0-openjdk-devel"  -a all -C tomcat_packaging -a x86_64 -m "Orbit System Group" -t rpm -s dir \
--before-install ./packaging_scripts/tomcat.preinstall.sh  --after-install ./packaging_scripts/tomcat.postinstall.sh \
--before-remove ./packaging_scripts/tomcat.preuninstall.sh --after-remove ./packaging_scripts/tomcat.postuninstall.sh \
--description "Apache Tomcat v7.0.42 Container Using Logback" --debug ./

but now fails in FPM 1.0.2

But when the --config-files line is removed it works as expected ? and produces the file with --config-files  line in the following is output

no value for epoch is set, defaulting to nil {:level=>:warn}
/usr/lib/ruby/1.9.1/find.rb:38:in `block in find': No such file or directory (Errno::ENOENT)
    from /usr/lib/ruby/1.9.1/find.rb:38:in`collect!'
    from /usr/lib/ruby/1.9.1/find.rb:38:in `find'
    from /var/lib/gems/1.9.1/gems/fpm-1.0.2/lib/fpm/package/rpm.rb:352:in`block in output'
    from /var/lib/gems/1.9.1/gems/fpm-1.0.2/lib/fpm/package/rpm.rb:350:in `each'
    from /var/lib/gems/1.9.1/gems/fpm-1.0.2/lib/fpm/package/rpm.rb:350:in`output'
    from /var/lib/gems/1.9.1/gems/fpm-1.0.2/lib/fpm/command.rb:389:in `execute'
    from /var/lib/gems/1.9.1/gems/clamp-0.6.3/lib/clamp/command.rb:67:in`run'
    from /var/lib/gems/1.9.1/gems/fpm-1.0.2/lib/fpm/command.rb:440:in `run'
    from /var/lib/gems/1.9.1/gems/clamp-0.6.3/lib/clamp/command.rb:125:in`run'
    from /var/lib/gems/1.9.1/gems/fpm-1.0.2/bin/fpm:8:in `<top (required)>'
    from /usr/local/bin/fpm:23:in`load'
    from /usr/local/bin/fpm:23:in `<main>'

**Comment by loque1** [comment]
Closing issue as no useful update
