### ISSUE TITLE
unable to build python module rpm using pip

### ISSUE THREAD

**Issue by mnikhil-git** [jordansissel/fpm#670]
Hi,

I am facing this problem while building the python module to be rpm packaged. Easy install command went through though. Any help is appreciated.

thanks,
Nikhil

 /usr/lib64/ruby/gems/1.8/gems/fpm-1.0.2/bin/fpm -s python --python-pip=/opt/python2.7/bin/pip-2.7 --python-bin=/opt/python2.7/bin/python -t rpm --python-package-name-prefix python27 -v 3.2.2 'cherrypy' --verbose
All flags should be before the first argument (stray flags found: --verbose {:level=>:warn}
/usr/lib64/ruby/gems/1.8/gems/fpm-1.0.2/bin/../lib/fpm/package/python.rb:132:in `download_if_necessary': Unexpected directory layout after easy_install. Maybe file a bug? The directory is /tmp/package-python-build20140404-24804-1c3i5uu (RuntimeError)
        from /usr/lib64/ruby/gems/1.8/gems/fpm-1.0.2/bin/../lib/fpm/package/python.rb:77:in`input'
        from /usr/lib64/ruby/gems/1.8/gems/fpm-1.0.2/bin/../lib/fpm/command.rb:292:in `execute'
        from /usr/lib64/ruby/gems/1.8/gems/fpm-1.0.2/bin/../lib/fpm/command.rb:291:in`each'
        from /usr/lib64/ruby/gems/1.8/gems/fpm-1.0.2/bin/../lib/fpm/command.rb:291:in `execute'
        from /usr/lib64/ruby/gems/1.8/gems/clamp-0.6.0/lib/clamp/command.rb:69:in`run'
        from /usr/lib64/ruby/gems/1.8/gems/fpm-1.0.2/bin/../lib/fpm/command.rb:440:in `run'
        from /usr/lib64/ruby/gems/1.8/gems/clamp-0.6.0/lib/clamp/command.rb:127:in`run'
        from /usr/lib64/ruby/gems/1.8/gems/fpm-1.0.2/bin/fpm:8

**Comment by stieg** [comment]
Facing the same issue on my CentOS 7 environment.  Output as follows:

```
fpm -s python -t rpm --maintainer 'AutosportLabs' --iteration '1.el7' --python-pip $(which pip) collectd
/usr/local/share/gems/gems/fpm-1.3.3/lib/fpm/package/python.rb:137:in `download_if_necessary': Unexpected directory layout after easy_install. Maybe file a bug? The directory is /tmp/package-python-build20150216-11734-1d7m4sr (RuntimeError)
        from /usr/local/share/gems/gems/fpm-1.3.3/lib/fpm/package/python.rb:83:in `input'
        from /usr/local/share/gems/gems/fpm-1.3.3/lib/fpm/command.rb:332:in `block in execute'
        from /usr/local/share/gems/gems/fpm-1.3.3/lib/fpm/command.rb:331:in `each'
        from /usr/local/share/gems/gems/fpm-1.3.3/lib/fpm/command.rb:331:in `execute'
        from /usr/local/share/gems/gems/clamp-0.6.3/lib/clamp/command.rb:67:in `run'
        from /usr/local/share/gems/gems/fpm-1.3.3/lib/fpm/command.rb:510:in `run'
        from /usr/local/share/gems/gems/clamp-0.6.3/lib/clamp/command.rb:125:in `run'
        from /usr/local/share/gems/gems/fpm-1.3.3/bin/fpm:8:in `<top (required)>'
        from /usr/local/bin/fpm:23:in `load'
        from /usr/local/bin/fpm:23:in `<main>'
```

I found this out because I am having an SSL failure with easy_install.  Examples follow:

```
[vagrant@dev-vagrant-stieg ~]$ fpm -s python -t rpm --maintainer 'AutosportLabs' --iteration '1.el7' --python-pip $(which pip) collectd
/usr/local/share/gems/gems/fpm-1.3.3/lib/fpm/package/python.rb:137:in `download_if_necessary': Unexpected directory layout after easy_install. Maybe file a bug? The directory is /tmp/package-python-build20150216-11734-1d7m4sr (RuntimeError)
        from /usr/local/share/gems/gems/fpm-1.3.3/lib/fpm/package/python.rb:83:in `input'
        from /usr/local/share/gems/gems/fpm-1.3.3/lib/fpm/command.rb:332:in `block in execute'
        from /usr/local/share/gems/gems/fpm-1.3.3/lib/fpm/command.rb:331:in `each'
        from /usr/local/share/gems/gems/fpm-1.3.3/lib/fpm/command.rb:331:in `execute'
        from /usr/local/share/gems/gems/clamp-0.6.3/lib/clamp/command.rb:67:in `run'
        from /usr/local/share/gems/gems/fpm-1.3.3/lib/fpm/command.rb:510:in `run'
        from /usr/local/share/gems/gems/clamp-0.6.3/lib/clamp/command.rb:125:in `run'
        from /usr/local/share/gems/gems/fpm-1.3.3/bin/fpm:8:in `<top (required)>'
        from /usr/local/bin/fpm:23:in `load'
        from /usr/local/bin/fpm:23:in `<main>'
[vagrant@dev-vagrant-stieg ~]$ fpm -s python -t rpm --maintainer 'AutosportLabs' --iteration '1.el7' collectd
Process failed: easy_install failed (exit code 1). Full command was:["easy_install", "-i", "http://pypi.python.org/simple", "--editable", "-U", "--build-directory", "/tmp/package-python-build20150216-11773-1jiwipu/collectd", "collectd"] {:level=>:error}
[vagrant@dev-vagrant-stieg ~]$ easy_install -i http://pypi.python.org/simple --editable -U --build-directory /tmp collectd
Searching for collectd
Reading http://pypi.python.org/simple/collectd/
Best match: collectd 1.0.2
Downloading https://github.com/downloads/appliedsec/collectd/collectd-1.0.2.tar.gz
error: Download error for https://github.com/downloads/appliedsec/collectd/collectd-1.0.2.tar.gz: [Errno 1] _ssl.c:504: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure
```

The easy_install failure is likely related to SSI in openssl and not related to this.  But regardless the inability to use both easy_install and pip is the suck.  Any help would be most appreciated.
