### ISSUE TITLE
--config-files in conflict with --prefix option

### ISSUE THREAD

**Issue by vazic** [jordansissel/fpm#730]
$mkdir test;cd test
$echo '1' > default
$fpm -s dir -t rpm  \
  --name "TEST" -v "1" \
  --iteration 1 --epoch 1 \
  --license "PRIVATE" --vendor "TEST" --architecture "noarch" \
  --config-files "default" \
  --prefix "/opt" \
  "./"

/home/vaz/.rvm/rubies/ruby-1.9.3-p545/lib/ruby/1.9.1/find.rb:38:in `block in find': No such file or directory (Errno::ENOENT)

CentOS 5

example works fine either without `--prefix` or `--config-files` options

**Comment by zoresvit** [comment]
The same issue happens with `dir` source when specifying destination directories. So command 

```
fpm -s dir -t deb -n redis --config-files /etc/redis/redis.conf -v 2.6.10 --prefix /opt ./src/redis-server=/usr/bin redis.conf=/etc/redis
```
fails with error:

```
/usr/share/ruby/find.rb:40:in `block in find': No such file or directory (Errno::ENOENT)
        from /usr/share/ruby/find.rb:40:in `collect!'
        from /usr/share/ruby/find.rb:40:in `find'
        from /usr/local/share/gems/gems/fpm-1.4.0/lib/fpm/package/rpm.rb:447:in `block in output'
        from /usr/local/share/gems/gems/fpm-1.4.0/lib/fpm/package/rpm.rb:446:in `each'
        from /usr/local/share/gems/gems/fpm-1.4.0/lib/fpm/package/rpm.rb:446:in `output'
        from /usr/local/share/gems/gems/fpm-1.4.0/lib/fpm/command.rb:475:in `execute'
        from /usr/local/share/gems/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'
        from /usr/local/share/gems/gems/fpm-1.4.0/lib/fpm/command.rb:535:in `run'
        from /usr/local/share/gems/gems/clamp-0.6.5/lib/clamp/command.rb:132:in `run'
        from /usr/local/share/gems/gems/fpm-1.4.0/bin/fpm:8:in `<top (required)>'
        from /usr/local/bin/fpm:23:in `load'
        from /usr/local/bin/fpm:23:in `<main>'
```

I understand that the arguments are incompatible, but still the program shouldn't crash and should provide descriptive error message instead.
