### ISSUE TITLE
fpm `utime`s symlinks (and does so despite exclusion)

### ISSUE THREAD

**Issue by doismellburning** [jordansissel/fpm#767]
```
$ fpm --version
1.2.0
$ virtualenv .env
New python executable in .env/bin/python
Installing setuptools, pip...done.
$ rm -f *deb ; fpm -s dir -t deb -n excludetest -x .env .
.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/fpm-1.2.0/lib/fpm/package/dir.rb:202:in `utime': Operation not permitted - /tmp/package-dir-staging20140904-42793-xphwui/./.env/.Python (Errno::EPERM)
    from .rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/fpm-1.2.0/lib/fpm/package/dir.rb:202:in `copy_metadata'
    from .rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/fpm-1.2.0/lib/fpm/package/dir.rb:191:in `copy'
    from .rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/fpm-1.2.0/lib/fpm/package/dir.rb:145:in `block in clone'
    from .rbenv/versions/1.9.3-p194/lib/ruby/1.9.1/find.rb:41:in `block in find'
    from .rbenv/versions/1.9.3-p194/lib/ruby/1.9.1/find.rb:40:in `catch'
    from .rbenv/versions/1.9.3-p194/lib/ruby/1.9.1/find.rb:40:in `find'
    from .rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/fpm-1.2.0/lib/fpm/package/dir.rb:143:in `clone'
    from .rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/fpm-1.2.0/lib/fpm/package/dir.rb:71:in `block in input'
    from .rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/fpm-1.2.0/lib/fpm/package/dir.rb:69:in `chdir'
    from .rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/fpm-1.2.0/lib/fpm/package/dir.rb:69:in `input'
    from .rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/fpm-1.2.0/lib/fpm/command.rb:302:in `block in execute'
    from .rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/fpm-1.2.0/lib/fpm/command.rb:301:in `each'
    from .rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/fpm-1.2.0/lib/fpm/command.rb:301:in `execute'
    from .rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/clamp-0.6.3/lib/clamp/command.rb:67:in `run'
    from .rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/fpm-1.2.0/lib/fpm/command.rb:482:in `run'
    from .rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/clamp-0.6.3/lib/clamp/command.rb:125:in `run'
    from .rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/fpm-1.2.0/bin/fpm:8:in `<top (required)>'
    from .rbenv/versions/1.9.3-p194/bin/fpm:23:in `load'
    from .rbenv/versions/1.9.3-p194/bin/fpm:23:in `<main>'
$ rm -rf .env
$ mkdir .env
$ touch .env/SHOULD_BE_EXCLUDED
$ fpm -s dir -t deb -n excludetest -x .env . && dpkg --contents *.deb | grep -c SHOULD_BE_EXCLUDED
Created package {:path=>"excludetest_1.0_amd64.deb"}
0
```

Observations:
- This appears to be a regression of #224 / #234 / #240 which talk about "not utime-ing symlinks
- This happens _despite_ `-x .env` which, when `.env` does not include symlinks, successfully excludes `.env`

**Comment by rkh** [comment]
Any updates on this?

**Comment by bsergean** [comment]
I'm hitting this problem too. I'm trying to fpm a directory made out of python installed package through virtualenv. The symlinks are created by virtualenv. I was able to workaround the problem by passing the `--always-copy` flag when I create my virtualenv.

I guess I could also try to create the package using the supported easy_install and stuff...

**Comment by andschwa** [comment]
I get this whenever I try to package a symlink in a `dir` package if the symlink's target exist. Oddly, when the target doesn't exist, it works just fine :frowning:
