### ISSUE TITLE
"No such file or directory" - can it include filename?

### ISSUE THREAD

**Issue by stodge** [jordansissel/fpm#768]
I keep getting a "No such file or directory" error, but there's no indication of what it was trying to find. Would it be possible include the file or directory name in the error? Thanks

```
Package version '1.0.0-2471' includes dashes, converting to underscores {:level=>:warn}
no value for epoch is set, defaulting to nil {:level=>:warn}
/usr/share/ruby/find.rb:38:in `block in find': No such file or directory (Errno::ENOENT)
    from /usr/share/ruby/find.rb:38:in `collect!'
    from /usr/share/ruby/find.rb:38:in `find'
    from /usr/local/share/gems/gems/fpm-1.2.0/lib/fpm/package/rpm.rb:396:in `block in output'
    from /usr/local/share/gems/gems/fpm-1.2.0/lib/fpm/package/rpm.rb:395:in `each'
    from /usr/local/share/gems/gems/fpm-1.2.0/lib/fpm/package/rpm.rb:395:in `output'
    from /usr/local/share/gems/gems/fpm-1.2.0/lib/fpm/command.rb:418:in `execute'
    from /usr/local/share/gems/gems/clamp-0.6.3/lib/clamp/command.rb:67:in `run'
    from /usr/local/share/gems/gems/fpm-1.2.0/lib/fpm/command.rb:482:in `run'
    from /usr/local/share/gems/gems/clamp-0.6.3/lib/clamp/command.rb:125:in `run'
    from /usr/local/share/gems/gems/fpm-1.2.0/bin/fpm:8:in `<top (required)>'
    from /usr/local/bin/fpm:23:in `load'
    from /usr/local/bin/fpm:23:in `<main>'
```

**Comment by mIcHyAmRaNe** [comment]
10 years later, i'm facing this error, and even with verbose, debug, i can't figure out what's looking for :D
