### ISSUE TITLE
Error building python-dateutil with pip

### ISSUE THREAD

**Issue by robinbowes** [jordansissel/fpm#848]
I was quite sure how to categorise this issue so I'll just describe what I experienced. I think there may be a couple of issues here. Feel free to triage/re-label/etc.

I was packaging awscli in rpm format on a CentOS 7 box. The basic procedure I was using was:

```
list_of_packages = awscli
while list_of_packages is not empty
  get next package from list_of_packages
  build pkg using: fpm -s python -t rpm --python-pip /usr/bin/pip pkg_name (use --version if necessary)
  check requirements of pkg_name and add any new ones to list_of_packages
end
```
This worked fine until I got to the dependencies of botocore where I hit the first issue. The botocore build completed OK and the resulting rpm has the following dependencies:
```
$ rpm -qp --requires python-botocore-0.86.0-1.noarch.rpm
python-jmespath = 0.6.1
python-dateutil >= 2.1
python-dateutil < 3.0.0
rpmlib(PayloadFilesHavePrefix) <= 4.0-1
rpmlib(CompressedFileNames) <= 3.0.4-1
```
I couldn't understand why fpm was not able to find the python module named "dateutil". However, the name of the python dateutil module is actually "python-dateutil" (not "dateutil"), so the dependency should be listed as "python-python-dateutil"

I then moved on to building python-dateutil, where I hit the second issue. The python-datetutil build failed when using pip:
```
$ fpm -s python -t rpm --python-pip /usr/bin/pip python-dateutil
Could not find 'setup.py' {:path=>"/tmp/package-python-build20150210-26950-se8w0r/python-dateutil/python-dateutil/setup.py", :level=>:error}
/usr/local/share/gems/gems/fpm-1.3.3/lib/fpm/package/python.rb:93:in `input': Unable to find python package; tried /tmp/package-python-build20150210-26950-se8w0r/python-dateutil/python-dateutil/setup.py (RuntimeError)
	from /usr/local/share/gems/gems/fpm-1.3.3/lib/fpm/command.rb:332:in `block in execute'
	from /usr/local/share/gems/gems/fpm-1.3.3/lib/fpm/command.rb:331:in `each'
	from /usr/local/share/gems/gems/fpm-1.3.3/lib/fpm/command.rb:331:in `execute'
	from /usr/local/share/gems/gems/clamp-0.6.3/lib/clamp/command.rb:67:in `run'
	from /usr/local/share/gems/gems/fpm-1.3.3/lib/fpm/command.rb:510:in `run'
	from /usr/local/share/gems/gems/clamp-0.6.3/lib/clamp/command.rb:125:in `run'
	from /usr/local/share/gems/gems/fpm-1.3.3/bin/fpm:8:in `<top (required)>'
	from /usr/local/bin/fpm:23:in `load'
	from /usr/local/bin/fpm:23:in `<main>'
```
I discovered that it works OK with out pip:
```
$ fpm -s python -t rpm python-dateutil
no value for epoch is set, defaulting to nil {:level=>:warn}
no value for epoch is set, defaulting to nil {:level=>:warn}
Created package {:path=>"python-dateutil-2.4.0-1.noarch.rpm"}
```
However, you will notice that the rpm name does not follow OS convention, ie. it is "python-dateutil" rather than "python-python-dateutil".

So, I've actually got what I wanted (awscli and all deps packaged as RPMs) but Tray suggest I log the issue.

**Comment by mzupan** [comment]
running into this same issue.. any fixes?

**Comment by pnewb** [comment]
If I'm reading this correctly, we're falling prey to this:
https://github.com/jordansissel/fpm/blob/master/lib/fpm/package/python.rb#L261

I know it feels odd to have a package called 'python36-python-dateutil' but I think if the package name truly _is_ "python-whatever" then preserving that may be the way to go when prefixing python packages.
