### ISSUE TITLE
python: sometimes packages using `pbr` don't work right?

### ISSUE THREAD

**Issue by jordansissel** [jordansissel/fpm#854]
Example: https://gist.github.com/neoice/d62e1ea2036e452f0366

I can't reproduce this myself, `fpm -s python -t deb jenkins-job-builder` (and `-t rpm`) work fine for me on OSX Python 2.7.6.

**Comment by jordansissel** [comment]
This is reported to fail under CentOS with Python 2.6

**Comment by jordansissel** [comment]
`pbr` itself seems... to break things, for example (tested with 2.7.6)

```
% python setup.py --help-commands
Traceback (most recent call last):
  File "setup.py", line 19, in <module>
    pbr=True)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 138, in setup
    ok = dist.parse_command_line()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/dist.py", line 250, in parse_command_line
    result = _Distribution.parse_command_line(self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 464, in parse_command_line
    if self.handle_display_options(option_order):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/dist.py", line 611, in handle_display_options
    return _Distribution.handle_display_options(self, option_order)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 669, in handle_display_options
    self.print_commands()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/dist.py", line 371, in print_commands
    cmdclass = ep.load(False) # don't require extras, we're not running
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 2108, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/private/tmp/jjb/jenkins-job-builder/pbr-0.10.7-py2.7.egg/pbr/testr_command.py", line 47, in <module>
    from testrepository import commands
ImportError: No module named testrepository
```

**Comment by neoice** [comment]
output of a broken build
```
Setting attribute", :output_type=>"rpm", :level=>:debug, :file=>"fpm/command.rb", :line=>"293"}
Setting attribute", :input_type=>"python", :level=>:debug, :file=>"fpm/command.rb", :line=>"293"}
Setting attribute", :chdir=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"293"}
Setting attribute", :prefix=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"293"}
Setting attribute", :package=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"293"}
Setting attribute", :force?=>false, :level=>:debug, :file=>"fpm/command.rb", :line=>"293"}
Setting attribute", :name=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"293"}
Setting attribute", :verbose?=>true, :level=>:debug, :file=>"fpm/command.rb", :line=>"293"}
Setting attribute", :debug?=>true, :level=>:debug, :file=>"fpm/command.rb", :line=>"293"}
Setting attribute", :debug_workspace?=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"293"}
Setting attribute", :version=>1.0, :level=>:debug, :file=>"fpm/command.rb", :line=>"293"}
Setting attribute", :iteration=>"10", :level=>:debug, :file=>"fpm/command.rb", :line=>"293"}
Setting attribute", :epoch=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"293"}
Setting attribute", :license=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"293"}
Setting attribute", :vendor=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"293"}
Setting attribute", :category=>"none", :level=>:debug, :file=>"fpm/command.rb", :line=>"293"}
Setting attribute", :dependencies=>[], :level=>:debug, :file=>"fpm/command.rb", :line=>"293"}
Setting attribute", :no_depends?=>false, :level=>:debug, :file=>"fpm/command.rb", :line=>"293"}
Setting attribute", :no_auto_depends?=>false, :level=>:debug, :file=>"fpm/command.rb", :line=>"293"}
Setting attribute", :provides=>[], :level=>:debug, :file=>"fpm/command.rb", :line=>"293"}
Setting attribute", :conflicts=>[], :level=>:debug, :file=>"fpm/command.rb", :line=>"293"}
Setting attribute", :replaces=>[], :level=>:debug, :file=>"fpm/command.rb", :line=>"293"}
Setting attribute", :config_files=>[], :level=>:debug, :file=>"fpm/command.rb", :line=>"293"}
Setting attribute", :directories=>[], :level=>:debug, :file=>"fpm/command.rb", :line=>"293"}
Setting attribute", :architecture=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"293"}
Setting attribute", :maintainer=>"<jenkins@build.example.com>", :level=>:debug, :file=>"fpm/command.rb", :line=>"293"}
Setting attribute", :package_name_suffix=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"293"}
Setting attribute", :edit?=>false, :level=>:debug, :file=>"fpm/command.rb", :line=>"293"}
Setting attribute", :excludes=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"293"}
Setting attribute", :description=>"no description", :level=>:debug, :file=>"fpm/command.rb", :line=>"293"}
Setting attribute", :url=>"http://example.com/no-uri-given", :level=>:debug, :file=>"fpm/command.rb", :line=>"293"}
Setting attribute", :inputs=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"293"}
Setting attribute", :post_install=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"293"}
Setting attribute", :pre_install=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"293"}
Setting attribute", :post_uninstall=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"293"}
Setting attribute", :pre_uninstall=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"293"}
Setting attribute", :after_install=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"293"}
Setting attribute", :before_install=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"293"}
Setting attribute", :after_remove=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"293"}
Setting attribute", :before_remove=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"293"}
Setting attribute", :template_scripts?=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"293"}
Setting attribute", :template_value_list=>[], :level=>:debug, :file=>"fpm/command.rb", :line=>"293"}
Setting attribute", :workdir=>"/tmp", :level=>:debug, :file=>"fpm/command.rb", :line=>"293"}
Setting attribute", :gem_bin_path=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"293"}
Setting attribute", :gem_package_prefix=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"293"}
Setting attribute", :gem_package_name_prefix=>"rubygem", :level=>:debug, :file=>"fpm/command.rb", :line=>"293"}
Setting attribute", :gem_gem=>"gem", :level=>:debug, :file=>"fpm/command.rb", :line=>"293"}
Setting attribute", :gem_fix_name?=>true, :level=>:debug, :file=>"fpm/command.rb", :line=>"293"}
Setting attribute", :gem_fix_dependencies?=>true, :level=>:debug, :file=>"fpm/command.rb", :line=>"293"}
Setting attribute", :gem_env_shebang?=>true, :level=>:debug, :file=>"fpm/command.rb", :line=>"293"}
Setting attribute", :gem_prerelease?=>false, :level=>:debug, :file=>"fpm/command.rb", :line=>"293"}
Setting attribute", :gem_disable_dependencies=>[], :level=>:debug, :file=>"fpm/command.rb", :line=>"293"}
Setting attribute", :gem_version_bins?=>false, :level=>:debug, :file=>"fpm/command.rb", :line=>"293"}
Setting attribute", :deb_ignore_iteration_in_dependencies?=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"293"}
Setting attribute", :deb_build_depends=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"293"}
Setting attribute", :deb_pre_depends=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"293"}
Setting attribute", :deb_compression=>"gz", :level=>:debug, :file=>"fpm/command.rb", :line=>"293"}
Setting attribute", :deb_custom_control=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"293"}
Setting attribute", :deb_config=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"293"}
Setting attribute", :deb_templates=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"293"}
Setting attribute", :deb_installed_size=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"293"}
Setting attribute", :deb_priority=>"extra", :level=>:debug, :file=>"fpm/command.rb", :line=>"293"}
Setting attribute", :deb_use_file_permissions?=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"293"}
Setting attribute", :deb_user=>"root", :level=>:debug, :file=>"fpm/command.rb", :line=>"293"}
Setting attribute", :deb_group=>"root", :level=>:debug, :file=>"fpm/command.rb", :line=>"293"}
Setting attribute", :deb_changelog=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"293"}
Setting attribute", :deb_recommends=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"293"}
Setting attribute", :deb_suggests=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"293"}
Setting attribute", :deb_meta_file=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"293"}
Setting attribute", :deb_interest=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"293"}
Setting attribute", :deb_activate=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"293"}
Setting attribute", :deb_field=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"293"}
Setting attribute", :deb_shlibs=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"293"}
Setting attribute", :deb_init_list=>[], :level=>:debug, :file=>"fpm/command.rb", :line=>"293"}
Setting attribute", :deb_default_list=>[], :level=>:debug, :file=>"fpm/command.rb", :line=>"293"}
Setting attribute", :deb_upstart_list=>[], :level=>:debug, :file=>"fpm/command.rb", :line=>"293"}
Setting attribute", :npm_bin=>"npm", :level=>:debug, :file=>"fpm/command.rb", :line=>"293"}
Setting attribute", :npm_package_name_prefix=>"node", :level=>:debug, :file=>"fpm/command.rb", :line=>"293"}
Setting attribute", :npm_registry=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"293"}
Setting attribute", :rpm_use_file_permissions?=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"293"}
Setting attribute", :rpm_user=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"293"}
Setting attribute", :rpm_group=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"293"}
Setting attribute", :rpm_defattrfile=>"-", :level=>:debug, :file=>"fpm/command.rb", :line=>"293"}
Setting attribute", :rpm_defattrdir=>"-", :level=>:debug, :file=>"fpm/command.rb", :line=>"293"}
Setting attribute", :rpm_rpmbuild_define=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"293"}
Setting attribute", :rpm_digest=>"md5", :level=>:debug, :file=>"fpm/command.rb", :line=>"293"}
Setting attribute", :rpm_compression=>"gzip", :level=>:debug, :file=>"fpm/command.rb", :line=>"293"}
Setting attribute", :rpm_os=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"293"}
Setting attribute", :rpm_changelog=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"293"}
Setting attribute", :rpm_sign?=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"293"}
Setting attribute", :rpm_auto_add_directories?=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"293"}
Setting attribute", :auto_add_exclude_directories=>[], :level=>:debug, :file=>"fpm/command.rb", :line=>"293"}
Setting attribute", :rpm_autoreqprov?=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"293"}
Setting attribute", :rpm_autoreq?=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"293"}
Setting attribute", :rpm_autoprov?=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"293"}
Setting attribute", :attrs=>[], :level=>:debug, :file=>"fpm/command.rb", :line=>"293"}
Setting attribute", :rpm_filter_from_provides=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"293"}
Setting attribute", :rpm_filter_from_requires=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"293"}
Setting attribute", :rpm_ignore_iteration_in_dependencies?=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"293"}
Setting attribute", :rpm_verbatim_gem_dependencies?=>false, :level=>:debug, :file=>"fpm/command.rb", :line=>"293"}
Setting attribute", :rpm_verifyscript=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"293"}
Setting attribute", :rpm_pretrans=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"293"}
Setting attribute", :rpm_posttrans=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"293"}
Setting attribute", :cpan_perl_bin=>"perl", :level=>:debug, :file=>"fpm/command.rb", :line=>"293"}
Setting attribute", :cpan_cpanm_bin=>"cpanm", :level=>:debug, :file=>"fpm/command.rb", :line=>"293"}
Setting attribute", :cpan_mirror=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"293"}
Setting attribute", :cpan_mirror_only?=>false, :level=>:debug, :file=>"fpm/command.rb", :line=>"293"}
Setting attribute", :cpan_package_name_prefix=>"perl", :level=>:debug, :file=>"fpm/command.rb", :line=>"293"}
Setting attribute", :cpan_test?=>true, :level=>:debug, :file=>"fpm/command.rb", :line=>"293"}
Setting attribute", :cpan_perl_lib_path=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"293"}
Setting attribute", :pear_package_name_prefix=>"php-pear", :level=>:debug, :file=>"fpm/command.rb", :line=>"293"}
Setting attribute", :pear_channel=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"293"}
Setting attribute", :pear_channel_update?=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"293"}
Setting attribute", :pear_bin_dir=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"293"}
Setting attribute", :pear_php_bin=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"293"}
Setting attribute", :pear_php_dir=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"293"}
Setting attribute", :pear_data_dir=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"293"}
Setting attribute", :python_bin=>"python", :level=>:debug, :file=>"fpm/command.rb", :line=>"293"}
Setting attribute", :python_easyinstall=>"easy_install", :level=>:debug, :file=>"fpm/command.rb", :line=>"293"}
Setting attribute", :python_pip=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"293"}
Setting attribute", :python_pypi=>"http://pypi.python.org/simple", :level=>:debug, :file=>"fpm/command.rb", :line=>"293"}
Setting attribute", :python_package_prefix=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"293"}
Setting attribute", :python_package_name_prefix=>"python", :level=>:debug, :file=>"fpm/command.rb", :line=>"293"}
Setting attribute", :python_fix_name?=>true, :level=>:debug, :file=>"fpm/command.rb", :line=>"293"}
Setting attribute", :python_fix_dependencies?=>true, :level=>:debug, :file=>"fpm/command.rb", :line=>"293"}
Setting attribute", :python_downcase_name?=>true, :level=>:debug, :file=>"fpm/command.rb", :line=>"293"}
Setting attribute", :python_downcase_dependencies?=>true, :level=>:debug, :file=>"fpm/command.rb", :line=>"293"}
Setting attribute", :python_install_bin=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"293"}
Setting attribute", :python_install_lib=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"293"}
Setting attribute", :python_install_data=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"293"}
Setting attribute", :python_dependencies?=>true, :level=>:debug, :file=>"fpm/command.rb", :line=>"293"}
Setting attribute", :python_obey_requirements_txt?=>false, :level=>:debug, :file=>"fpm/command.rb", :line=>"293"}
Setting attribute", :python_scripts_executable=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"293"}
Setting attribute", :osxpkg_identifier_prefix=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"293"}
Setting attribute", :osxpkg_payload_free?=>false, :level=>:debug, :file=>"fpm/command.rb", :line=>"293"}
Setting attribute", :osxpkg_ownership=>"recommended", :level=>:debug, :file=>"fpm/command.rb", :line=>"293"}
Setting attribute", :osxpkg_postinstall_action=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"293"}
Setting attribute", :osxpkg_dont_obsolete=>nil, :level=>:debug, :file=>"fpm/command.rb", :line=>"293"}
Setting attribute", :solaris_user=>"root", :level=>:debug, :file=>"fpm/command.rb", :line=>"293"}
Setting attribute", :solaris_group=>"root", :level=>:debug, :file=>"fpm/command.rb", :line=>"293"}
Trying to download", :package=>"jenkins-job-builder", :level=>:info, :file=>"fpm/package/python.rb", :line=>"111"}
no pip, defaulting to easy_install", :easy_install=>"easy_install", :level=>:debug, :file=>"fpm/package/python.rb", :line=>"124"}
Running command", :args=>["easy_install", "-i", "http://pypi.python.org/simple", "--editable", "-U", "--build-directory", "/tmp/package-python-build20150206-15932-12wra86/jenkins-job-builder", "jenkins-job-builder"], :level=>:debug, :file=>"fpm/util.rb", :line=>"59"}
Process is running", :pid=>15935, :level=>:debug, :file=>"fpm/util.rb", :line=>"72"}
Searching for jenkins-job-builder", :level=>:info, :file=>"cabin/mixins/pipe.rb", :line=>"46"}
Reading http://pypi.python.org/simple/jenkins-job-builder/", :level=>:info, :file=>"cabin/mixins/pipe.rb", :line=>"46"}
Best match: jenkins-job-builder 1.1.0", :level=>:info, :file=>"cabin/mixins/pipe.rb", :line=>"46"}
Downloading https://pypi.python.org/packages/source/j/jenkins-job-builder/jenkins-job-builder-1.1.0.tar.gz#md5=345d44a4fa78f7034d89eaa7eb2b8794", :level=>:info, :file=>"cabin/mixins/pipe.rb", :line=>"46"}
Processing jenkins-job-builder-1.1.0.tar.gz", :level=>:info, :file=>"cabin/mixins/pipe.rb", :line=>"46"}
", :level=>:info, :file=>"cabin/mixins/pipe.rb", :line=>"46"}
Extracted editable version of jenkins-job-builder to /tmp/package-python-build20150206-15932-12wra86/jenkins-job-builder/jenkins-job-builder", :level=>:info, :file=>"cabin/mixins/pipe.rb", :line=>"46"}
", :level=>:info, :file=>"cabin/mixins/pipe.rb", :line=>"46"}
If it uses setuptools in its setup script, you can activate it in", :level=>:info, :file=>"cabin/mixins/pipe.rb", :line=>"46"}
\"development\" mode by going to that directory and running::", :level=>:info, :file=>"cabin/mixins/pipe.rb", :line=>"46"}
", :level=>:info, :file=>"cabin/mixins/pipe.rb", :line=>"46"}
    /usr/bin/python setup.py develop", :level=>:info, :file=>"cabin/mixins/pipe.rb", :line=>"46"}
", :level=>:info, :file=>"cabin/mixins/pipe.rb", :line=>"46"}
See the setuptools documentation for the \"develop\" command for more info.", :level=>:info, :file=>"cabin/mixins/pipe.rb", :line=>"46"}
", :level=>:info, :file=>"cabin/mixins/pipe.rb", :line=>"46"}
Running command", :args=>["/bin/bash", "-c", "python -c 'try:\n  import json\nexcept ImportError:\n  import simplejson as json'"], :level=>:debug, :file=>"fpm/util.rb", :line=>"59"}
Process is running", :pid=>15944, :level=>:debug, :file=>"fpm/util.rb", :line=>"72"}
Running command", :args=>["/bin/bash", "-c", "python -c 'import pkg_resources'"], :level=>:debug, :file=>"fpm/util.rb", :line=>"59"}
Process is running", :pid=>15947, :level=>:debug, :file=>"fpm/util.rb", :line=>"72"}
fetching package metadata", :setup_cmd=>"env PYTHONPATH=/usr/ruby/2.1.2/lib/ruby/gems/2.1.0/gems/fpm-1.2.0/lib/fpm/package python setup.py --command-packages=pyfpm get_metadata --output=/tmp/package-python-build20150206-15932-12wra86/metadata.json", :level=>:info, :file=>"fpm/package/python.rb", :line=>"187"}
Running command", :args=>["/bin/bash", "-c", "env PYTHONPATH=/usr/ruby/2.1.2/lib/ruby/gems/2.1.0/gems/fpm-1.2.0/lib/fpm/package python setup.py --command-packages=pyfpm get_metadata --output=/tmp/package-python-build20150206-15932-12wra86/metadata.json"], :level=>:debug, :file=>"fpm/util.rb", :line=>"59"}
Process is running", :pid=>15954, :level=>:debug, :file=>"fpm/util.rb", :line=>"72"}
/usr/lib64/python2.6/distutils/dist.py:266: UserWarning: Unknown distribution option: 'pbr'", :level=>:info, :file=>"cabin/mixins/pipe.rb", :line=>"46"}
  warnings.warn(msg)", :level=>:info, :file=>"cabin/mixins/pipe.rb", :line=>"46"}
running get_metadata", :level=>:info, :file=>"cabin/mixins/pipe.rb", :line=>"46"}
result from `setup.py get_metadata`", :data=>"{\n  \"description\": \"UNKNOWN\", \n  \"license\": \"UNKNOWN\", \n  \"author\": \"UNKNOWN <UNKNOWN>\", \n  \"url\": \"UNKNOWN\", \n  \"version\": \"0.0.0\", \n  \"architecture\": \"all\", \n  \"dependencies\": [], \n  \"name\": \"UNKNOWN\"\n}", :level=>:debug, :file=>"fpm/package/python.rb", :line=>"198"}
object output of get_metadata", :json=>{"description"=>"UNKNOWN", "license"=>"UNKNOWN", "author"=>"UNKNOWN <UNKNOWN>", "url"=>"UNKNOWN", "version"=>"0.0.0", "architecture"=>"all", "dependencies"=>[], "name"=>"UNKNOWN"}, :level=>:info, :file=>"fpm/package/python.rb", :line=>"200"}
Running command", :args=>["python", "setup.py", "install", "--root", "/tmp/package-python-staging20150206-15932-9gnkdf"], :level=>:debug, :file=>"fpm/util.rb", :line=>"59"}
Process is running", :pid=>15959, :level=>:debug, :file=>"fpm/util.rb", :line=>"72"}
/usr/lib64/python2.6/distutils/dist.py:266: UserWarning: Unknown distribution option: 'pbr'", :level=>:info, :file=>"cabin/mixins/pipe.rb", :line=>"46"}
  warnings.warn(msg)", :level=>:info, :file=>"cabin/mixins/pipe.rb", :line=>"46"}
running install", :level=>:info, :file=>"cabin/mixins/pipe.rb", :line=>"46"}
running build", :level=>:info, :file=>"cabin/mixins/pipe.rb", :line=>"46"}
running install_egg_info", :level=>:info, :file=>"cabin/mixins/pipe.rb", :line=>"46"}
running egg_info", :level=>:info, :file=>"cabin/mixins/pipe.rb", :line=>"46"}
creating UNKNOWN.egg-info", :level=>:info, :file=>"cabin/mixins/pipe.rb", :line=>"46"}
writing UNKNOWN.egg-info/PKG-INFO", :level=>:info, :file=>"cabin/mixins/pipe.rb", :line=>"46"}
writing top-level names to UNKNOWN.egg-info/top_level.txt", :level=>:info, :file=>"cabin/mixins/pipe.rb", :line=>"46"}
writing dependency_links to UNKNOWN.egg-info/dependency_links.txt", :level=>:info, :file=>"cabin/mixins/pipe.rb", :line=>"46"}
writing manifest file 'UNKNOWN.egg-info/SOURCES.txt'", :level=>:info, :file=>"cabin/mixins/pipe.rb", :line=>"46"}
reading manifest file 'UNKNOWN.egg-info/SOURCES.txt'", :level=>:info, :file=>"cabin/mixins/pipe.rb", :line=>"46"}
reading manifest template 'MANIFEST.in'", :level=>:info, :file=>"cabin/mixins/pipe.rb", :line=>"46"}
warning: no files found matching 'jenkins_jobs/versioninfo'", :level=>:info, :file=>"cabin/mixins/pipe.rb", :line=>"46"}
warning: no previously-included files found matching '.gitignore'", :level=>:info, :file=>"cabin/mixins/pipe.rb", :line=>"46"}
warning: no previously-included files found matching '.gitreview'", :level=>:info, :file=>"cabin/mixins/pipe.rb", :line=>"46"}
warning: no previously-included files matching '*.pyc' found anywhere in distribution", :level=>:info, :file=>"cabin/mixins/pipe.rb", :line=>"46"}
writing manifest file 'UNKNOWN.egg-info/SOURCES.txt'", :level=>:info, :file=>"cabin/mixins/pipe.rb", :line=>"46"}
Copying UNKNOWN.egg-info to /tmp/package-python-staging20150206-15932-9gnkdf/usr/lib/python2.6/site-packages/UNKNOWN-0.0.0-py2.6.egg-info", :level=>:info, :file=>"cabin/mixins/pipe.rb", :line=>"46"}
running install_scripts", :level=>:info, :file=>"cabin/mixins/pipe.rb", :line=>"46"}
Setting from flags: epoch=", :level=>:info, :file=>"fpm/command.rb", :line=>"329"}
Setting from flags: iteration=10", :level=>:info, :file=>"fpm/command.rb", :line=>"329"}
Converting python to rpm", :level=>:info, :file=>"fpm/package.rb", :line=>"192"}
Cleaning up staging path", :path=>"/tmp/package-rpm-staging20150206-15932-1mlol7b", :level=>:debug, :file=>"fpm/package.rb", :line=>"281"}
no value for epoch is set, defaulting to nil", :level=>:warn, :file=>"fpm/package/rpm.rb", :line=>"470"}
Reading template", :path=>"/usr/ruby/2.1.2/lib/ruby/gems/2.1.0/gems/fpm-1.2.0/templates/rpm.erb", :level=>:info, :file=>"fpm/package.rb", :line=>"330"}
no value for epoch is set, defaulting to nil", :level=>:warn, :file=>"fpm/package/rpm.rb", :line=>"470"}
Running rpmbuild", :args=>["rpmbuild", "-bb", "--target", "noarch", "--define", "buildroot /tmp/package-rpm-build20150206-15932-1yls3mt/BUILD", "--define", "_topdir /tmp/package-rpm-build20150206-15932-1yls3mt", "--define", "_sourcedir /tmp/package-rpm-build20150206-15932-1yls3mt", "--define", "_rpmdir /tmp/package-rpm-build20150206-15932-1yls3mt/RPMS", "--define", "_tmppath /tmp", "/tmp/package-rpm-build20150206-15932-1yls3mt/SPECS/python-unknown.spec"], :level=>:info, :file=>"fpm/package/rpm.rb", :line=>"437"}
Running command", :args=>["rpmbuild", "-bb", "--target", "noarch", "--define", "buildroot /tmp/package-rpm-build20150206-15932-1yls3mt/BUILD", "--define", "_topdir /tmp/package-rpm-build20150206-15932-1yls3mt", "--define", "_sourcedir /tmp/package-rpm-build20150206-15932-1yls3mt", "--define", "_rpmdir /tmp/package-rpm-build20150206-15932-1yls3mt/RPMS", "--define", "_tmppath /tmp", "/tmp/package-rpm-build20150206-15932-1yls3mt/SPECS/python-unknown.spec"], :level=>:debug, :file=>"fpm/util.rb", :line=>"59"}
Process is running", :pid=>15963, :level=>:debug, :file=>"fpm/util.rb", :line=>"72"}
Building target platforms: noarch", :level=>:info, :file=>"cabin/mixins/pipe.rb", :line=>"46"}
Building for target noarch", :level=>:info, :file=>"cabin/mixins/pipe.rb", :line=>"46"}
Executing(%prep): /bin/sh -e /tmp/rpm-tmp.Sua3d5", :level=>:info, :file=>"cabin/mixins/pipe.rb", :line=>"46"}
Executing(%build): /bin/sh -e /tmp/rpm-tmp.NbNKps", :level=>:info, :file=>"cabin/mixins/pipe.rb", :line=>"46"}
Executing(%install): /bin/sh -e /tmp/rpm-tmp.CJDcCP", :level=>:info, :file=>"cabin/mixins/pipe.rb", :line=>"46"}
Processing files: python-unknown-0.0.0-10.noarch", :level=>:info, :file=>"cabin/mixins/pipe.rb", :line=>"46"}
Wrote: /tmp/package-rpm-build20150206-15932-1yls3mt/RPMS/noarch/python-unknown-0.0.0-10.noarch.rpm", :level=>:info, :file=>"cabin/mixins/pipe.rb", :line=>"46"}
Executing(%clean): /bin/sh -e /tmp/rpm-tmp.F9CA3z", :level=>:info, :file=>"cabin/mixins/pipe.rb", :line=>"46"}
Created package", :path=>"python-unknown-0.0.0-10.noarch.rpm", :file=>"clamp/command.rb", :line=>"67"}
```
