### ISSUE TITLE
Using using more than 1 install script flag with --template-scripts causes build failure.

### ISSUE THREAD

**Issue by stumped2** [jordansissel/fpm#855]
When using --template-scripts --after-install "post.sh" --before-install "pre.sh" I get this error:
```ruby
All flags should be before the first argument (stray flags found: ["--template-scripts", "--after-install", "--before-install"] {:level=>:warn}
Invalid package configuration: Cannot package the path 'bugzilla-asf/--template-scripts', does it exist? {:level=>:error}
```

It tries to parse the next flag as a script. If I remove the secondary script flag, then I don't get the error, but I also don't get the expected script behavior.

**Comment by jakerobinson** [comment]
fpm typically looks for a 'thing to be packaged' as the last argument in the command. As a test, I'd add an arbitrary folder to the end. maybe a silly question, but where are you getting the `-s file` from?

**Comment by jordansissel** [comment]
Please post your entire fpm command line

**Comment by stumped2** [comment]
@jakerobinson oops, that was a typo. It was supposed to be dir (and is in my script)

@jordansissel here is the entire command:

```sh
/home/coreyg/.gem/ruby/1.9.1/bin/fpm -s dir -t deb -C ./bugzilla-asf --prefix /var/www/bugzilla-asf/ --template-scripts --before-install preinstall.sh --after-install postinstall.sh -n bugzilla-asf -v 4.4.6 --workdir /tmp/fpm --iteration 20150220 -d apache2 -d libdbd-mysql-perl -d libjifty-plugin-chart-perl -d libdatetime-perl -d libdatetime-timezone-perl -d libtemplate-plugin-gd-perl -d libemail-send-perl -d libemail-mime-perl -d libmath-random-isaac-perl -d libbytes-random-secure-perl -d libsoap-lite-perl -d libtest-taint-perl -d xml-twig-tools -d libjson-rpc-perl -d libhtml-scrubber-perl --description 'ASF Bugzilla' .
/usr/lib/ruby/1.9.1/erb.rb:838:in `eval': script(before_install):8: syntax error, unexpected '=', expecting $end (SyntaxError)
;  = name ; _erbout.concat "/data...
    ^
	from /usr/lib/ruby/1.9.1/erb.rb:838:in `result'
	from /home/coreyg/.gem/ruby/1.9.1/gems/fpm-1.3.3/lib/fpm/package.rb:489:in `script'
	from /home/coreyg/.gem/ruby/1.9.1/gems/fpm-1.3.3/lib/fpm/package/deb.rb:636:in `block (2 levels) in write_scripts'
	from /home/coreyg/.gem/ruby/1.9.1/gems/fpm-1.3.3/lib/fpm/util.rb:144:in `call'
	from /home/coreyg/.gem/ruby/1.9.1/gems/fpm-1.3.3/lib/fpm/util.rb:144:in `with'
	from /home/coreyg/.gem/ruby/1.9.1/gems/fpm-1.3.3/lib/fpm/package/deb.rb:634:in `block in write_scripts'
	from /home/coreyg/.gem/ruby/1.9.1/gems/fpm-1.3.3/lib/fpm/package/deb.rb:631:in `each'
	from /home/coreyg/.gem/ruby/1.9.1/gems/fpm-1.3.3/lib/fpm/package/deb.rb:631:in `write_scripts'
	from /home/coreyg/.gem/ruby/1.9.1/gems/fpm-1.3.3/lib/fpm/package/deb.rb:569:in `write_control_tarball'
	from /home/coreyg/.gem/ruby/1.9.1/gems/fpm-1.3.3/lib/fpm/package/deb.rb:369:in `output'
	from /home/coreyg/.gem/ruby/1.9.1/gems/fpm-1.3.3/lib/fpm/command.rb:450:in `execute'
	from /home/coreyg/.gem/ruby/1.9.1/gems/clamp-0.6.3/lib/clamp/command.rb:67:in `run'
	from /home/coreyg/.gem/ruby/1.9.1/gems/fpm-1.3.3/lib/fpm/command.rb:510:in `run'
	from /home/coreyg/.gem/ruby/1.9.1/gems/clamp-0.6.3/lib/clamp/command.rb:125:in `run'
	from /home/coreyg/.gem/ruby/1.9.1/gems/fpm-1.3.3/bin/fpm:8:in `<top (required)>'
	from /home/coreyg/.gem/ruby/1.9.1/bin/fpm:23:in `load'
	from /home/coreyg/.gem/ruby/1.9.1/bin/fpm:23:in `<main>'
```
