### ISSUE TITLE
fpm ignores later inputs if I omit trailing slash

### ISSUE THREAD

**Issue by wang-d** [jordansissel/fpm#910]
What are the semantics of trailing slashes in mapping paths for the
dir source?

First, set up some files to package:

    d=$(mktemp -d)
    date > $d/foo
    date > $d/bar
    date > $d/baz

No trailing slashes: puts foo into the file /usr/bin and ignores bar 

    fpm --force -s dir -t rpm --name foo -p /tmp/foo.rpm \
        $d/foo=/usr/bin $d/bar=/usr/bin
    rpmfile /tmp/foo.rpm

Trailing slash on first input: puts foo and bar under /usr/bin as I expect

    fpm --force -s dir -t rpm --name foo -p /tmp/foo.rpm \
        $d/foo=/usr/bin/ $d/bar=/usr/bin
    rpmfile /tmp/foo.rpm

Trailing slashes on both inputs: also as expected

    fpm --force -s dir -t rpm --name foo -p /tmp/foo.rpm \
        $d/foo=/usr/bin/ $d/bar=/usr/bin/
    rpmfile /tmp/foo.rpm

Trailing slash on second input: also as expected

    fpm --force -s dir -t rpm --name foo -p /tmp/foo.rpm \
        $d/foo=/usr/bin $d/bar=/usr/bin/
    rpmfile /tmp/foo.rpm

So do I just need a trailing slash on at least one input?  No, a
trailing slash on second of three inputs raises an exception!

    fpm --force -s dir -t rpm --name foo -p /tmp/foo.rpm \
        $d/foo=/usr/bin $d/bar=/usr/bin/ $d/baz=/usr/bin
    rpmfile /tmp/foo.rpm

Here's the full output:

    ++ mktemp -d
    + d=/tmp/tmp.t2gOfmui7G
    + date
    + date
    + date
    + fpm --force -s dir -t rpm --name foo -p /tmp/foo.rpm /tmp/tmp.t2gOfmui7G/foo=/usr/bin /tmp/tmp.t2gOfmui7G/bar=/usr/bin
    Cannot copy file, the destination path is probably a directory and I attempted to write a file. {:staging=>"/tmp/dwang/package-dir-staging20150501-12799-1j35d1h", "method"=>"input", :level=>:error, :path=>"/usr/bin"}
    no value for epoch is set, defaulting to nil {:level=>:warn}
    Force flag given. Overwriting package at /tmp/foo.rpm {:level=>:warn}
    no value for epoch is set, defaulting to nil {:level=>:warn}
    Created package {:path=>"/tmp/foo.rpm"}
    + rpmfile /tmp/foo.rpm
    /usr/bin	100644	ASCII text
    + fpm --force -s dir -t rpm --name foo -p /tmp/foo.rpm /tmp/tmp.t2gOfmui7G/foo=/usr/bin/ /tmp/tmp.t2gOfmui7G/bar=/usr/bin
    no value for epoch is set, defaulting to nil {:level=>:warn}
    Force flag given. Overwriting package at /tmp/foo.rpm {:level=>:warn}
    no value for epoch is set, defaulting to nil {:level=>:warn}
    Created package {:path=>"/tmp/foo.rpm"}
    + rpmfile /tmp/foo.rpm
    /usr/bin/bar	100644	ASCII text
    /usr/bin/foo	100644	ASCII text
    + fpm --force -s dir -t rpm --name foo -p /tmp/foo.rpm /tmp/tmp.t2gOfmui7G/foo=/usr/bin/ /tmp/tmp.t2gOfmui7G/bar=/usr/bin/
    no value for epoch is set, defaulting to nil {:level=>:warn}
    Force flag given. Overwriting package at /tmp/foo.rpm {:level=>:warn}
    no value for epoch is set, defaulting to nil {:level=>:warn}
    Created package {:path=>"/tmp/foo.rpm"}
    + rpmfile /tmp/foo.rpm
    /usr/bin/bar	100644	ASCII text
    /usr/bin/foo	100644	ASCII text
    + fpm --force -s dir -t rpm --name foo -p /tmp/foo.rpm /tmp/tmp.t2gOfmui7G/foo=/usr/bin /tmp/tmp.t2gOfmui7G/bar=/usr/bin/
    /usr/lib/ruby/1.8/fileutils.rb:243:in `mkdir': File exists - /tmp/dwang/package-dir-staging20150501-13019-ntg3kl/usr/bin (Errno::EEXIST)
            from /usr/lib/ruby/1.8/fileutils.rb:243:in `fu_mkdir'
            from /usr/lib/ruby/1.8/fileutils.rb:217:in `mkdir_p'
            from /usr/lib/ruby/1.8/fileutils.rb:215:in `reverse_each'
            from /usr/lib/ruby/1.8/fileutils.rb:215:in `mkdir_p'
            from /usr/lib/ruby/1.8/fileutils.rb:201:in `each'
            from /usr/lib/ruby/1.8/fileutils.rb:201:in `mkdir_p'
            from /usr/lib/ruby/gems/1.8/gems/fpm-1.1.0/lib/fpm/package/dir.rb:158:in `copy'
            from /usr/lib/ruby/gems/1.8/gems/fpm-1.1.0/lib/fpm/package/dir.rb:137:in `clone'
            from /usr/lib/ruby/gems/1.8/gems/fpm-1.1.0/lib/fpm/package/dir.rb:71:in `input'
            from /usr/lib/ruby/gems/1.8/gems/fpm-1.1.0/lib/fpm/package/dir.rb:69:in `chdir'
            from /usr/lib/ruby/gems/1.8/gems/fpm-1.1.0/lib/fpm/package/dir.rb:69:in `input'
            from /usr/lib/ruby/gems/1.8/gems/fpm-1.1.0/lib/fpm/command.rb:299:in `execute'
            from /usr/lib/ruby/gems/1.8/gems/fpm-1.1.0/lib/fpm/command.rb:298:in `each'
            from /usr/lib/ruby/gems/1.8/gems/fpm-1.1.0/lib/fpm/command.rb:298:in `execute'
            from /usr/lib/ruby/gems/1.8/gems/clamp-0.6.3/lib/clamp/command.rb:67:in `run'
            from /usr/lib/ruby/gems/1.8/gems/fpm-1.1.0/lib/fpm/command.rb:449:in `run'
            from /usr/lib/ruby/gems/1.8/gems/clamp-0.6.3/lib/clamp/command.rb:125:in `run'
            from /usr/lib/ruby/gems/1.8/gems/fpm-1.1.0/bin/fpm:8
            from /usr/bin/fpm:19:in `load'
            from /usr/bin/fpm:19

**Comment by axd1967** [comment]
not a complete answer, but this might help?

https://github.com/jordansissel/fpm/blob/139793c8b39ee98eeb1f137757cc718674a83104/spec/fpm/package/dir_spec.rb#L98
