### ISSUE TITLE
Debian 6: squid 3.5 packaging fails

### ISSUE THREAD

**Issue by constructs** [jordansissel/fpm#923]
Tried on a docker image

Steps:
Download squid
./configure
make
make install DESTDIR=/tmp/install

apt-get install ruby-dev gcc
sudo apt-get install libruby
sudo apt-get install ruby1.8
ln -s /usr/bin/ruby1.8 /usr/bin/ruby
sudo apt-get install rubygems
gem install fpm
fpm --version
fpm --help

mkdir fpm
cd fpm
curl -LO https://github.com/jordansissel/fpm/archive/master.zip
ls
unzip master.zip 
cd fpm-master/

User@machine:~/fpm/fpm-master# bin/fpm -s dir -t deb -n squid-ssl -v 3.5.4 -C ~/installs -p squid-ssl-3.5.4_amd64.deb                                               
Debian packaging tools generally labels all files in /etc as config files, as mandated by policy, so fpm defaults to this behavior for deb packages. You can disable this default behavior with --deb-no-default-config-files flag {:level=>:warn}
/usr/lib/ruby/1.8/find.rb:39:in `find': no block given (LocalJumpError)
        from /usr/lib/ruby/1.8/find.rb:38:in `catch'
        from /usr/lib/ruby/1.8/find.rb:38:in `find'
        from ./bin/../lib/fpm/package/deb.rb:671:in `add_path'
        from ./bin/../lib/fpm/package/deb.rb:692:in `write_conffiles'
        from ./bin/../lib/fpm/package/deb.rb:590:in `write_control_tarball'
        from ./bin/../lib/fpm/package/deb.rb:389:in `output'
        from ./bin/../lib/fpm/command.rb:475:in `execute'
        from /var/lib/gems/1.8/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'
        from ./bin/../lib/fpm/command.rb:535:in `run'
        from /var/lib/gems/1.8/gems/clamp-0.6.5/lib/clamp/command.rb:132:in `run'
        from bin/fpm:8

**Comment by constructs** [comment]
Guys, any info as to where I fail, might be really helpful.

**Comment by jeremypruitt** [comment]
I had the same issue with 1.8.7. Installing 1.9.3 helped, so I am guessing the Find class changed from 1.8.7 -> 1.9.X and now allows more than just a block as an arg. Total guess, and perhaps you can't upgrade, but thought it might help the next person.

**Comment by thefosk** [comment]
I am experiencing the same issue.

**Comment by hatt** [comment]
Tthis is a bug in Ruby 1.8.7 and not actually FPM. When the list of files is empty the `find` block is unable to yield. The only diff in this function from 1.8.7 to 1.9.3 is checking if the file exists being removed from 1.9.3. The only workaround I can offer is flag a config file (even if it's empty) so that the list isn't empty.

For the original report here, since you're in Docker and explicitly installing 18, I'd say update, but I assume others here are on older versions of Ruby due to older distros. Tools like rbenv or Docker might work for you if upgrading distro isn't an option.

**Comment by thefosk** [comment]
> Basically all I can offer is flag a config file (even if it's empty) so that the list isn't empty.

That would be great - although this is a bug in Ruby, having a workaround that can fix it would certainly help.

**Comment by hatt** [comment]
I think we can either work around it by just running say `touch .gitempty` and adding `--config-files .gitempty` to the FPM line, or possibly add an exclusion in the code for 1.8.7. I feel like custom version workarounds in code are bad since there are several issues with 1.8.7 but if it's something relatively easy to fix, we may as well. I'll try to get a PR up today and see how it goes.

**Comment by TimZehta** [comment]
I encountered the same/similar issue when trying to use fpm `1.4.0` on Ubuntu Lucid (ruby 1.8) to build a deb.

I was able to avoid the issue by using `--deb-no-default-config-files`

**Comment by hatt** [comment]
Possibly fixed by 02df699ff9c84a83ed879f89d81896cbe954f667, @constructs @jeremypruitt and @thefosk if you guys could test/confirm this is now good with 1.8.7 that'd be much appreciated :smiley:

**Comment by nicovs** [comment]
This is fixed with

ruby 1.8.7 (2011-06-30 patchlevel 352) [x86_64-linux]

**Comment by deniszh** [comment]
>Possibly fixed by 02df699

Unfortunately not. Even on ```ruby 1.8.7 (2011-06-30 patchlevel 352) [x86_64-linux]```

**Comment by hatt** [comment]
So, which way is it? Can we get some output to show the version of FPM and Ruby being used that fails @deniszh? It seems to work for @nicovs, but a sample size of 2 doesn't really show us much. Would be good if we had a unit test for it.

**Comment by deniszh** [comment]
It's ubuntu 12.04, version of ruby is above - "ruby 1.8.7 (2011-06-30 patchlevel 352) [x86_64-linux]", version of fpm - 1.4.0 (latest from gem), https://github.com/jordansissel/fpm/commit/02df699ff9c84a83ed879f89d81896cbe954f667 was applied manually. 
But I migrated to ruby1.9 after that (it's also available for ubuntu 12.04), so, can't help with that more, unfortunately. :(

**Comment by dankegel** [comment]
This just bit me on Ubuntu 12.04.  
$ sudo gem install fpm
Successfully installed fpm-1.4.0
$ fpm -s dir -t deb -n hello-main -v 0.0.1 -C dummy.7374 usr
/usr/lib/ruby/1.8/find.rb:39:in `find': no block given (LocalJumpError)
$ ruby --version
ruby 1.8.7 (2011-06-30 patchlevel 352) [x86_64-linux]

Using --deb-no-default-config-files might get me by, not sure how many places I'll need to sprinkle it.

**Comment by hatt** [comment]
Just so it's really clear, this fix has been merged but not released into a gem. FPM 1.4.0 still has the bug. The next release will include it but until then you'll need to use a Git checkout version.

**Comment by moribellamy** [comment]
is this fixed in 1.6.2?

**Comment by hatt** [comment]
@moribellamy yes
