### ISSUE TITLE
Segfault on osx 10.10 with Ruby 2.2.1

### ISSUE THREAD

**Issue by dkowis** [jordansissel/fpm#959]
Google finds me nothing about this segfault, and it works just fine in ruby 2.2.1 on Linux.

```
$ bundle exec fpm -s dir -C src -t deb -n appengine-deploy
/Library/Ruby/Gems/2.0.0/gems/ffi-1.9.10/lib/ffi_c.bundle: [BUG] Segmentation fault at 0x00000000000418
ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-darwin14]

-- Crash Report log information --------------------------------------------
   See Crash Report log file under the one of following:
     * ~/Library/Logs/CrashReporter
     * /Library/Logs/CrashReporter
     * ~/Library/Logs/DiagnosticReports
     * /Library/Logs/DiagnosticReports
   for more details.

-- Control frame information -----------------------------------------------
c:0015 p:-17578739244820 s:0045 e:000044 TOP    [FINISH]
c:0014 p:---- s:0043 e:000042 CFUNC  :require
c:0013 p:0020 s:0039 e:000038 RESCUE /Library/Ruby/Gems/2.0.0/gems/ffi-1.9.10/lib/ffi.rb:6
c:0012 p:0099 s:0036 e:000035 TOP    /Library/Ruby/Gems/2.0.0/gems/ffi-1.9.10/lib/ffi.rb:3 [FINISH]
c:0011 p:---- s:0034 e:000033 CFUNC  :require
c:0010 p:0023 s:0030 e:000029 TOP    /Library/Ruby/Gems/2.0.0/gems/fpm-1.3.3/lib/fpm/util.rb:3 [FINISH]
c:0009 p:---- s:0028 e:000027 CFUNC  :require
c:0008 p:0015 s:0024 e:000023 TOP    /Library/Ruby/Gems/2.0.0/gems/fpm-1.3.3/lib/fpm/package.rb:2 [FINISH]
c:0007 p:---- s:0022 e:000021 CFUNC  :require
c:0006 p:0015 s:0018 e:000017 TOP    /Library/Ruby/Gems/2.0.0/gems/fpm-1.3.3/lib/fpm.rb:3 [FINISH]
c:0005 p:---- s:0016 e:000015 CFUNC  :require
c:0004 p:0046 s:0012 e:000011 TOP    /Library/Ruby/Gems/2.0.0/gems/fpm-1.3.3/bin/fpm:5 [FINISH]
c:0003 p:---- s:0010 e:000009 CFUNC  :load
c:0002 p:0119 s:0006 E:001ff0 EVAL   /usr/bin/fpm:23 [FINISH]
c:0001 p:0000 s:0002 E:002140 TOP    [FINISH]

-- Ruby level backtrace information ----------------------------------------
/usr/bin/fpm:23:in `<main>'
/usr/bin/fpm:23:in `load'
/Library/Ruby/Gems/2.0.0/gems/fpm-1.3.3/bin/fpm:5:in `<top (required)>'
/Library/Ruby/Gems/2.0.0/gems/fpm-1.3.3/bin/fpm:5:in `require'
/Library/Ruby/Gems/2.0.0/gems/fpm-1.3.3/lib/fpm.rb:3:in `<top (required)>'
/Library/Ruby/Gems/2.0.0/gems/fpm-1.3.3/lib/fpm.rb:3:in `require'
/Library/Ruby/Gems/2.0.0/gems/fpm-1.3.3/lib/fpm/package.rb:2:in `<top (required)>'
/Library/Ruby/Gems/2.0.0/gems/fpm-1.3.3/lib/fpm/package.rb:2:in `require'
/Library/Ruby/Gems/2.0.0/gems/fpm-1.3.3/lib/fpm/util.rb:3:in `<top (required)>'
/Library/Ruby/Gems/2.0.0/gems/fpm-1.3.3/lib/fpm/util.rb:3:in `require'
/Library/Ruby/Gems/2.0.0/gems/ffi-1.9.10/lib/ffi.rb:3:in `<top (required)>'
/Library/Ruby/Gems/2.0.0/gems/ffi-1.9.10/lib/ffi.rb:6:in `rescue in <top (required)>'
/Library/Ruby/Gems/2.0.0/gems/ffi-1.9.10/lib/ffi.rb:6:in `require'

-- Machine register context ------------------------------------------------
 rax: 0x0000000000000030 rbx: 0x000000010a0bf766 rcx: 0x0000000000000000
 rdx: 0xfffffffffffffff0 rdi: 0x0000000000000030 rsi: 0x0000000000000000
 rbp: 0x00007fff56210340 rsp: 0x00007fff56210340  r8: 0x000000000000000b
  r9: 0x00000000fffffffe r10: 0x0000000000000a58 r11: 0x00007fff8b32ec40
 r12: 0x4c009626311ff636 r13: 0x00007fe6f2409240 r14: 0x0000000000000003
 r15: 0x00007fff562103f0 rip: 0x000000010a11749f rfl: 0x0000000000010246

-- C level backtrace information -------------------------------------------
0   ruby                                0x0000000109b8b7c5 rb_vm_bugreport + 149
1   ruby                                0x0000000109a2ea79 rb_bug_context + 473
2   ruby                                0x0000000109b05f33 sigsegv + 83
3   libsystem_platform.dylib            0x00007fff8b32df1a _sigtramp + 26
4   libruby.2.0.0.dylib                 0x000000010a11749f ruby_xmalloc + 17
5   ???                                 0x00007fff56210360 0x0 + 140734638392160

-- Other runtime information -----------------------------------------------

* Loaded script: /usr/bin/fpm

* Loaded features:

    0 enumerator.so
    1 rational.so
    2 complex.so
    3 /opt/rubies/2.2.1/lib/ruby/2.2.0/x86_64-darwin14/enc/encdb.bundle
    4 /opt/rubies/2.2.1/lib/ruby/2.2.0/x86_64-darwin14/enc/trans/transdb.bundle
    5 /opt/rubies/2.2.1/lib/ruby/2.2.0/unicode_normalize.rb
    6 /opt/rubies/2.2.1/lib/ruby/2.2.0/x86_64-darwin14/rbconfig.rb
    7 thread.rb
    8 /opt/rubies/2.2.1/lib/ruby/2.2.0/x86_64-darwin14/thread.bundle
    9 /opt/rubies/2.2.1/lib/ruby/2.2.0/rubygems/compatibility.rb
   10 /opt/rubies/2.2.1/lib/ruby/2.2.0/rubygems/defaults.rb
   11 /opt/rubies/2.2.1/lib/ruby/2.2.0/rubygems/deprecate.rb
   12 /opt/rubies/2.2.1/lib/ruby/2.2.0/rubygems/errors.rb
   13 /opt/rubies/2.2.1/lib/ruby/2.2.0/rubygems/version.rb
   14 /opt/rubies/2.2.1/lib/ruby/2.2.0/rubygems/requirement.rb
   15 /opt/rubies/2.2.1/lib/ruby/2.2.0/rubygems/platform.rb
   16 /opt/rubies/2.2.1/lib/ruby/2.2.0/rubygems/basic_specification.rb
   17 /opt/rubies/2.2.1/lib/ruby/2.2.0/rubygems/stub_specification.rb
   18 /opt/rubies/2.2.1/lib/ruby/2.2.0/rubygems/util/stringio.rb
   19 /opt/rubies/2.2.1/lib/ruby/2.2.0/rubygems/specification.rb
   20 /opt/rubies/2.2.1/lib/ruby/2.2.0/rubygems/exceptions.rb
   21 /opt/rubies/2.2.1/lib/ruby/2.2.0/rubygems/core_ext/kernel_gem.rb
   22 /opt/rubies/2.2.1/lib/ruby/2.2.0/monitor.rb
   23 /opt/rubies/2.2.1/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb
   24 /opt/rubies/2.2.1/lib/ruby/2.2.0/rubygems.rb
   25 /opt/rubies/2.2.1/lib/ruby/2.2.0/x86_64-darwin14/pathname.bundle
   26 /opt/rubies/2.2.1/lib/ruby/2.2.0/pathname.rb
   27 /Library/Ruby/Gems/2.0.0/gems/bundler-1.5.3/lib/bundler/constants.rb
   28 /opt/rubies/2.2.1/lib/ruby/2.2.0/x86_64-darwin14/io/console.bundle
   29 /opt/rubies/2.2.1/lib/ruby/2.2.0/rubygems/user_interaction.rb
   30 /opt/rubies/2.2.1/lib/ruby/2.2.0/x86_64-darwin14/etc.bundle
   31 /opt/rubies/2.2.1/lib/ruby/2.2.0/rubygems/config_file.rb
   32 /Library/Ruby/Gems/2.0.0/gems/bundler-1.5.3/lib/bundler/rubygems_integration.rb
   33 /Library/Ruby/Gems/2.0.0/gems/bundler-1.5.3/lib/bundler/current_ruby.rb
   34 /opt/rubies/2.2.1/lib/ruby/2.2.0/rubygems/dependency.rb
   35 /Library/Ruby/Gems/2.0.0/gems/bundler-1.5.3/lib/bundler/shared_helpers.rb
   36 /opt/rubies/2.2.1/lib/ruby/2.2.0/fileutils.rb
   37 /Library/Ruby/Gems/2.0.0/gems/bundler-1.5.3/lib/bundler/gem_path_manipulation.rb
   38 /Library/Ruby/Gems/2.0.0/gems/bundler-1.5.3/lib/bundler/gem_helpers.rb
   39 /Library/Ruby/Gems/2.0.0/gems/bundler-1.5.3/lib/bundler/match_platform.rb
   40 /Library/Ruby/Gems/2.0.0/gems/bundler-1.5.3/lib/bundler/rubygems_ext.rb
   41 /Library/Ruby/Gems/2.0.0/gems/bundler-1.5.3/lib/bundler/version.rb
   42 /Library/Ruby/Gems/2.0.0/gems/bundler-1.5.3/lib/bundler.rb
   43 /Library/Ruby/Gems/2.0.0/gems/bundler-1.5.3/lib/bundler/settings.rb
   44 /opt/rubies/2.2.1/lib/ruby/2.2.0/rubygems/path_support.rb
   45 /opt/rubies/2.2.1/lib/ruby/2.2.0/x86_64-darwin14/digest.bundle
   46 /opt/rubies/2.2.1/lib/ruby/2.2.0/digest.rb
   47 /opt/rubies/2.2.1/lib/ruby/2.2.0/x86_64-darwin14/digest/sha1.bundle
   48 /opt/rubies/2.2.1/lib/ruby/2.2.0/set.rb
   49 /Library/Ruby/Gems/2.0.0/gems/bundler-1.5.3/lib/bundler/definition.rb
   50 /Library/Ruby/Gems/2.0.0/gems/bundler-1.5.3/lib/bundler/dependency.rb
   51 /Library/Ruby/Gems/2.0.0/gems/bundler-1.5.3/lib/bundler/ruby_dsl.rb
   52 /Library/Ruby/Gems/2.0.0/gems/bundler-1.5.3/lib/bundler/dsl.rb
   53 /Library/Ruby/Gems/2.0.0/gems/bundler-1.5.3/lib/bundler/source.rb
   54 /opt/rubies/2.2.1/lib/ruby/2.2.0/uri/rfc2396_parser.rb
   55 /opt/rubies/2.2.1/lib/ruby/2.2.0/uri/rfc3986_parser.rb
   56 /opt/rubies/2.2.1/lib/ruby/2.2.0/uri/common.rb
   57 /opt/rubies/2.2.1/lib/ruby/2.2.0/uri/generic.rb
   58 /opt/rubies/2.2.1/lib/ruby/2.2.0/uri/ftp.rb
   59 /opt/rubies/2.2.1/lib/ruby/2.2.0/uri/http.rb
   60 /opt/rubies/2.2.1/lib/ruby/2.2.0/uri/https.rb
   61 /opt/rubies/2.2.1/lib/ruby/2.2.0/uri/ldap.rb
   62 /opt/rubies/2.2.1/lib/ruby/2.2.0/uri/ldaps.rb
   63 /opt/rubies/2.2.1/lib/ruby/2.2.0/uri/mailto.rb
   64 /opt/rubies/2.2.1/lib/ruby/2.2.0/uri.rb
   65 /opt/rubies/2.2.1/lib/ruby/2.2.0/x86_64-darwin14/socket.bundle
   66 /opt/rubies/2.2.1/lib/ruby/2.2.0/socket.rb
   67 /opt/rubies/2.2.1/lib/ruby/2.2.0/timeout.rb
   68 /opt/rubies/2.2.1/lib/ruby/2.2.0/net/protocol.rb
   69 /opt/rubies/2.2.1/lib/ruby/2.2.0/x86_64-darwin14/zlib.bundle
   70 /opt/rubies/2.2.1/lib/ruby/2.2.0/x86_64-darwin14/stringio.bundle
   71 /opt/rubies/2.2.1/lib/ruby/2.2.0/net/http/exceptions.rb
   72 /opt/rubies/2.2.1/lib/ruby/2.2.0/net/http/header.rb
   73 /opt/rubies/2.2.1/lib/ruby/2.2.0/x86_64-darwin14/enc/windows_31j.bundle
   74 /opt/rubies/2.2.1/lib/ruby/2.2.0/net/http/generic_request.rb
   75 /opt/rubies/2.2.1/lib/ruby/2.2.0/net/http/request.rb
   76 /opt/rubies/2.2.1/lib/ruby/2.2.0/net/http/requests.rb
   77 /opt/rubies/2.2.1/lib/ruby/2.2.0/net/http/response.rb
   78 /opt/rubies/2.2.1/lib/ruby/2.2.0/net/http/responses.rb
   79 /opt/rubies/2.2.1/lib/ruby/2.2.0/net/http/proxy_delta.rb
   80 /opt/rubies/2.2.1/lib/ruby/2.2.0/net/http/backward.rb
   81 /opt/rubies/2.2.1/lib/ruby/2.2.0/net/http.rb
   82 /opt/rubies/2.2.1/lib/ruby/2.2.0/x86_64-darwin14/date_core.bundle
   83 /opt/rubies/2.2.1/lib/ruby/2.2.0/date.rb
   84 /opt/rubies/2.2.1/lib/ruby/2.2.0/time.rb
   85 /opt/rubies/2.2.1/lib/ruby/2.2.0/rubygems/request/http_pool.rb
   86 /opt/rubies/2.2.1/lib/ruby/2.2.0/rubygems/request/https_pool.rb
   87 /opt/rubies/2.2.1/lib/ruby/2.2.0/rubygems/request/connection_pools.rb
   88 /opt/rubies/2.2.1/lib/ruby/2.2.0/rubygems/request.rb
   89 /opt/rubies/2.2.1/lib/ruby/2.2.0/cgi/core.rb
   90 /opt/rubies/2.2.1/lib/ruby/2.2.0/cgi/util.rb
   91 /opt/rubies/2.2.1/lib/ruby/2.2.0/cgi/cookie.rb
   92 /opt/rubies/2.2.1/lib/ruby/2.2.0/cgi.rb
   93 /opt/rubies/2.2.1/lib/ruby/2.2.0/rubygems/uri_formatter.rb
   94 /opt/rubies/2.2.1/lib/ruby/2.2.0/x86_64-darwin14/openssl.bundle
   95 /opt/rubies/2.2.1/lib/ruby/2.2.0/openssl/bn.rb
   96 /opt/rubies/2.2.1/lib/ruby/2.2.0/openssl/cipher.rb
   97 /opt/rubies/2.2.1/lib/ruby/2.2.0/openssl/config.rb
   98 /opt/rubies/2.2.1/lib/ruby/2.2.0/openssl/digest.rb
   99 /opt/rubies/2.2.1/lib/ruby/2.2.0/openssl/x509.rb
  100 /opt/rubies/2.2.1/lib/ruby/2.2.0/openssl/buffering.rb
  101 /opt/rubies/2.2.1/lib/ruby/2.2.0/x86_64-darwin14/fcntl.bundle
  102 /opt/rubies/2.2.1/lib/ruby/2.2.0/openssl/ssl.rb
  103 /opt/rubies/2.2.1/lib/ruby/2.2.0/openssl.rb
  104 /opt/rubies/2.2.1/lib/ruby/2.2.0/securerandom.rb
  105 /opt/rubies/2.2.1/lib/ruby/2.2.0/resolv.rb
  106 /opt/rubies/2.2.1/lib/ruby/2.2.0/rubygems/remote_fetcher.rb
  107 /opt/rubies/2.2.1/lib/ruby/2.2.0/rubygems/text.rb
  108 /opt/rubies/2.2.1/lib/ruby/2.2.0/rubygems/name_tuple.rb
  109 /opt/rubies/2.2.1/lib/ruby/2.2.0/rubygems/spec_fetcher.rb
  110 /Library/Ruby/Gems/2.0.0/gems/bundler-1.5.3/lib/bundler/source/rubygems.rb
  111 /opt/rubies/2.2.1/lib/ruby/2.2.0/x86_64-darwin14/strscan.bundle
  112 /Library/Ruby/Gems/2.0.0/gems/bundler-1.5.3/lib/bundler/source/path.rb
  113 /Library/Ruby/Gems/2.0.0/gems/bundler-1.5.3/lib/bundler/source/git.rb
  114 /Library/Ruby/Gems/2.0.0/gems/bundler-1.5.3/lib/bundler/lockfile_parser.rb
  115 /Library/Ruby/Gems/2.0.0/gems/bundler-1.5.3/lib/bundler/lazy_specification.rb
  116 /opt/rubies/2.2.1/lib/ruby/2.2.0/tsort.rb
  117 /opt/rubies/2.2.1/lib/ruby/2.2.0/forwardable.rb
  118 /Library/Ruby/Gems/2.0.0/gems/bundler-1.5.3/lib/bundler/spec_set.rb
  119 /Library/Ruby/Gems/2.0.0/gems/bundler-1.5.3/lib/bundler/environment.rb
  120 /Library/Ruby/Gems/2.0.0/gems/bundler-1.5.3/lib/bundler/runtime.rb
  121 /Library/Ruby/Gems/2.0.0/gems/bundler-1.5.3/lib/bundler/index.rb
  122 /Library/Ruby/Gems/2.0.0/gems/bundler-1.5.3/lib/bundler/remote_specification.rb
  123 /Library/Ruby/Gems/2.0.0/gems/bundler-1.5.3/lib/bundler/endpoint_specification.rb
  124 /Library/Ruby/Gems/2.0.0/gems/bundler-1.5.3/lib/bundler/dep_proxy.rb
  125 /Library/Ruby/Gems/2.0.0/gems/bundler-1.5.3/lib/bundler/setup.rb
  126 /Library/Ruby/Gems/2.0.0/gems/fpm-1.3.3/lib/fpm/namespace.rb
  127 /Library/Ruby/Gems/2.0.0/gems/childprocess-0.5.6/lib/childprocess/errors.rb
  128 /Library/Ruby/Gems/2.0.0/gems/childprocess-0.5.6/lib/childprocess/abstract_process.rb
  129 /Library/Ruby/Gems/2.0.0/gems/childprocess-0.5.6/lib/childprocess/abstract_io.rb
  130 /Library/Ruby/Gems/2.0.0/gems/childprocess-0.5.6/lib/childprocess/unix/io.rb
  131 /Library/Ruby/Gems/2.0.0/gems/childprocess-0.5.6/lib/childprocess/unix/process.rb
  132 /Library/Ruby/Gems/2.0.0/gems/childprocess-0.5.6/lib/childprocess/unix/fork_exec_process.rb
  133 /Library/Ruby/Gems/2.0.0/gems/childprocess-0.5.6/lib/childprocess/unix.rb
  134 /Library/Ruby/Gems/2.0.0/gems/childprocess-0.5.6/lib/childprocess.rb

[NOTE]
You may have encountered a bug in the Ruby interpreter or extension libraries.
Bug reports are welcome.
Don't forget to include the above Crash Report log file.
For details: http://www.ruby-lang.org/bugreport.html

Abort trap: 6
```

**Comment by hatt** [comment]
Almost a complete guess but the problem looks to be in FFI. How is your Ruby installed? The path looks a bit odd. FFI is a lib for linking C libraries with the Ruby runtime without actually compiling them against it, so it might be a bug in libffi, ruby-ffi, or just you've updated one or another with homebrew/rbenv/whatever and now the ABI has a mismatch. Reinstalling libffi or rebuilding the ruby install or ffi gem might fix it.

**Comment by dkowis** [comment]
It's installed as part of boxen, which uses this: https://github.com/boxen/puppet-ruby

I'll try reinstalling those mentioned packages...

**Comment by hatt** [comment]
Rbenv can sometimes do this but usually someone has installed libffi from homebrew, updated it, and cleaned the old one with ruby-ffi is still linked to it. I don't see a linker error here though so it looks more like a bad build of libffi; definitely try updating to a later (or stable older) version there. It could also be a problem in ruby-ffi itself but since nobody else has reported any issues, I'm not convinced.

**Comment by Zhomart** [comment]
Unrelated to this project. I've faced crash while running resque (1.24.5) worker on rails (4.2). I was using ffi (1.9.10).
Now I downgraded ffi to "1.9.8" and resque worker works as expected.
