### ISSUE TITLE
License issue when making python module mysql for deb

### ISSUE THREAD

**Issue by adminempire** [jordansissel/fpm#964]
I get the following error when I am trying to make a deb for the python module mysql 

```
fpm --name python-mysql --epoch 1 --iteration 1 -m me@spam.com --description 'BLAH maintained python module mysql' --python-bin '/usr/bin/python2' -s python -t deb mysql
/usr/lib/ruby/gems/2.2.0/gems/fpm-1.3.3/lib/fpm/package/python.rb:206:in `load_package_info': undefined method `split' for ["GPL"]:Array (NoMethodError)
	from /usr/lib/ruby/gems/2.2.0/gems/fpm-1.3.3/lib/fpm/package/python.rb:96:in `input'
	from /usr/lib/ruby/gems/2.2.0/gems/fpm-1.3.3/lib/fpm/command.rb:332:in `block in execute'
	from /usr/lib/ruby/gems/2.2.0/gems/fpm-1.3.3/lib/fpm/command.rb:331:in `each'
	from /usr/lib/ruby/gems/2.2.0/gems/fpm-1.3.3/lib/fpm/command.rb:331:in `execute'
	from /usr/lib/ruby/gems/2.2.0/gems/clamp-0.6.3/lib/clamp/command.rb:67:in `run'
	from /usr/lib/ruby/gems/2.2.0/gems/fpm-1.3.3/lib/fpm/command.rb:510:in `run'
	from /usr/lib/ruby/gems/2.2.0/gems/clamp-0.6.3/lib/clamp/command.rb:125:in `run'
	from /usr/lib/ruby/gems/2.2.0/gems/fpm-1.3.3/bin/fpm:8:in `<top (required)>'
	from /usr/bin/fpm:23:in `load'
	from /usr/bin/fpm:23:in `<main>'
```

**Comment by adminempire** [comment]
Noticed I was using an old version updated and same results 

/usr/lib/ruby/gems/2.2.0/gems/fpm-1.4.0/lib/fpm/package/python.rb:210:in `load_package_info': undefined method `split' for ["GPL"]:Array (NoMethodError)
	from /usr/lib/ruby/gems/2.2.0/gems/fpm-1.4.0/lib/fpm/package/python.rb:100:in `input'
	from /usr/lib/ruby/gems/2.2.0/gems/fpm-1.4.0/lib/fpm/command.rb:341:in `block in execute'
	from /usr/lib/ruby/gems/2.2.0/gems/fpm-1.4.0/lib/fpm/command.rb:340:in `each'
	from /usr/lib/ruby/gems/2.2.0/gems/fpm-1.4.0/lib/fpm/command.rb:340:in `execute'
	from /usr/lib/ruby/gems/2.2.0/gems/clamp-0.6.3/lib/clamp/command.rb:67:in `run'
	from /usr/lib/ruby/gems/2.2.0/gems/fpm-1.4.0/lib/fpm/command.rb:535:in `run'
	from /usr/lib/ruby/gems/2.2.0/gems/clamp-0.6.3/lib/clamp/command.rb:125:in `run'
	from /usr/lib/ruby/gems/2.2.0/gems/fpm-1.4.0/bin/fpm:8:in `<top (required)>'
	from /usr/bin/fpm:23:in `load'
	from /usr/bin/fpm:23:in `<main>'

**Comment by hatt** [comment]
License must be a string, not an array. It looks like the inline python metadata collector (I'm not entirely sure why this is even needed, or why virtualenv is split from the main python module) outputs it as an array for this module. Can you see if this happens for other single-license and multi-license python modules? If it's a standard across python licenses, we can update the ruby side to treat it like an array, otherwise we'll need to fix the metadata script.
