### ISSUE TITLE
Unable to execute it on Ubuntu 14.04

### ISSUE THREAD

**Issue by simonbcn** [jordansissel/fpm#974]
Ubuntu 14.04 64 bits
node.js v0.12.7 installed with NVM

The installation:
```
$ npm install -g fpm
npm WARN peerDependencies The peer dependency grunt@~0.4.0 included from blockparser will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
/home/simon/.nvm/versions/node/v0.12.7/bin/fpm -> /home/simon/.nvm/versions/node/v0.12.7/lib/node_modules/fpm/bin/iffront
fpm@1.4.4 /home/simon/.nvm/versions/node/v0.12.7/lib/node_modules/fpm
├── which@1.0.9
├── osenv@0.0.3
├── abbrev@1.0.7
├── archy@0.0.2
├── graceful-fs@2.0.3
├── rimraf@2.2.6
├── p-throttler@0.0.1
├── nopt@2.2.1
├── tmp@0.0.20
├── chalk@0.2.1 (ansi-styles@0.2.0, has-color@0.1.7)
├── q@0.9.7
├── sudo-block@0.2.1 (chalk@0.1.1)
├── shelljs@0.2.6
├── ejs@0.8.8
├── minimatch@0.2.14 (sigmund@1.0.1, lru-cache@2.6.5)
├── send@0.1.4 (range-parser@0.0.4, fresh@0.2.0, mime@1.2.11, debug@2.2.0)
├── glob@3.2.11 (inherits@2.0.1, minimatch@0.3.0)
├── iconv-lite@0.2.11
├── lodash@2.2.1
├── file-utils@0.1.5 (isbinaryfile@0.1.9, lodash@2.1.0, findup-sync@0.1.3)
├── inquirer@0.3.5 (mute-stream@0.0.3, async@0.2.10, lodash@1.2.1, cli-color@0.2.3)
├── wm@1.2.1 (cssmin@0.4.3, uglify-js@2.4.24, jshint@2.4.3, grunt@0.4.5, blockparser@1.0.0)
├── mout@0.7.1
├── update-notifier@0.2.2 (is-npm@1.0.0, chalk@0.5.1, string-length@1.0.1, semver-diff@2.0.0, latest-version@1.0.1, configstore@0.3.2)
├── bower@1.2.8 (junk@0.2.2, stringify-object@0.1.8, chmodr@0.1.1, open@0.0.5, bower-logger@0.2.2, bower-endpoint-parser@0.2.2, lru-cache@2.3.1, nopt@2.1.2, retry@0.6.1, mkdirp@0.3.5, request-progress@0.3.1, semver@2.1.0, bower-json@0.4.0, promptly@0.2.1, fstream-ignore@0.0.10, tar@0.1.20, fstream@0.1.31, decompress-zip@0.0.8, request@2.27.0, handlebars@1.0.12, cardinal@0.4.4, bower-config@0.5.2, bower-registry-client@0.1.6, update-notifier@0.1.10)
└── connect@2.12.0 (uid2@0.0.3, methods@0.1.0, debug@0.8.1, cookie-signature@1.0.1, pause@0.0.1, fresh@0.2.0, qs@0.6.6, bytes@0.2.1, buffer-crc32@0.2.1, raw-body@1.1.2, batch@0.5.0, cookie@0.1.0, negotiator@0.3.0, multiparty@2.2.0)
```

When I execute it:
```
$ fpm --help
/home/simon/.nvm/versions/node/v0.12.7/lib/node_modules/fpm/node_modules/tmp/lib/tmp.js:260
  throw err;
        ^
TypeError: Cannot read property 'line' of undefined
    at Object.<anonymous> (/home/simon/.nvm/versions/node/v0.12.7/lib/node_modules/fpm/bin/iffront:49:15)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

**Comment by lesinigo** [comment]
`fpm` on node/npm is a ***Javascript package*** with description "前端自动化工具" (whatever that means, I can't understand it), but you filed an issue on the `fpm` ***ruby gem*** (Effing Package Management). I guess you have a problem here :)

**Comment by epylar** [comment]
前端自动化工具 translates to "front-end automation tools" on Google Translate
