### ISSUE TITLE
FPM recently started failing with ruby exception.

### ISSUE THREAD

**Issue by sashalionheart** [jordansissel/fpm#975]
We have been using FPM in the following project: https://github.com/GoogleCloudPlatform/compute-user-accounts

Recently the following command:
fpm -t deb -p pkg/  -d "libc6 >= 2.12" -d "libstdc++6 >= 4.4.7" -s dir -n "gcua" -v 0.20150806.182155 -a native --license "Apache 2.0" -m "gc-team@google.com" --description "Google Compute User Accounts." --url "https://github.com/GoogleCloudPlatform/compute-user-accounts" --vendor "Google Inc." --after-install etc/after-install.sh --before-remove etc/before-remove.sh --after-remove etc/after-remove.sh /home/lionhearts/go/bin/gcua=/usr/share/google/ /home/lionhearts/go/bin/authorizedkeys=/usr/share/google/ nssplugin/bin/libnss_google.so.2.0.1=/usr/lib/ etc/init.d/gcua etc/sudoers.d/gcua etc/systemd/system/gcua.service

Started failing with the following error:
/usr/lib/ruby/1.8/find.rb:39:in `find': no block given (LocalJumpError)
        from /usr/lib/ruby/1.8/find.rb:38:in `catch'
        from /usr/lib/ruby/1.8/find.rb:38:in `find'
        from /usr/lib/ruby/gems/1.8/gems/fpm-1.4.0/lib/fpm/package/deb.rb:672:in `add_path'
        from /usr/lib/ruby/gems/1.8/gems/fpm-1.4.0/lib/fpm/package/deb.rb:680:in `write_conffiles'
        from /usr/lib/ruby/gems/1.8/gems/fpm-1.4.0/lib/fpm/package/deb.rb:678:in `each'
        from /usr/lib/ruby/gems/1.8/gems/fpm-1.4.0/lib/fpm/package/deb.rb:678:in `write_conffiles'
        from /usr/lib/ruby/gems/1.8/gems/fpm-1.4.0/lib/fpm/package/deb.rb:590:in `write_control_tarball'
        from /usr/lib/ruby/gems/1.8/gems/fpm-1.4.0/lib/fpm/package/deb.rb:389:in `output'
        from /usr/lib/ruby/gems/1.8/gems/fpm-1.4.0/lib/fpm/command.rb:475:in `execute'
        from /usr/lib/ruby/gems/1.8/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'
        from /usr/lib/ruby/gems/1.8/gems/fpm-1.4.0/lib/fpm/command.rb:535:in `run'
        from /usr/lib/ruby/gems/1.8/gems/clamp-0.6.5/lib/clamp/command.rb:132:in `run'
        from /usr/lib/ruby/gems/1.8/gems/fpm-1.4.0/bin/fpm:8
        from /usr/bin/fpm:19:in `load'
        from /usr/bin/fpm:19

I have tried to poke around to see what is failing, but my lack of Ruby knowledge makes this difficult. Is this a regression?

**Comment by jordansissel** [comment]
Yeah this is a regression. I will get a fix out for this soon!

**Comment by sashalionheart** [comment]
FYI, there's a suggested fix here: https://github.com/jordansissel/fpm/pull/965

**Comment by jordansissel** [comment]
Oh neat, someone already made a patch? <3 people.

I'll review now. Thanks for digging!

**Comment by JokerQyou** [comment]
Is this considered as fixed? I did see #965 got merged by August last year, but I believe the latest fpm release is `1.4.0` which was released July last year.
