### ISSUE TITLE
how to run tests?

### ISSUE THREAD

**Issue by glensc** [jordansissel/fpm#992]
it would be useful to document in readme.md (or separate testing.md?) or at least indicate and point how to run tests for fpm.

i've done some digging, and here's what i've found out myself:

  - to run all tests  
`rspec`
  - run tests from `spec/fpm/package/rpm_spec.rb` only  
`rspec spec/fpm/package/rpm_spec.rb`
  - run specific test from `spec/fpm/package/rpm_spec.rb` on line 127 ([answer from stackoverflow](http://stackoverflow.com/a/6116744))  
`rspec spec/fpm/package/rpm_spec.rb:127`

here's example output from the last command:
```

➔ rspec spec/fpm/package/rpm_spec.rb:127
Run options: include {:locations=>{"./spec/fpm/package/rpm_spec.rb"=>[127]}}
F

Failures:

  1) FPM::Package::RPM#output architecture can be basically anything
     Failure/Error: subject.output(target)
     FPM::Util::ProcessFailed:
       rpmbuild failed (exit code 1). Full command was:["rpmbuild", "-bb", "--target", "fancypants", "--define", "buildroot /home/users/glen/tmp/package-rpm-build20150825-139056-1m8r9bq/BUILD", "--define", "_topdir /home/users/glen/tmp/package-rpm-build20150825-139056-1m8r9bq", "--define", "_sourcedir /home/users/glen/tmp/package-rpm-build20150825-139056-1m8r9bq", "--define", "_rpmdir /home/users/glen/tmp/package-rpm-build20150825-139056-1m8r9bq/RPMS", "/home/users/glen/tmp/package-rpm-build20150825-139056-1m8r9bq/SPECS/example.spec"]
     # ./lib/fpm/util.rb:83:in `safesystem'
     # ./lib/fpm/package/rpm.rb:498:in `output'
     # ./spec/fpm/package/rpm_spec.rb:134:in `block (4 levels) in <top (required)>'

Finished in 0.77373 seconds
1 example, 1 failure

Failed examples:

rspec ./spec/fpm/package/rpm_spec.rb:127 # FPM::Package::RPM#output architecture can be basically anything
```

also, this is fpm specific, how to see the output of executed rpmbuild command? as when the test finishes the files are removed, can't reproduce from terminal myself

**Comment by hatt** [comment]
Sounds like something we could add to README.md pretty easily, just a subheader for testing and the usual `bundle install` and `bundle exec rspec`. Not sure on your latter question though, @jordansissel ?

**Comment by jordansissel** [comment]
#1681 will improve this and, I hope, make it easier for folks to run the test suite!
